//
//  SFSymbolSourceFileGenerator.swift
//  SFSymbolKit
//
//  Created by LiYanan2004 on 2025/11/9.
//

import Foundation
import SwiftSyntax
import SwiftSyntaxBuilder

package struct SFSymbolSourceFileGenerator {
    package let outputURL: URL
    
    package init(outputURL: URL) {
        self.outputURL = outputURL
    }
    
    package func generate() throws {
        try FileManager.default.createDirectoryIfNecessary(
            for: outputURL.deletingLastPathComponent()
        )
        try sourceFile.description
            .write(to: outputURL, atomically: true, encoding: .utf8)
    }
    
    private var sourceFile: some SyntaxProtocol {
        get throws {
            let header = """
            //
            // \(outputURL.lastPathComponent)
            // Generated by SymbolGenPlugin – do not edit.
            //
            """
            
            return try SourceFileSyntax {
                try StructDeclSyntax(
                    "public struct SFSymbol: RawRepresentable, Hashable, Equatable, Sendable"
                ) {
                    try VariableDeclSyntax("public var rawValue: String")
                        .with(\.leadingTrivia, .newline)
                    
                    try InitializerDeclSyntax("""
                    public init(rawValue: String) {
                        self.rawValue = rawValue
                    }
                    """)
                    .with(\.leadingTrivia, .newline)
                    
                    try sfSymbolMembers
                }
            }
            .with(\.leadingTrivia, Trivia(stringLiteral: header) + .newline)
        }
    }
    
    private var sfSymbolMembers: [DeclSyntax] {
        get throws {
            try SFSymbols_Private.allSymbols.map { symbol in
                let availabilities = symbol.availabilities
                let availabilityAttribute = AttributeSyntax(
                    stringLiteral: "@available(\(availabilities.joined(separator: ", ")), *)"
                ).with(\.trailingTrivia, .newline)
                
                let identifier = symbol.identifier.replacingOccurrences(of: ".", with: "_")
                let validIdentifier = identifier.isValidSwiftIdentifier(for: .variableName) ? identifier : "`\(identifier)`"
                
                return try DeclSyntax(
                    VariableDeclSyntax(
                        "static public let \(raw: validIdentifier) = SFSymbol(rawValue: \"\(raw: symbol.identifier)\")"
                    )
                    .with(\.attributes, [.attribute(availabilityAttribute)])
                    .with(\.leadingTrivia, .newlines(2))
                )
            }
        }
    }
}
