//
//  PrivateSFSymbols.2023.1.swift
//
//  Automatically generated by SFSymbolKit.
//  Do not edit directly!
//  swift-format-ignore-file

@_documentation(visibility: internal)
@available(iOS 17.1, macOS 14.1, tvOS 17.1, visionOS 1.0, watchOS 10.1, *)
extension PrivateSFSymbol {
	/// 􂉢 `person.and.rectangle.far`
	///
	/// - categories:
	///   - `human`
	///
	/// - search keywords:
	///   - `people`
	///   - `person`
	static public let person_and_rectangle_far = PrivateSFSymbol(identifier: "person.and.rectangle.far")

	/// 􂉣 `person.and.rectangle.near`
	///
	/// - categories:
	///   - `human`
	///
	/// - search keywords:
	///   - `people`
	///   - `person`
	static public let person_and_rectangle_near = PrivateSFSymbol(identifier: "person.and.rectangle.near")

	/// 􂉑 `apps.iphone.assistive.access`
	///
	/// - categories:
	///   - `devices`
	static public let apps_iphone_assistive_access = PrivateSFSymbol(identifier: "apps.iphone.assistive.access")

	/// 􂉒 `iphone.always.on.display`
	///
	/// - categories:
	///   - `devices`
	static public let iphone_always_on_display = PrivateSFSymbol(identifier: "iphone.always.on.display")

	/// 􂉋 `persona.circle`
	///
	/// - categories:
	///   - `human`
	///
	/// - search keywords:
	///   - `people`
	///   - `person`
	static public let persona_circle = PrivateSFSymbol(identifier: "persona.circle")

	/// 􂉌 `persona.circle.fill`
	///
	/// - categories:
	///   - `human`
	///   - `multicolor`
	///
	/// - search keywords:
	///   - `people`
	///   - `person`
	static public let persona_circle_fill = PrivateSFSymbol(identifier: "persona.circle.fill")

	/// 􂉍 `persona.crop.circle`
	///
	/// - categories:
	///   - `human`
	///
	/// - search keywords:
	///   - `people`
	///   - `person`
	static public let persona_crop_circle = PrivateSFSymbol(identifier: "persona.crop.circle")

	/// 􂉎 `persona.crop.circle.fill`
	///
	/// - categories:
	///   - `human`
	///   - `multicolor`
	///
	/// - search keywords:
	///   - `people`
	///   - `person`
	static public let persona_crop_circle_fill = PrivateSFSymbol(identifier: "persona.crop.circle.fill")

	/// 􂈌 `persona.crop.square`
	///
	/// - categories:
	///   - `human`
	///
	/// - search keywords:
	///   - `people`
	///   - `person`
	static public let persona_crop_square = PrivateSFSymbol(identifier: "persona.crop.square")

	/// 􂈍 `persona.crop.square.fill`
	///
	/// - categories:
	///   - `human`
	///   - `multicolor`
	///
	/// - search keywords:
	///   - `people`
	///   - `person`
	static public let persona_crop_square_fill = PrivateSFSymbol(identifier: "persona.crop.square.fill")

	/// 􂈎 `persona.crop.square.slash`
	///
	/// - categories:
	///   - `human`
	///
	/// - search keywords:
	///   - `people`
	///   - `person`
	static public let persona_crop_square_slash = PrivateSFSymbol(identifier: "persona.crop.square.slash")

	/// 􂈏 `persona.crop.square.slash.fill`
	///
	/// - categories:
	///   - `human`
	///
	/// - search keywords:
	///   - `people`
	///   - `person`
	static public let persona_crop_square_slash_fill = PrivateSFSymbol(identifier: "persona.crop.square.slash.fill")

	/// 􂉂 `voice.control`
	///
	/// - categories:
	///   - `accessibility`
	///   - `variablecolor`
	///
	/// - search keywords:
	///   - `voice control`
	static public let voice_control = PrivateSFSymbol(identifier: "voice.control")

	/// 􂉃 `voice.control.circle`
	///
	/// - categories:
	///   - `accessibility`
	///   - `variablecolor`
	///
	/// - search keywords:
	///   - `voice control`
	static public let voice_control_circle = PrivateSFSymbol(identifier: "voice.control.circle")

	/// 􂉄 `voice.control.circle.fill`
	///
	/// - categories:
	///   - `accessibility`
	///   - `multicolor`
	///   - `variablecolor`
	///
	/// - search keywords:
	///   - `voice control`
	static public let voice_control_circle_fill = PrivateSFSymbol(identifier: "voice.control.circle.fill")

	/// 􂉅 `voice.control.slash`
	///
	/// - categories:
	///   - `accessibility`
	///
	/// - search keywords:
	///   - `voice control`
	static public let voice_control_slash = PrivateSFSymbol(identifier: "voice.control.slash")

	/// 􂉆 `voice.control.slash.circle`
	///
	/// - categories:
	///   - `accessibility`
	///
	/// - search keywords:
	///   - `voice control`
	static public let voice_control_slash_circle = PrivateSFSymbol(identifier: "voice.control.slash.circle")

	/// 􂉇 `voice.control.slash.circle.fill`
	///
	/// - categories:
	///   - `accessibility`
	///   - `multicolor`
	///
	/// - search keywords:
	///   - `voice control`
	static public let voice_control_slash_circle_fill = PrivateSFSymbol(identifier: "voice.control.slash.circle.fill")

	/// 􂉙 `dot.arrowtriangles.up.right.down.left`
	///
	/// - categories:
	///   - `accessibility`
	static public let dot_arrowtriangles_up_right_down_left = PrivateSFSymbol(identifier: "dot.arrowtriangles.up.right.down.left")
}