//
//  PrivateSFSymbols.2021.swift
//
//  Automatically generated by SFSymbolKit.
//  Do not edit directly!
//  swift-format-ignore-file

@_documentation(visibility: internal)
@available(iOS 15.0, macOS 12.0, tvOS 15.0, visionOS 1.0, watchOS 8.0, *)
extension PrivateSFSymbol {
	/// 􁀝 `quicknote`
	static public let quicknote = PrivateSFSymbol(identifier: "quicknote")

	/// 􀸃 `newsplus`
	static public let newsplus = PrivateSFSymbol(identifier: "newsplus")

	/// 􀸄 `newsplus.fill`
	static public let newsplus_fill = PrivateSFSymbol(identifier: "newsplus.fill")

	/// 􀺷 `person.raised.hand`
	///
	/// - categories:
	///   - `human`
	///
	/// - search keywords:
	///   - `people`
	static public let person_raised_hand = PrivateSFSymbol(identifier: "person.raised.hand")

	/// 􁇧 `person.raised.hand.circle`
	///
	/// - categories:
	///   - `human`
	///
	/// - search keywords:
	///   - `people`
	static public let person_raised_hand_circle = PrivateSFSymbol(identifier: "person.raised.hand.circle")

	/// 􁇨 `person.raised.hand.circle.fill`
	///
	/// - categories:
	///   - `human`
	///   - `multicolor`
	///
	/// - search keywords:
	///   - `people`
	static public let person_raised_hand_circle_fill = PrivateSFSymbol(identifier: "person.raised.hand.circle.fill")

	/// 􁆺 `person.2.badge.heart`
	///
	/// - categories:
	///   - `human`
	///   - `multicolor`
	///
	/// - search keywords:
	///   - `people`
	static public let person_2_badge_heart = PrivateSFSymbol(identifier: "person.2.badge.heart")

	/// 􁆻 `person.2.badge.heart.fill`
	///
	/// - categories:
	///   - `human`
	///   - `multicolor`
	///
	/// - search keywords:
	///   - `people`
	static public let person_2_badge_heart_fill = PrivateSFSymbol(identifier: "person.2.badge.heart.fill")

	/// 􀹿 `person.lanyardcard`
	///
	/// - categories:
	///   - `human`
	///   - `objectsandtools`
	///
	/// - search keywords:
	///   - `people`
	///   - `work`
	static public let person_lanyardcard = PrivateSFSymbol(identifier: "person.lanyardcard")

	/// 􀺀 `person.lanyardcard.fill`
	///
	/// - categories:
	///   - `human`
	///   - `objectsandtools`
	///
	/// - search keywords:
	///   - `people`
	///   - `work`
	static public let person_lanyardcard_fill = PrivateSFSymbol(identifier: "person.lanyardcard.fill")

	/// 􁇩 `person.lanyardcard.circle`
	///
	/// - categories:
	///   - `human`
	///   - `objectsandtools`
	///
	/// - search keywords:
	///   - `people`
	///   - `work`
	static public let person_lanyardcard_circle = PrivateSFSymbol(identifier: "person.lanyardcard.circle")

	/// 􁇪 `person.lanyardcard.circle.fill`
	///
	/// - categories:
	///   - `human`
	///   - `multicolor`
	///   - `objectsandtools`
	///
	/// - search keywords:
	///   - `people`
	///   - `work`
	static public let person_lanyardcard_circle_fill = PrivateSFSymbol(identifier: "person.lanyardcard.circle.fill")

	/// 􀼇 `gymkit`
	static public let gymkit = PrivateSFSymbol(identifier: "gymkit")

	/// 􁃖 `music.badge.plus`
	///
	/// - categories:
	///   - `multicolor`
	///
	/// - search keywords:
	///   - `apple music`
	static public let music_badge_plus = PrivateSFSymbol(identifier: "music.badge.plus")

	/// 􀶹 `music.on.film`
	///
	/// - search keywords:
	///   - `media`
	static public let music_on_film = PrivateSFSymbol(identifier: "music.on.film")

	/// 􀝺 `appstore.capsule.2.fill`
	///
	/// - categories:
	///   - `multicolor`
	static public let appstore_capsule_2_fill = PrivateSFSymbol(identifier: "appstore.capsule.2.fill")

	/// 􀿉 `appstore.app`
	///
	/// - categories:
	///   - `multicolor`
	static public let appstore_app = PrivateSFSymbol(identifier: "appstore.app")

	/// 􀿊 `appstore.app.fill`
	///
	/// - categories:
	///   - `multicolor`
	static public let appstore_app_fill = PrivateSFSymbol(identifier: "appstore.app.fill")

	/// 􀽃 `bluetooth.square`
	///
	/// - categories:
	///   - `connectivity`
	///   - `multicolor`
	static public let bluetooth_square = PrivateSFSymbol(identifier: "bluetooth.square")

	/// 􀽄 `bluetooth.square.fill`
	///
	/// - categories:
	///   - `connectivity`
	///   - `multicolor`
	static public let bluetooth_square_fill = PrivateSFSymbol(identifier: "bluetooth.square.fill")

	/// 􁂢 `images.magnifyingglass`
	///
	/// - categories:
	///   - `objectsandtools`
	static public let images_magnifyingglass = PrivateSFSymbol(identifier: "images.magnifyingglass")

	/// 􀮒 `location.appclip`
	static public let location_appclip = PrivateSFSymbol(identifier: "location.appclip")

	/// 􁀏 `arrow.up.forward.appclip`
	static public let arrow_up_forward_appclip = PrivateSFSymbol(identifier: "arrow.up.forward.appclip")

	/// 􀦦 `star.circle.badge.person.crop`
	///
	/// - categories:
	///   - `multicolor`
	///
	/// - search keywords:
	///   - `favorite`
	///   - `people`
	static public let star_circle_badge_person_crop = PrivateSFSymbol(identifier: "star.circle.badge.person.crop")

	/// 􀾓 `location.fill.radiowaves.left.and.right`
	///
	/// - categories:
	///   - `arrows`
	///   - `variablecolor`
	static public let location_fill_radiowaves_left_and_right = PrivateSFSymbol(identifier: "location.fill.radiowaves.left.and.right")

	/// 􁃥 `laugh`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `haha`
	static public let laugh = PrivateSFSymbol(identifier: "laugh")

	/// 􁃩 `laugh.es`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `haha`
	static public let laugh_es = PrivateSFSymbol(identifier: "laugh.es")

	/// 􀴫 `laugh.el`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `haha`
	static public let laugh_el = PrivateSFSymbol(identifier: "laugh.el")

	/// 􀴬 `laugh.ru`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `haha`
	static public let laugh_ru = PrivateSFSymbol(identifier: "laugh.ru")

	/// 􀴭 `laugh.it`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `haha`
	static public let laugh_it = PrivateSFSymbol(identifier: "laugh.it")

	/// 􀴮 `laugh.ar`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `haha`
	static public let laugh_ar = PrivateSFSymbol(identifier: "laugh.ar")

	/// 􀴯 `laugh.he`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `haha`
	static public let laugh_he = PrivateSFSymbol(identifier: "laugh.he")

	/// 􀴰 `laugh.th`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `haha`
	static public let laugh_th = PrivateSFSymbol(identifier: "laugh.th")

	/// 􀴱 `laugh.ja`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `haha`
	static public let laugh_ja = PrivateSFSymbol(identifier: "laugh.ja")

	/// 􀵁 `laugh.ko`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `haha`
	static public let laugh_ko = PrivateSFSymbol(identifier: "laugh.ko")

	/// 􀵂 `laugh.zh`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `haha`
	static public let laugh_zh = PrivateSFSymbol(identifier: "laugh.zh")

	/// 􀵃 `laugh.hi`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `haha`
	static public let laugh_hi = PrivateSFSymbol(identifier: "laugh.hi")

	/// 􁃣 `question`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `?`
	static public let question = PrivateSFSymbol(identifier: "question")

	/// 􁃼 `question.ar`
	///
	/// - categories:
	///   - `communication`
	static public let question_ar = PrivateSFSymbol(identifier: "question.ar")

	/// 􁃤 `emphasize`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `!`
	static public let emphasize = PrivateSFSymbol(identifier: "emphasize")

	/// 􁃝 `bubble.tapback`
	///
	/// - categories:
	///   - `communication`
	static public let bubble_tapback = PrivateSFSymbol(identifier: "bubble.tapback")

	/// 􁃞 `bubble.tapback.fill`
	///
	/// - categories:
	///   - `communication`
	static public let bubble_tapback_fill = PrivateSFSymbol(identifier: "bubble.tapback.fill")

	/// 􁃶 `plus.bubble.tapback`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `+`
	///   - `add`
	static public let plus_bubble_tapback = PrivateSFSymbol(identifier: "plus.bubble.tapback")

	/// 􁃷 `plus.bubble.tapback.fill`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `+`
	///   - `add`
	static public let plus_bubble_tapback_fill = PrivateSFSymbol(identifier: "plus.bubble.tapback.fill")

	/// 􁃡 `heart.bubble.tapback`
	///
	/// - categories:
	///   - `communication`
	static public let heart_bubble_tapback = PrivateSFSymbol(identifier: "heart.bubble.tapback")

	/// 􁃢 `heart.bubble.tapback.fill`
	///
	/// - categories:
	///   - `communication`
	static public let heart_bubble_tapback_fill = PrivateSFSymbol(identifier: "heart.bubble.tapback.fill")

	/// 􁃟 `hand.thumbsup.bubble.tapback`
	///
	/// - categories:
	///   - `communication`
	static public let hand_thumbsup_bubble_tapback = PrivateSFSymbol(identifier: "hand.thumbsup.bubble.tapback")

	/// 􁃠 `hand.thumbsup.bubble.tapback.fill`
	///
	/// - categories:
	///   - `communication`
	static public let hand_thumbsup_bubble_tapback_fill = PrivateSFSymbol(identifier: "hand.thumbsup.bubble.tapback.fill")

	/// 􁃴 `hand.thumbsdown.bubble.tapback`
	///
	/// - categories:
	///   - `communication`
	static public let hand_thumbsdown_bubble_tapback = PrivateSFSymbol(identifier: "hand.thumbsdown.bubble.tapback")

	/// 􁃵 `hand.thumbsdown.bubble.tapback.fill`
	///
	/// - categories:
	///   - `communication`
	static public let hand_thumbsdown_bubble_tapback_fill = PrivateSFSymbol(identifier: "hand.thumbsdown.bubble.tapback.fill")

	/// 􁃦 `laugh.bubble.tapback`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback = PrivateSFSymbol(identifier: "laugh.bubble.tapback")

	/// 􁃧 `laugh.bubble.tapback.fill`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_fill = PrivateSFSymbol(identifier: "laugh.bubble.tapback.fill")

	/// 􁆀 `laugh.bubble.tapback.es`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_es = PrivateSFSymbol(identifier: "laugh.bubble.tapback.es")

	/// 􁆁 `laugh.bubble.tapback.fill.es`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_fill_es = PrivateSFSymbol(identifier: "laugh.bubble.tapback.fill.es")

	/// 􁆂 `laugh.bubble.tapback.el`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_el = PrivateSFSymbol(identifier: "laugh.bubble.tapback.el")

	/// 􁆃 `laugh.bubble.tapback.fill.el`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_fill_el = PrivateSFSymbol(identifier: "laugh.bubble.tapback.fill.el")

	/// 􁆄 `laugh.bubble.tapback.ru`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_ru = PrivateSFSymbol(identifier: "laugh.bubble.tapback.ru")

	/// 􁆅 `laugh.bubble.tapback.fill.ru`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_fill_ru = PrivateSFSymbol(identifier: "laugh.bubble.tapback.fill.ru")

	/// 􁆆 `laugh.bubble.tapback.it`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_it = PrivateSFSymbol(identifier: "laugh.bubble.tapback.it")

	/// 􁆇 `laugh.bubble.tapback.fill.it`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_fill_it = PrivateSFSymbol(identifier: "laugh.bubble.tapback.fill.it")

	/// 􁆈 `laugh.bubble.tapback.ar`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_ar = PrivateSFSymbol(identifier: "laugh.bubble.tapback.ar")

	/// 􁆉 `laugh.bubble.tapback.fill.ar`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_fill_ar = PrivateSFSymbol(identifier: "laugh.bubble.tapback.fill.ar")

	/// 􁆊 `laugh.bubble.tapback.he`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_he = PrivateSFSymbol(identifier: "laugh.bubble.tapback.he")

	/// 􁆋 `laugh.bubble.tapback.fill.he`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_fill_he = PrivateSFSymbol(identifier: "laugh.bubble.tapback.fill.he")

	/// 􁆌 `laugh.bubble.tapback.th`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_th = PrivateSFSymbol(identifier: "laugh.bubble.tapback.th")

	/// 􁆍 `laugh.bubble.tapback.fill.th`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_fill_th = PrivateSFSymbol(identifier: "laugh.bubble.tapback.fill.th")

	/// 􁆎 `laugh.bubble.tapback.ja`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_ja = PrivateSFSymbol(identifier: "laugh.bubble.tapback.ja")

	/// 􁆏 `laugh.bubble.tapback.fill.ja`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_fill_ja = PrivateSFSymbol(identifier: "laugh.bubble.tapback.fill.ja")

	/// 􁆐 `laugh.bubble.tapback.ko`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_ko = PrivateSFSymbol(identifier: "laugh.bubble.tapback.ko")

	/// 􁆑 `laugh.bubble.tapback.fill.ko`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_fill_ko = PrivateSFSymbol(identifier: "laugh.bubble.tapback.fill.ko")

	/// 􁆒 `laugh.bubble.tapback.zh`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_zh = PrivateSFSymbol(identifier: "laugh.bubble.tapback.zh")

	/// 􁆓 `laugh.bubble.tapback.fill.zh`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_fill_zh = PrivateSFSymbol(identifier: "laugh.bubble.tapback.fill.zh")

	/// 􁆔 `laugh.bubble.tapback.hi`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_hi = PrivateSFSymbol(identifier: "laugh.bubble.tapback.hi")

	/// 􁆕 `laugh.bubble.tapback.fill.hi`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_fill_hi = PrivateSFSymbol(identifier: "laugh.bubble.tapback.fill.hi")

	/// 􁃬 `question.bubble.tapback`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `?`
	static public let question_bubble_tapback = PrivateSFSymbol(identifier: "question.bubble.tapback")

	/// 􁃭 `question.bubble.tapback.fill`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `?`
	static public let question_bubble_tapback_fill = PrivateSFSymbol(identifier: "question.bubble.tapback.fill")

	/// 􁃽 `question.bubble.tapback.ar`
	///
	/// - categories:
	///   - `communication`
	static public let question_bubble_tapback_ar = PrivateSFSymbol(identifier: "question.bubble.tapback.ar")

	/// 􁃾 `question.bubble.tapback.fill.ar`
	///
	/// - categories:
	///   - `communication`
	static public let question_bubble_tapback_fill_ar = PrivateSFSymbol(identifier: "question.bubble.tapback.fill.ar")

	/// 􁃮 `emphasize.bubble.tapback`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `!`
	static public let emphasize_bubble_tapback = PrivateSFSymbol(identifier: "emphasize.bubble.tapback")

	/// 􁃯 `emphasize.bubble.tapback.fill`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `!`
	static public let emphasize_bubble_tapback_fill = PrivateSFSymbol(identifier: "emphasize.bubble.tapback.fill")

	/// 􁄁 `emphasize.bubble.tapback.rtl`
	///
	/// - categories:
	///   - `communication`
	static public let emphasize_bubble_tapback_rtl = PrivateSFSymbol(identifier: "emphasize.bubble.tapback.rtl")

	/// 􁄂 `emphasize.bubble.tapback.fill.rtl`
	///
	/// - categories:
	///   - `communication`
	static public let emphasize_bubble_tapback_fill_rtl = PrivateSFSymbol(identifier: "emphasize.bubble.tapback.fill.rtl")

	/// 􁄃 `bubble.tapback.2`
	///
	/// - categories:
	///   - `communication`
	static public let bubble_tapback_2 = PrivateSFSymbol(identifier: "bubble.tapback.2")

	/// 􁄄 `bubble.tapback.2.fill`
	///
	/// - categories:
	///   - `communication`
	static public let bubble_tapback_2_fill = PrivateSFSymbol(identifier: "bubble.tapback.2.fill")

	/// 􁄅 `heart.bubble.tapback.2`
	///
	/// - categories:
	///   - `communication`
	static public let heart_bubble_tapback_2 = PrivateSFSymbol(identifier: "heart.bubble.tapback.2")

	/// 􁄆 `heart.bubble.tapback.2.fill`
	///
	/// - categories:
	///   - `communication`
	static public let heart_bubble_tapback_2_fill = PrivateSFSymbol(identifier: "heart.bubble.tapback.2.fill")

	/// 􁄉 `hand.thumbsup.bubble.tapback.2`
	///
	/// - categories:
	///   - `communication`
	static public let hand_thumbsup_bubble_tapback_2 = PrivateSFSymbol(identifier: "hand.thumbsup.bubble.tapback.2")

	/// 􁄊 `hand.thumbsup.bubble.tapback.2.fill`
	///
	/// - categories:
	///   - `communication`
	static public let hand_thumbsup_bubble_tapback_2_fill = PrivateSFSymbol(identifier: "hand.thumbsup.bubble.tapback.2.fill")

	/// 􁄋 `hand.thumbsdown.bubble.tapback.2`
	///
	/// - categories:
	///   - `communication`
	static public let hand_thumbsdown_bubble_tapback_2 = PrivateSFSymbol(identifier: "hand.thumbsdown.bubble.tapback.2")

	/// 􁄌 `hand.thumbsdown.bubble.tapback.2.fill`
	///
	/// - categories:
	///   - `communication`
	static public let hand_thumbsdown_bubble_tapback_2_fill = PrivateSFSymbol(identifier: "hand.thumbsdown.bubble.tapback.2.fill")

	/// 􁄑 `laugh.bubble.tapback.2`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2 = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2")

	/// 􁄒 `laugh.bubble.tapback.2.fill`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2_fill = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2.fill")

	/// 􁆖 `laugh.bubble.tapback.2.es`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2_es = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2.es")

	/// 􁆗 `laugh.bubble.tapback.2.fill.es`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2_fill_es = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2.fill.es")

	/// 􁆘 `laugh.bubble.tapback.2.el`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2_el = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2.el")

	/// 􁆙 `laugh.bubble.tapback.2.fill.el`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2_fill_el = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2.fill.el")

	/// 􁆚 `laugh.bubble.tapback.2.ru`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2_ru = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2.ru")

	/// 􁆛 `laugh.bubble.tapback.2.fill.ru`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2_fill_ru = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2.fill.ru")

	/// 􁆜 `laugh.bubble.tapback.2.it`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2_it = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2.it")

	/// 􁆝 `laugh.bubble.tapback.2.fill.it`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2_fill_it = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2.fill.it")

	/// 􁆞 `laugh.bubble.tapback.2.ar`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2_ar = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2.ar")

	/// 􁆟 `laugh.bubble.tapback.2.fill.ar`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2_fill_ar = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2.fill.ar")

	/// 􁆠 `laugh.bubble.tapback.2.he`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2_he = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2.he")

	/// 􁆡 `laugh.bubble.tapback.2.fill.he`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2_fill_he = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2.fill.he")

	/// 􁆢 `laugh.bubble.tapback.2.th`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2_th = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2.th")

	/// 􁆣 `laugh.bubble.tapback.2.fill.th`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2_fill_th = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2.fill.th")

	/// 􁆤 `laugh.bubble.tapback.2.ja`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2_ja = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2.ja")

	/// 􁆥 `laugh.bubble.tapback.2.fill.ja`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2_fill_ja = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2.fill.ja")

	/// 􁆦 `laugh.bubble.tapback.2.ko`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2_ko = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2.ko")

	/// 􁆧 `laugh.bubble.tapback.2.fill.ko`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2_fill_ko = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2.fill.ko")

	/// 􁆨 `laugh.bubble.tapback.2.zh`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2_zh = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2.zh")

	/// 􁆩 `laugh.bubble.tapback.2.fill.zh`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2_fill_zh = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2.fill.zh")

	/// 􁆪 `laugh.bubble.tapback.2.hi`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2_hi = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2.hi")

	/// 􁆫 `laugh.bubble.tapback.2.fill.hi`
	///
	/// - categories:
	///   - `communication`
	static public let laugh_bubble_tapback_2_fill_hi = PrivateSFSymbol(identifier: "laugh.bubble.tapback.2.fill.hi")

	/// 􁄓 `question.bubble.tapback.2`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `?`
	static public let question_bubble_tapback_2 = PrivateSFSymbol(identifier: "question.bubble.tapback.2")

	/// 􁄔 `question.bubble.tapback.2.fill`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `?`
	static public let question_bubble_tapback_2_fill = PrivateSFSymbol(identifier: "question.bubble.tapback.2.fill")

	/// 􁄕 `question.bubble.tapback.2.ar`
	///
	/// - categories:
	///   - `communication`
	static public let question_bubble_tapback_2_ar = PrivateSFSymbol(identifier: "question.bubble.tapback.2.ar")

	/// 􁄖 `question.bubble.tapback.2.fill.ar`
	///
	/// - categories:
	///   - `communication`
	static public let question_bubble_tapback_2_fill_ar = PrivateSFSymbol(identifier: "question.bubble.tapback.2.fill.ar")

	/// 􁄙 `emphasize.bubble.tapback.2`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `!`
	static public let emphasize_bubble_tapback_2 = PrivateSFSymbol(identifier: "emphasize.bubble.tapback.2")

	/// 􁄚 `emphasize.bubble.tapback.2.fill`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `!`
	static public let emphasize_bubble_tapback_2_fill = PrivateSFSymbol(identifier: "emphasize.bubble.tapback.2.fill")

	/// 􁄛 `emphasize.bubble.tapback.2.rtl`
	///
	/// - categories:
	///   - `communication`
	static public let emphasize_bubble_tapback_2_rtl = PrivateSFSymbol(identifier: "emphasize.bubble.tapback.2.rtl")

	/// 􁄜 `emphasize.bubble.tapback.2.fill.rtl`
	///
	/// - categories:
	///   - `communication`
	static public let emphasize_bubble_tapback_2_fill_rtl = PrivateSFSymbol(identifier: "emphasize.bubble.tapback.2.fill.rtl")

	/// 􁇟 `cinematic.video`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `facetime`
	static public let cinematic_video = PrivateSFSymbol(identifier: "cinematic.video")

	/// 􁇠 `cinematic.video.fill`
	///
	/// - categories:
	///   - `communication`
	///
	/// - search keywords:
	///   - `facetime`
	static public let cinematic_video_fill = PrivateSFSymbol(identifier: "cinematic.video.fill")

	/// 􀫛 `siri`
	///
	/// - categories:
	///   - `accessibility`
	///   - `multicolor`
	///
	/// - search keywords:
	///   - `siri`
	static public let siri = PrivateSFSymbol(identifier: "siri")

	/// 􁀙 `apple.haptics`
	static public let apple_haptics = PrivateSFSymbol(identifier: "apple.haptics")

	/// 􁇫 `apple.homekey`
	///
	/// - categories:
	///   - `privacyandsecurity`
	///   - `variablecolor`
	///
	/// - search keywords:
	///   - `homekit`
	static public let apple_homekey = PrivateSFSymbol(identifier: "apple.homekey")

	/// 􁇬 `apple.homekey.fill`
	///
	/// - categories:
	///   - `multicolor`
	///   - `privacyandsecurity`
	///   - `variablecolor`
	///
	/// - search keywords:
	///   - `homekit`
	static public let apple_homekey_fill = PrivateSFSymbol(identifier: "apple.homekey.fill")

	/// 􁇀 `wallet.circle`
	///
	/// - categories:
	///   - `commerce`
	static public let wallet_circle = PrivateSFSymbol(identifier: "wallet.circle")

	/// 􁇁 `wallet.circle.fill`
	///
	/// - categories:
	///   - `commerce`
	///   - `multicolor`
	static public let wallet_circle_fill = PrivateSFSymbol(identifier: "wallet.circle.fill")

	/// 􁁓 `buildings.3d`
	static public let buildings_3d = PrivateSFSymbol(identifier: "buildings.3d")

	/// 􀴘 `pin.point.of.interest`
	///
	/// - categories:
	///   - `maps`
	static public let pin_point_of_interest = PrivateSFSymbol(identifier: "pin.point.of.interest")

	/// 􁄮 `pin.point.of.interest.fill`
	///
	/// - categories:
	///   - `maps`
	///   - `multicolor`
	static public let pin_point_of_interest_fill = PrivateSFSymbol(identifier: "pin.point.of.interest.fill")

	/// 􀴙 `pin.point.of.interest.badge.plus`
	///
	/// - categories:
	///   - `maps`
	///   - `multicolor`
	///
	/// - search keywords:
	///   - `+`
	///   - `add`
	static public let pin_point_of_interest_badge_plus = PrivateSFSymbol(identifier: "pin.point.of.interest.badge.plus")

	/// 􁄯 `pin.point.of.interest.badge.plus.fill`
	///
	/// - categories:
	///   - `maps`
	///   - `multicolor`
	///
	/// - search keywords:
	///   - `+`
	///   - `add`
	static public let pin_point_of_interest_badge_plus_fill = PrivateSFSymbol(identifier: "pin.point.of.interest.badge.plus.fill")

	/// 􁂳 `pin.point.of.interest.2.fill`
	///
	/// - categories:
	///   - `maps`
	///   - `multicolor`
	static public let pin_point_of_interest_2_fill = PrivateSFSymbol(identifier: "pin.point.of.interest.2.fill")

	/// 􁂴 `pin.point.of.interest.circle`
	///
	/// - categories:
	///   - `maps`
	static public let pin_point_of_interest_circle = PrivateSFSymbol(identifier: "pin.point.of.interest.circle")

	/// 􁂵 `pin.point.of.interest.circle.fill`
	///
	/// - categories:
	///   - `maps`
	///   - `multicolor`
	static public let pin_point_of_interest_circle_fill = PrivateSFSymbol(identifier: "pin.point.of.interest.circle.fill")

	/// 􁅣 `location.pin.point.of.interest`
	///
	/// - categories:
	///   - `maps`
	static public let location_pin_point_of_interest = PrivateSFSymbol(identifier: "location.pin.point.of.interest")

	/// 􁅤 `location.pin.point.of.interest.fill`
	///
	/// - categories:
	///   - `maps`
	static public let location_pin_point_of_interest_fill = PrivateSFSymbol(identifier: "location.pin.point.of.interest.fill")

	/// 􀹄 `apple.silicon`
	///
	/// - search keywords:
	///   - `chip`
	///   - `cpu`
	///   - `gpu`
	static public let apple_silicon = PrivateSFSymbol(identifier: "apple.silicon")

	/// 􀹅 `apple.silicon.fill`
	///
	/// - categories:
	///   - `multicolor`
	///
	/// - search keywords:
	///   - `chip`
	///   - `cpu`
	///   - `gpu`
	static public let apple_silicon_fill = PrivateSFSymbol(identifier: "apple.silicon.fill")

	/// 􀺚 `sensor.applewatch.case`
	///
	/// - categories:
	///   - `devices`
	static public let sensor_applewatch_case = PrivateSFSymbol(identifier: "sensor.applewatch.case")

	/// 􀺛 `sensor.applewatch.case.fill`
	///
	/// - categories:
	///   - `devices`
	static public let sensor_applewatch_case_fill = PrivateSFSymbol(identifier: "sensor.applewatch.case.fill")

	/// 􀺖 `watchdock.applewatch.case`
	///
	/// - categories:
	///   - `devices`
	static public let watchdock_applewatch_case = PrivateSFSymbol(identifier: "watchdock.applewatch.case")

	/// 􀼤 `watchdock.fill`
	///
	/// - categories:
	///   - `devices`
	///   - `multicolor`
	static public let watchdock_fill = PrivateSFSymbol(identifier: "watchdock.fill")

	/// 􀼥 `watchdock.circle`
	///
	/// - categories:
	///   - `devices`
	///   - `multicolor`
	static public let watchdock_circle = PrivateSFSymbol(identifier: "watchdock.circle")

	/// 􀼦 `watchdock.circle.fill`
	///
	/// - categories:
	///   - `devices`
	///   - `multicolor`
	static public let watchdock_circle_fill = PrivateSFSymbol(identifier: "watchdock.circle.fill")

	/// 􀺜 `walkietalkie.applewatch.case`
	///
	/// - categories:
	///   - `devices`
	static public let walkietalkie_applewatch_case = PrivateSFSymbol(identifier: "walkietalkie.applewatch.case")

	/// 􀺝 `walkietalkie.applewatch.case.fill`
	///
	/// - categories:
	///   - `devices`
	static public let walkietalkie_applewatch_case_fill = PrivateSFSymbol(identifier: "walkietalkie.applewatch.case.fill")

	/// 􀺞 `walkietalkie.applewatch.case.circle`
	///
	/// - categories:
	///   - `devices`
	static public let walkietalkie_applewatch_case_circle = PrivateSFSymbol(identifier: "walkietalkie.applewatch.case.circle")

	/// 􀺟 `walkietalkie.applewatch.case.circle.fill`
	///
	/// - categories:
	///   - `devices`
	///   - `multicolor`
	static public let walkietalkie_applewatch_case_circle_fill = PrivateSFSymbol(identifier: "walkietalkie.applewatch.case.circle.fill")

	/// 􀺫 `walkietalkie.applewatch.case.radiowaves.left.and.right`
	///
	/// - categories:
	///   - `devices`
	///   - `variablecolor`
	static public let walkietalkie_applewatch_case_radiowaves_left_and_right = PrivateSFSymbol(identifier: "walkietalkie.applewatch.case.radiowaves.left.and.right")

	/// 􀺬 `walkietalkie.applewatch.case.fill.radiowaves.left.and.right`
	///
	/// - categories:
	///   - `devices`
	///   - `variablecolor`
	static public let walkietalkie_applewatch_case_fill_radiowaves_left_and_right = PrivateSFSymbol(identifier: "walkietalkie.applewatch.case.fill.radiowaves.left.and.right")

	/// 􀸴 `activity.sharing`
	///
	/// - categories:
	///   - `fitness`
	///
	/// - search keywords:
	///   - `fitness`
	static public let activity_sharing = PrivateSFSymbol(identifier: "activity.sharing")

	/// 􀼊 `apple.mindfulness`
	///
	/// - categories:
	///   - `health`
	///   - `multicolor`
	static public let apple_mindfulness = PrivateSFSymbol(identifier: "apple.mindfulness")

	/// 􁅘 `apple.mindfulness.circle`
	///
	/// - categories:
	///   - `health`
	///   - `multicolor`
	static public let apple_mindfulness_circle = PrivateSFSymbol(identifier: "apple.mindfulness.circle")

	/// 􁅙 `apple.mindfulness.circle.fill`
	///
	/// - categories:
	///   - `health`
	///   - `multicolor`
	static public let apple_mindfulness_circle_fill = PrivateSFSymbol(identifier: "apple.mindfulness.circle.fill")

	/// 􁂗 `apple.breathe`
	///
	/// - categories:
	///   - `health`
	///   - `variablecolor`
	static public let apple_breathe = PrivateSFSymbol(identifier: "apple.breathe")

	/// 􁂘 `apple.reflect`
	///
	/// - categories:
	///   - `health`
	static public let apple_reflect = PrivateSFSymbol(identifier: "apple.reflect")

	/// 􀦝 `apple.cycletracking`
	///
	/// - categories:
	///   - `health`
	///   - `multicolor`
	///   - `variablecolor`
	///
	/// - search keywords:
	///   - `medical`
	static public let apple_cycletracking = PrivateSFSymbol(identifier: "apple.cycletracking")

	/// 􀼈 `apple.slice`
	///
	/// - categories:
	///   - `health`
	///   - `multicolor`
	///   - `nature`
	///
	/// - search keywords:
	///   - `fruit`
	///   - `medical`
	static public let apple_slice = PrivateSFSymbol(identifier: "apple.slice")

	/// 􀼉 `apple.slice.fill`
	///
	/// - categories:
	///   - `health`
	///   - `multicolor`
	///   - `nature`
	///
	/// - search keywords:
	///   - `fruit`
	///   - `medical`
	static public let apple_slice_fill = PrivateSFSymbol(identifier: "apple.slice.fill")

	/// 􀠫 `capsule.cross`
	///
	/// - categories:
	///   - `health`
	///   - `multicolor`
	///
	/// - search keywords:
	///   - `medical`
	static public let capsule_cross = PrivateSFSymbol(identifier: "capsule.cross")

	/// 􀠬 `capsule.cross.fill`
	///
	/// - categories:
	///   - `health`
	///   - `multicolor`
	///
	/// - search keywords:
	///   - `medical`
	static public let capsule_cross_fill = PrivateSFSymbol(identifier: "capsule.cross.fill")

	/// 􀜬 `emoji.face.grinning`
	///
	/// - categories:
	///   - `human`
	///
	/// - search keywords:
	///   - `smile`
	static public let emoji_face_grinning = PrivateSFSymbol(identifier: "emoji.face.grinning")

	/// 􀜭 `emoji.face.grinning.inverse`
	///
	/// - categories:
	///   - `human`
	///
	/// - search keywords:
	///   - `smile`
	static public let emoji_face_grinning_inverse = PrivateSFSymbol(identifier: "emoji.face.grinning.inverse")

	/// 􀵤 `ear.and.zzz`
	///
	/// - categories:
	///   - `accessibility`
	///   - `health`
	///   - `human`
	///
	/// - search keywords:
	///   - `zzz`
	static public let ear_and_zzz = PrivateSFSymbol(identifier: "ear.and.zzz")

	/// 􁄰 `macwindow.resize`
	static public let macwindow_resize = PrivateSFSymbol(identifier: "macwindow.resize")

	/// 􁄱 `macwindow.resize.lock`
	///
	/// - search keywords:
	///   - `padlock`
	static public let macwindow_resize_lock = PrivateSFSymbol(identifier: "macwindow.resize.lock")

	/// 􁅉 `tabbar.top.rectangle`
	static public let tabbar_top_rectangle = PrivateSFSymbol(identifier: "tabbar.top.rectangle")

	/// 􀻝 `apple.mobility`
	///
	/// - categories:
	///   - `health`
	///   - `multicolor`
	///
	/// - search keywords:
	///   - `medical`
	static public let apple_mobility = PrivateSFSymbol(identifier: "apple.mobility")

	/// 􀣒 `buildingblock`
	///
	/// - categories:
	///   - `objectsandtools`
	static public let buildingblock = PrivateSFSymbol(identifier: "buildingblock")

	/// 􀣓 `buildingblock.fill`
	///
	/// - categories:
	///   - `objectsandtools`
	static public let buildingblock_fill = PrivateSFSymbol(identifier: "buildingblock.fill")

	/// 􁂦 `stopwatch.hybrid`
	///
	/// - categories:
	///   - `objectsandtools`
	static public let stopwatch_hybrid = PrivateSFSymbol(identifier: "stopwatch.hybrid")

	/// 􁂧 `stopwatch.digital`
	///
	/// - categories:
	///   - `objectsandtools`
	///   - `time`
	static public let stopwatch_digital = PrivateSFSymbol(identifier: "stopwatch.digital")

	/// 􁂽 `stopwatch.digital.ar`
	///
	/// - categories:
	///   - `objectsandtools`
	///   - `time`
	static public let stopwatch_digital_ar = PrivateSFSymbol(identifier: "stopwatch.digital.ar")

	/// 􁇭 `rocket.circle`
	///
	/// - categories:
	///   - `transportation`
	static public let rocket_circle = PrivateSFSymbol(identifier: "rocket.circle")

	/// 􁇮 `rocket.circle.fill`
	///
	/// - categories:
	///   - `multicolor`
	///   - `transportation`
	static public let rocket_circle_fill = PrivateSFSymbol(identifier: "rocket.circle.fill")

	/// 􀬘 `battery.powerplug`
	///
	/// - categories:
	///   - `multicolor`
	///   - `objectsandtools`
	static public let battery_powerplug = PrivateSFSymbol(identifier: "battery.powerplug")

	/// 􀷅 `port.usb.c`
	///
	/// - categories:
	///   - `connectivity`
	static public let port_usb_c = PrivateSFSymbol(identifier: "port.usb.c")

	/// 􀠭 `sensorkit`
	static public let sensorkit = PrivateSFSymbol(identifier: "sensorkit")

	/// 􁇶 `emoji.face.smiling.with.smiling.eyes`
	static public let emoji_face_smiling_with_smiling_eyes = PrivateSFSymbol(identifier: "emoji.face.smiling.with.smiling.eyes")

	/// 􁇷 `emoji.face.smiling.with.smiling.eyes.inverse`
	static public let emoji_face_smiling_with_smiling_eyes_inverse = PrivateSFSymbol(identifier: "emoji.face.smiling.with.smiling.eyes.inverse")

	/// 􁇸 `emoji.face.grinning.with.squinting.eyes`
	static public let emoji_face_grinning_with_squinting_eyes = PrivateSFSymbol(identifier: "emoji.face.grinning.with.squinting.eyes")

	/// 􁈗 `emoji.face.grinning.with.squinting.eyes.inverse`
	static public let emoji_face_grinning_with_squinting_eyes_inverse = PrivateSFSymbol(identifier: "emoji.face.grinning.with.squinting.eyes.inverse")

	/// 􁇺 `emoji.face.with.tears.of.joy`
	static public let emoji_face_with_tears_of_joy = PrivateSFSymbol(identifier: "emoji.face.with.tears.of.joy")

	/// 􁇻 `emoji.face.with.tears.of.joy.inverse`
	static public let emoji_face_with_tears_of_joy_inverse = PrivateSFSymbol(identifier: "emoji.face.with.tears.of.joy.inverse")

	/// 􁇼 `emoji.face.rolling.on.the.floor.laughing`
	static public let emoji_face_rolling_on_the_floor_laughing = PrivateSFSymbol(identifier: "emoji.face.rolling.on.the.floor.laughing")

	/// 􁈘 `emoji.face.rolling.on.the.floor.laughing.inverse`
	static public let emoji_face_rolling_on_the_floor_laughing_inverse = PrivateSFSymbol(identifier: "emoji.face.rolling.on.the.floor.laughing.inverse")

	/// 􀹇 `emoji.face.winking.with.stuck.out.tongue`
	static public let emoji_face_winking_with_stuck_out_tongue = PrivateSFSymbol(identifier: "emoji.face.winking.with.stuck.out.tongue")

	/// 􁅩 `emoji.face.winking.with.stuck.out.tongue.inverse`
	static public let emoji_face_winking_with_stuck_out_tongue_inverse = PrivateSFSymbol(identifier: "emoji.face.winking.with.stuck.out.tongue.inverse")

	/// 􀹈 `emoji.face.grimacing`
	static public let emoji_face_grimacing = PrivateSFSymbol(identifier: "emoji.face.grimacing")

	/// 􁅪 `emoji.face.grimacing.inverse`
	static public let emoji_face_grimacing_inverse = PrivateSFSymbol(identifier: "emoji.face.grimacing.inverse")

	/// 􁇾 `emoji.face.smiling.with.heart.eyes`
	static public let emoji_face_smiling_with_heart_eyes = PrivateSFSymbol(identifier: "emoji.face.smiling.with.heart.eyes")

	/// 􁇿 `emoji.face.smiling.with.heart.eyes.inverse`
	static public let emoji_face_smiling_with_heart_eyes_inverse = PrivateSFSymbol(identifier: "emoji.face.smiling.with.heart.eyes.inverse")

	/// 􀹉 `emoji.face.blowing.a.kiss`
	static public let emoji_face_blowing_a_kiss = PrivateSFSymbol(identifier: "emoji.face.blowing.a.kiss")

	/// 􁅫 `emoji.face.blowing.a.kiss.inverse`
	static public let emoji_face_blowing_a_kiss_inverse = PrivateSFSymbol(identifier: "emoji.face.blowing.a.kiss.inverse")

	/// 􁈀 `emoji.face.smiling.with.hearts`
	static public let emoji_face_smiling_with_hearts = PrivateSFSymbol(identifier: "emoji.face.smiling.with.hearts")

	/// 􁈁 `emoji.face.smiling.with.hearts.inverse`
	static public let emoji_face_smiling_with_hearts_inverse = PrivateSFSymbol(identifier: "emoji.face.smiling.with.hearts.inverse")

	/// 􁈂 `emoji.face.smiling.with.sunglasses`
	static public let emoji_face_smiling_with_sunglasses = PrivateSFSymbol(identifier: "emoji.face.smiling.with.sunglasses")

	/// 􁈃 `emoji.face.smiling.with.sunglasses.inverse`
	static public let emoji_face_smiling_with_sunglasses_inverse = PrivateSFSymbol(identifier: "emoji.face.smiling.with.sunglasses.inverse")

	/// 􁈄 `emoji.face.with.starry.eyes`
	static public let emoji_face_with_starry_eyes = PrivateSFSymbol(identifier: "emoji.face.with.starry.eyes")

	/// 􁈅 `emoji.face.with.starry.eyes.inverse`
	static public let emoji_face_with_starry_eyes_inverse = PrivateSFSymbol(identifier: "emoji.face.with.starry.eyes.inverse")

	/// 􀹊 `emoji.thumbsup`
	static public let emoji_thumbsup = PrivateSFSymbol(identifier: "emoji.thumbsup")

	/// 􁅬 `emoji.thumbsup.fill`
	static public let emoji_thumbsup_fill = PrivateSFSymbol(identifier: "emoji.thumbsup.fill")

	/// 􀹋 `emoji.peace.hand.sign`
	static public let emoji_peace_hand_sign = PrivateSFSymbol(identifier: "emoji.peace.hand.sign")

	/// 􁅭 `emoji.peace.hand.sign.fill`
	static public let emoji_peace_hand_sign_fill = PrivateSFSymbol(identifier: "emoji.peace.hand.sign.fill")

	/// 􀹌 `emoji.love.you.gesture`
	static public let emoji_love_you_gesture = PrivateSFSymbol(identifier: "emoji.love.you.gesture")

	/// 􁅮 `emoji.love.you.gesture.fill`
	static public let emoji_love_you_gesture_fill = PrivateSFSymbol(identifier: "emoji.love.you.gesture.fill")

	/// 􀹍 `emoji.closed.fist`
	static public let emoji_closed_fist = PrivateSFSymbol(identifier: "emoji.closed.fist")

	/// 􁅯 `emoji.closed.fist.fill`
	static public let emoji_closed_fist_fill = PrivateSFSymbol(identifier: "emoji.closed.fist.fill")

	/// 􁆯 `emoji.heart`
	static public let emoji_heart = PrivateSFSymbol(identifier: "emoji.heart")

	/// 􀹎 `emoji.heart.fill`
	static public let emoji_heart_fill = PrivateSFSymbol(identifier: "emoji.heart.fill")

	/// 􁈖 `emoji.hearts.2`
	static public let emoji_hearts_2 = PrivateSFSymbol(identifier: "emoji.hearts.2")

	/// 􁈊 `emoji.hearts.2.fill`
	static public let emoji_hearts_2_fill = PrivateSFSymbol(identifier: "emoji.hearts.2.fill")

	/// 􁆰 `emoji.star`
	static public let emoji_star = PrivateSFSymbol(identifier: "emoji.star")

	/// 􀹏 `emoji.star.fill`
	static public let emoji_star_fill = PrivateSFSymbol(identifier: "emoji.star.fill")

	/// 􁈋 `emoji.sparkles`
	static public let emoji_sparkles = PrivateSFSymbol(identifier: "emoji.sparkles")

	/// 􀹐 `emoji.alien.monster`
	static public let emoji_alien_monster = PrivateSFSymbol(identifier: "emoji.alien.monster")

	/// 􁅰 `emoji.alien.monster.inverse`
	static public let emoji_alien_monster_inverse = PrivateSFSymbol(identifier: "emoji.alien.monster.inverse")

	/// 􀹑 `emoji.unicorn`
	static public let emoji_unicorn = PrivateSFSymbol(identifier: "emoji.unicorn")

	/// 􁅱 `emoji.unicorn.inverse`
	static public let emoji_unicorn_inverse = PrivateSFSymbol(identifier: "emoji.unicorn.inverse")

	/// 􀹒 `emoji.ghost`
	static public let emoji_ghost = PrivateSFSymbol(identifier: "emoji.ghost")

	/// 􁅲 `emoji.ghost.inverse`
	static public let emoji_ghost_inverse = PrivateSFSymbol(identifier: "emoji.ghost.inverse")

	/// 􀹓 `emoji.robot.face`
	static public let emoji_robot_face = PrivateSFSymbol(identifier: "emoji.robot.face")

	/// 􁅳 `emoji.robot.face.inverse`
	static public let emoji_robot_face_inverse = PrivateSFSymbol(identifier: "emoji.robot.face.inverse")

	/// 􀹔 `emoji.bear.face`
	static public let emoji_bear_face = PrivateSFSymbol(identifier: "emoji.bear.face")

	/// 􁅴 `emoji.bear.face.inverse`
	static public let emoji_bear_face_inverse = PrivateSFSymbol(identifier: "emoji.bear.face.inverse")

	/// 􀹕 `emoji.cat.face`
	static public let emoji_cat_face = PrivateSFSymbol(identifier: "emoji.cat.face")

	/// 􁁡 `emoji.cat.face.inverse`
	static public let emoji_cat_face_inverse = PrivateSFSymbol(identifier: "emoji.cat.face.inverse")

	/// 􀹖 `emoji.alien`
	static public let emoji_alien = PrivateSFSymbol(identifier: "emoji.alien")

	/// 􁅵 `emoji.alien.inverse`
	static public let emoji_alien_inverse = PrivateSFSymbol(identifier: "emoji.alien.inverse")

	/// 􀹗 `emoji.skull`
	static public let emoji_skull = PrivateSFSymbol(identifier: "emoji.skull")

	/// 􁅶 `emoji.skull.inverse`
	static public let emoji_skull_inverse = PrivateSFSymbol(identifier: "emoji.skull.inverse")

	/// 􀹘 `emoji.tiger.face`
	static public let emoji_tiger_face = PrivateSFSymbol(identifier: "emoji.tiger.face")

	/// 􁅷 `emoji.tiger.face.inverse`
	static public let emoji_tiger_face_inverse = PrivateSFSymbol(identifier: "emoji.tiger.face.inverse")

	/// 􀹙 `emoji.dragon.face`
	static public let emoji_dragon_face = PrivateSFSymbol(identifier: "emoji.dragon.face")

	/// 􁅸 `emoji.dragon.face.inverse`
	static public let emoji_dragon_face_inverse = PrivateSFSymbol(identifier: "emoji.dragon.face.inverse")

	/// 􀹚 `emoji.monkey.face`
	static public let emoji_monkey_face = PrivateSFSymbol(identifier: "emoji.monkey.face")

	/// 􁅹 `emoji.monkey.face.inverse`
	static public let emoji_monkey_face_inverse = PrivateSFSymbol(identifier: "emoji.monkey.face.inverse")

	/// 􀹛 `emoji.dog.face`
	static public let emoji_dog_face = PrivateSFSymbol(identifier: "emoji.dog.face")

	/// 􁁢 `emoji.dog.face.inverse`
	static public let emoji_dog_face_inverse = PrivateSFSymbol(identifier: "emoji.dog.face.inverse")

	/// 􀹜 `emoji.pile.of.poop`
	static public let emoji_pile_of_poop = PrivateSFSymbol(identifier: "emoji.pile.of.poop")

	/// 􁅺 `emoji.pile.of.poop.inverse`
	static public let emoji_pile_of_poop_inverse = PrivateSFSymbol(identifier: "emoji.pile.of.poop.inverse")

	/// 􀹝 `emoji.horse.face`
	static public let emoji_horse_face = PrivateSFSymbol(identifier: "emoji.horse.face")

	/// 􁅻 `emoji.horse.face.inverse`
	static public let emoji_horse_face_inverse = PrivateSFSymbol(identifier: "emoji.horse.face.inverse")

	/// 􀹞 `emoji.ram.face`
	static public let emoji_ram_face = PrivateSFSymbol(identifier: "emoji.ram.face")

	/// 􁅼 `emoji.ram.face.inverse`
	static public let emoji_ram_face_inverse = PrivateSFSymbol(identifier: "emoji.ram.face.inverse")

	/// 􀹟 `emoji.rabbit.face`
	static public let emoji_rabbit_face = PrivateSFSymbol(identifier: "emoji.rabbit.face")

	/// 􁅽 `emoji.rabbit.face.inverse`
	static public let emoji_rabbit_face_inverse = PrivateSFSymbol(identifier: "emoji.rabbit.face.inverse")

	/// 􀹠 `emoji.snake`
	static public let emoji_snake = PrivateSFSymbol(identifier: "emoji.snake")

	/// 􁅾 `emoji.snake.inverse`
	static public let emoji_snake_inverse = PrivateSFSymbol(identifier: "emoji.snake.inverse")

	/// 􀹡 `emoji.chicken.face`
	static public let emoji_chicken_face = PrivateSFSymbol(identifier: "emoji.chicken.face")

	/// 􁅿 `emoji.chicken.face.inverse`
	static public let emoji_chicken_face_inverse = PrivateSFSymbol(identifier: "emoji.chicken.face.inverse")

	/// 􀹢 `emoji.pig.face`
	static public let emoji_pig_face = PrivateSFSymbol(identifier: "emoji.pig.face")

	/// 􁆱 `emoji.pig.face.inverse`
	static public let emoji_pig_face_inverse = PrivateSFSymbol(identifier: "emoji.pig.face.inverse")

	/// 􀹣 `emoji.mouse.face`
	static public let emoji_mouse_face = PrivateSFSymbol(identifier: "emoji.mouse.face")

	/// 􁆲 `emoji.mouse.face.inverse`
	static public let emoji_mouse_face_inverse = PrivateSFSymbol(identifier: "emoji.mouse.face.inverse")

	/// 􀹤 `emoji.cow.face`
	static public let emoji_cow_face = PrivateSFSymbol(identifier: "emoji.cow.face")

	/// 􁆳 `emoji.cow.face.inverse`
	static public let emoji_cow_face_inverse = PrivateSFSymbol(identifier: "emoji.cow.face.inverse")

	/// 􁈆 `emoji.soccer.ball`
	static public let emoji_soccer_ball = PrivateSFSymbol(identifier: "emoji.soccer.ball")

	/// 􁈙 `emoji.soccer.ball.inverse`
	static public let emoji_soccer_ball_inverse = PrivateSFSymbol(identifier: "emoji.soccer.ball.inverse")

	/// 􁈇 `emoji.basketball`
	static public let emoji_basketball = PrivateSFSymbol(identifier: "emoji.basketball")

	/// 􁈚 `emoji.basketball.inverse`
	static public let emoji_basketball_inverse = PrivateSFSymbol(identifier: "emoji.basketball.inverse")

	/// 􁈈 `emoji.american.football`
	static public let emoji_american_football = PrivateSFSymbol(identifier: "emoji.american.football")

	/// 􁈛 `emoji.american.football.inverse`
	static public let emoji_american_football_inverse = PrivateSFSymbol(identifier: "emoji.american.football.inverse")

	/// 􁈉 `emoji.baseball`
	static public let emoji_baseball = PrivateSFSymbol(identifier: "emoji.baseball")

	/// 􁈜 `emoji.baseball.inverse`
	static public let emoji_baseball_inverse = PrivateSFSymbol(identifier: "emoji.baseball.inverse")
}