//
//  PrivateSFSymbols.2024.3.swift
//
//  Automatically generated by SFSymbolKit.
//  Do not edit directly!
//  swift-format-ignore-file

@_documentation(visibility: internal)
@available(iOS 18.4, macOS 15.4, tvOS 18.4, visionOS 2.4, watchOS 11.4, *)
extension PrivateSFSymbol {
	/// 􂽰 `long.text.page`
	static public let long_text_page = PrivateSFSymbol(identifier: "long.text.page")

	/// 􂽳 `long.text.page.fill`
	///
	/// - categories:
	///   - `multicolor`
	static public let long_text_page_fill = PrivateSFSymbol(identifier: "long.text.page.fill")

	/// 􂼍 `app.grid.2x2.fill`
	static public let app_grid_2x2_fill = PrivateSFSymbol(identifier: "app.grid.2x2.fill")

	/// 􂼎 `app.grid.2x2.and.person.fill`
	static public let app_grid_2x2_and_person_fill = PrivateSFSymbol(identifier: "app.grid.2x2.and.person.fill")

	/// 􂽶 `f1`
	///
	/// - categories:
	///   - `keyboard`
	static public let f1 = PrivateSFSymbol(identifier: "f1")

	/// 􂼒 `rays.6`
	///
	/// - categories:
	///   - `variable`
	static public let rays_6 = PrivateSFSymbol(identifier: "rays.6")

	/// 􂼐 `music.note.circle.righthalf.dotted`
	///
	/// - search keywords:
	///   - `media`
	static public let music_note_circle_righthalf_dotted = PrivateSFSymbol(identifier: "music.note.circle.righthalf.dotted")

	/// 􂻡 `event.2.text.fill`
	///
	/// - categories:
	///   - `multicolor`
	static public let event_2_text_fill = PrivateSFSymbol(identifier: "event.2.text.fill")

	/// 􂽏 `shield.split.diagonal`
	///
	/// - categories:
	///   - `objectsandtools`
	///   - `privacyandsecurity`
	///   - `shapes`
	static public let shield_split_diagonal = PrivateSFSymbol(identifier: "shield.split.diagonal")

	/// 􂽐 `shield.split.diagonal.fill`
	///
	/// - categories:
	///   - `objectsandtools`
	///   - `privacyandsecurity`
	///   - `shapes`
	static public let shield_split_diagonal_fill = PrivateSFSymbol(identifier: "shield.split.diagonal.fill")

	/// 􂽑 `shield.split.diagonal.badge.clock`
	///
	/// - categories:
	///   - `multicolor`
	///   - `objectsandtools`
	///   - `privacyandsecurity`
	///   - `shapes`
	static public let shield_split_diagonal_badge_clock = PrivateSFSymbol(identifier: "shield.split.diagonal.badge.clock")

	/// 􂽒 `shield.split.diagonal.badge.clock.fill`
	///
	/// - categories:
	///   - `multicolor`
	///   - `objectsandtools`
	///   - `privacyandsecurity`
	///   - `shapes`
	static public let shield_split_diagonal_badge_clock_fill = PrivateSFSymbol(identifier: "shield.split.diagonal.badge.clock.fill")

	/// 􂻤 `capsule.grid.2x3`
	///
	/// - categories:
	///   - `devices`
	static public let capsule_grid_2x3 = PrivateSFSymbol(identifier: "capsule.grid.2x3")

	/// 􀺕 `capsule.grid.2x4.applewatch.case`
	///
	/// - categories:
	///   - `devices`
	static public let capsule_grid_2x4_applewatch_case = PrivateSFSymbol(identifier: "capsule.grid.2x4.applewatch.case")

	/// 􂻢 `nfc.app`
	///
	/// - categories:
	///   - `connectivity`
	///   - `variable`
	static public let nfc_app = PrivateSFSymbol(identifier: "nfc.app")

	/// 􂻣 `nfc.app.fill`
	///
	/// - categories:
	///   - `connectivity`
	///   - `multicolor`
	///   - `variable`
	static public let nfc_app_fill = PrivateSFSymbol(identifier: "nfc.app.fill")

	/// 􂽍 `hand.draw.and.line.dotted`
	///
	/// - categories:
	///   - `human`
	///
	/// - search keywords:
	///   - `touch`
	static public let hand_draw_and_line_dotted = PrivateSFSymbol(identifier: "hand.draw.and.line.dotted")

	/// 􂽎 `hand.draw.and.line.dotted.fill`
	///
	/// - categories:
	///   - `human`
	///
	/// - search keywords:
	///   - `touch`
	static public let hand_draw_and_line_dotted_fill = PrivateSFSymbol(identifier: "hand.draw.and.line.dotted.fill")

	/// 􂹮 `michelin.key.logo`
	static public let michelin_key_logo = PrivateSFSymbol(identifier: "michelin.key.logo")

	/// 􂼻 `apple.energy`
	///
	/// - categories:
	///   - `multicolor`
	///   - `variable`
	static public let apple_energy = PrivateSFSymbol(identifier: "apple.energy")

	/// 􂻠 `reminders.checklist`
	static public let reminders_checklist = PrivateSFSymbol(identifier: "reminders.checklist")

	/// 􂿈 `apple.math.notes.ar`
	///
	/// - categories:
	///   - `math`
	static public let apple_math_notes_ar = PrivateSFSymbol(identifier: "apple.math.notes.ar")
}