//
//  SFSymbol+Symbols.2021.1.swift
//
//  Automatically generated by sf-symbol-member-gen
//  Do not edit directly!
//  swift-format-ignore-file

@_documentation(visibility: internal)
extension SFSymbol {
	@available(iOS 15.1, macOS 12.0, tvOS 15.1, visionOS 1.0, watchOS 8.1, *)
	static public let bolt_ring_closed = SFSymbol(rawValue: "bolt.ring.closed")

	@available(iOS 15.1, macOS 12.0, tvOS 15.1, visionOS 1.0, watchOS 8.1, *)
	static public let platter_filled_top_iphone = SFSymbol(rawValue: "platter.filled.top.iphone")

	@available(iOS 15.1, macOS 12.0, tvOS 15.1, visionOS 1.0, watchOS 8.1, *)
	static public let platter_filled_bottom_iphone = SFSymbol(rawValue: "platter.filled.bottom.iphone")

	@available(iOS 15.1, macOS 12.0, tvOS 15.1, visionOS 1.0, watchOS 8.1, *)
	static public let platter_filled_top_and_arrow_up_iphone = SFSymbol(rawValue: "platter.filled.top.and.arrow.up.iphone")

	@available(iOS 15.1, macOS 12.0, tvOS 15.1, visionOS 1.0, watchOS 8.1, *)
	static public let platter_filled_bottom_and_arrow_down_iphone = SFSymbol(rawValue: "platter.filled.bottom.and.arrow.down.iphone")

	@available(iOS 15.1, macOS 12.0, tvOS 15.1, visionOS 1.0, watchOS 8.1, *)
	static public let square_3_layers_3d_down_right = SFSymbol(rawValue: "square.3.layers.3d.down.right")

	@available(iOS 15.1, macOS 12.0, tvOS 15.1, visionOS 1.0, watchOS 8.1, *)
	static public let square_3_layers_3d_down_left = SFSymbol(rawValue: "square.3.layers.3d.down.left")

	@available(iOS 15.1, macOS 12.0, tvOS 15.1, visionOS 1.0, watchOS 8.1, *)
	static public let square_3_layers_3d_down_forward = SFSymbol(rawValue: "square.3.layers.3d.down.forward")

	@available(iOS 15.1, macOS 12.0, tvOS 15.1, visionOS 1.0, watchOS 8.1, *)
	static public let square_3_layers_3d_down_backward = SFSymbol(rawValue: "square.3.layers.3d.down.backward")

	@available(iOS 15.1, macOS 12.0, tvOS 15.1, visionOS 1.0, watchOS 8.1, *)
	static public let text_justify_left = SFSymbol(rawValue: "text.justify.left")

	@available(iOS 15.1, macOS 12.0, tvOS 15.1, visionOS 1.0, watchOS 8.1, *)
	static public let text_justify_right = SFSymbol(rawValue: "text.justify.right")

	@available(iOS 15.1, macOS 12.0, tvOS 15.1, visionOS 1.0, watchOS 8.1, *)
	static public let text_justify_leading = SFSymbol(rawValue: "text.justify.leading")

	@available(iOS 15.1, macOS 12.0, tvOS 15.1, visionOS 1.0, watchOS 8.1, *)
	static public let text_justify_trailing = SFSymbol(rawValue: "text.justify.trailing")
}