//
//  SFSymbols.2023.3.swift
//
//  Automatically generated by SFSymbolKit.
//  Do not edit directly!
//  swift-format-ignore-file

@_documentation(visibility: internal)
@available(iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4, *)
extension SFSymbol {
	/// `apple.terminal.circle`
	///
	/// - categories:
	///   - `variable`
	static public let apple_terminal_circle = SFSymbol(identifier: "apple.terminal.circle")

	/// `apple.terminal.circle.fill`
	///
	/// - categories:
	///   - `multicolor`
	static public let apple_terminal_circle_fill = SFSymbol(identifier: "apple.terminal.circle.fill")

	/// `plus.circle.dashed`
	static public let plus_circle_dashed = SFSymbol(identifier: "plus.circle.dashed")

	/// `arrow.down.app.dashed`
	static public let arrow_down_app_dashed = SFSymbol(identifier: "arrow.down.app.dashed")

	/// `arrow.down.app.dashed.trianglebadge.exclamationmark`
	///
	/// - categories:
	///   - `multicolor`
	static public let arrow_down_app_dashed_trianglebadge_exclamationmark = SFSymbol(identifier: "arrow.down.app.dashed.trianglebadge.exclamationmark")

	/// `medal.star`
	///
	/// - categories:
	///   - `objectsandtools`
	static public let medal_star = SFSymbol(identifier: "medal.star")

	/// `medal.star.fill`
	///
	/// - categories:
	///   - `objectsandtools`
	static public let medal_star_fill = SFSymbol(identifier: "medal.star.fill")

	/// `translate`
	///
	/// - categories:
	///   - `communication`
	static public let translate = SFSymbol(identifier: "translate")

	/// `iphone.gen1.badge.exclamationmark`
	///
	/// - categories:
	///   - `devices`
	///   - `multicolor`
	static public let iphone_gen1_badge_exclamationmark = SFSymbol(identifier: "iphone.gen1.badge.exclamationmark")

	/// `iphone.gen2.badge.exclamationmark`
	///
	/// - categories:
	///   - `devices`
	///   - `multicolor`
	static public let iphone_gen2_badge_exclamationmark = SFSymbol(identifier: "iphone.gen2.badge.exclamationmark")

	/// `iphone.gen3.badge.exclamationmark`
	///
	/// - categories:
	///   - `devices`
	///   - `multicolor`
	static public let iphone_gen3_badge_exclamationmark = SFSymbol(identifier: "iphone.gen3.badge.exclamationmark")

	/// `iphone.badge.exclamationmark`
	///
	/// - categories:
	///   - `devices`
	///   - `multicolor`
	static public let iphone_badge_exclamationmark = SFSymbol(identifier: "iphone.badge.exclamationmark")

	/// `ipad.gen1.badge.exclamationmark`
	///
	/// - categories:
	///   - `devices`
	///   - `multicolor`
	static public let ipad_gen1_badge_exclamationmark = SFSymbol(identifier: "ipad.gen1.badge.exclamationmark")

	/// `ipad.gen1.landscape.badge.exclamationmark`
	///
	/// - categories:
	///   - `devices`
	///   - `multicolor`
	static public let ipad_gen1_landscape_badge_exclamationmark = SFSymbol(identifier: "ipad.gen1.landscape.badge.exclamationmark")

	/// `ipad.gen2.badge.exclamationmark`
	///
	/// - categories:
	///   - `devices`
	///   - `multicolor`
	static public let ipad_gen2_badge_exclamationmark = SFSymbol(identifier: "ipad.gen2.badge.exclamationmark")

	/// `ipad.gen2.landscape.badge.exclamationmark`
	///
	/// - categories:
	///   - `devices`
	///   - `multicolor`
	static public let ipad_gen2_landscape_badge_exclamationmark = SFSymbol(identifier: "ipad.gen2.landscape.badge.exclamationmark")

	/// `ipad.badge.exclamationmark`
	///
	/// - categories:
	///   - `devices`
	///   - `multicolor`
	static public let ipad_badge_exclamationmark = SFSymbol(identifier: "ipad.badge.exclamationmark")

	/// `ipad.landscape.badge.exclamationmark`
	///
	/// - categories:
	///   - `devices`
	///   - `multicolor`
	static public let ipad_landscape_badge_exclamationmark = SFSymbol(identifier: "ipad.landscape.badge.exclamationmark")

	/// `audio.jack.stereo`
	///
	/// - categories:
	///   - `devices`
	static public let audio_jack_stereo = SFSymbol(identifier: "audio.jack.stereo")

	/// `audio.jack.mono`
	///
	/// - categories:
	///   - `devices`
	static public let audio_jack_mono = SFSymbol(identifier: "audio.jack.mono")

	/// `apple.meditate`
	///
	/// - categories:
	///   - `health`
	///   - `nature`
	static public let apple_meditate = SFSymbol(identifier: "apple.meditate")

	/// `apple.meditate.square.stack`
	///
	/// - categories:
	///   - `health`
	///   - `nature`
	static public let apple_meditate_square_stack = SFSymbol(identifier: "apple.meditate.square.stack")

	/// `apple.meditate.square.stack.fill`
	///
	/// - categories:
	///   - `health`
	///   - `nature`
	static public let apple_meditate_square_stack_fill = SFSymbol(identifier: "apple.meditate.square.stack.fill")
}