//
//  SFSymbols.2020.2.swift
//
//  Automatically generated by sf-symbol-member-gen
//  Do not edit directly!
//  swift-format-ignore-file

@_documentation(visibility: internal)
@available(iOS 14.5, macOS 11.3, tvOS 14.5, visionOS 1.0, watchOS 7.4, *)
extension SFSymbol {
	static public let character_bubble = SFSymbol(identifier: "character.bubble")

	static public let character_bubble_fill = SFSymbol(identifier: "character.bubble.fill")

	static public let character_bubble_ar = SFSymbol(identifier: "character.bubble.ar")

	static public let character_bubble_fill_ar = SFSymbol(identifier: "character.bubble.fill.ar")

	static public let character_bubble_he = SFSymbol(identifier: "character.bubble.he")

	static public let character_bubble_fill_he = SFSymbol(identifier: "character.bubble.fill.he")

	static public let applewatch_side_right = SFSymbol(identifier: "applewatch.side.right")

	static public let character_cursor_ibeam = SFSymbol(identifier: "character.cursor.ibeam")

	static public let character_cursor_ibeam_ar = SFSymbol(identifier: "character.cursor.ibeam.ar")

	static public let character_cursor_ibeam_he = SFSymbol(identifier: "character.cursor.ibeam.he")

	static public let character_cursor_ibeam_th = SFSymbol(identifier: "character.cursor.ibeam.th")

	static public let character_cursor_ibeam_zh = SFSymbol(identifier: "character.cursor.ibeam.zh")

	static public let character_cursor_ibeam_ja = SFSymbol(identifier: "character.cursor.ibeam.ja")

	static public let character_cursor_ibeam_ko = SFSymbol(identifier: "character.cursor.ibeam.ko")

	static public let character_cursor_ibeam_hi = SFSymbol(identifier: "character.cursor.ibeam.hi")

	static public let character_textbox = SFSymbol(identifier: "character.textbox")

	static public let character_textbox_ar = SFSymbol(identifier: "character.textbox.ar")

	static public let character_textbox_he = SFSymbol(identifier: "character.textbox.he")

	static public let character_textbox_th = SFSymbol(identifier: "character.textbox.th")

	static public let character_textbox_zh = SFSymbol(identifier: "character.textbox.zh")

	static public let character_textbox_ja = SFSymbol(identifier: "character.textbox.ja")

	static public let character_textbox_ko = SFSymbol(identifier: "character.textbox.ko")

	static public let character_textbox_hi = SFSymbol(identifier: "character.textbox.hi")
}