//
//  SFSymbols.2023.2.swift
//
//  Automatically generated by SFSymbolKit.
//  Do not edit directly!
//  swift-format-ignore-file

@_documentation(visibility: internal)
@available(iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.1, watchOS 10.2, *)
extension SFSymbol {
	/// `square.and.arrow.up.badge.clock`
	///
	/// - categories:
	///   - `multicolor`
	///
	/// - search keywords:
	///   - `export`
	///   - `share`
	///   - `sharrow`
	///   - `upload`
	static public let square_and_arrow_up_badge_clock = SFSymbol(identifier: "square.and.arrow.up.badge.clock")

	/// `square.and.arrow.up.badge.clock.fill`
	///
	/// - categories:
	///   - `multicolor`
	///
	/// - search keywords:
	///   - `export`
	///   - `share`
	///   - `sharrow`
	///   - `upload`
	static public let square_and_arrow_up_badge_clock_fill = SFSymbol(identifier: "square.and.arrow.up.badge.clock.fill")

	/// `0.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `0_circle_hi` = SFSymbol(identifier: "0.circle.hi")

	/// `0.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `0_circle_fill_hi` = SFSymbol(identifier: "0.circle.fill.hi")

	/// `0.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `0_square_hi` = SFSymbol(identifier: "0.square.hi")

	/// `0.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `0_square_fill_hi` = SFSymbol(identifier: "0.square.fill.hi")

	/// `1.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `1_circle_hi` = SFSymbol(identifier: "1.circle.hi")

	/// `1.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `1_circle_fill_hi` = SFSymbol(identifier: "1.circle.fill.hi")

	/// `1.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `1_square_hi` = SFSymbol(identifier: "1.square.hi")

	/// `1.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `1_square_fill_hi` = SFSymbol(identifier: "1.square.fill.hi")

	/// `2.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `2_circle_hi` = SFSymbol(identifier: "2.circle.hi")

	/// `2.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `2_circle_fill_hi` = SFSymbol(identifier: "2.circle.fill.hi")

	/// `2.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `2_square_hi` = SFSymbol(identifier: "2.square.hi")

	/// `2.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `2_square_fill_hi` = SFSymbol(identifier: "2.square.fill.hi")

	/// `3.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `3_circle_hi` = SFSymbol(identifier: "3.circle.hi")

	/// `3.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `3_circle_fill_hi` = SFSymbol(identifier: "3.circle.fill.hi")

	/// `3.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `3_square_hi` = SFSymbol(identifier: "3.square.hi")

	/// `3.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `3_square_fill_hi` = SFSymbol(identifier: "3.square.fill.hi")

	/// `4.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `4_circle_hi` = SFSymbol(identifier: "4.circle.hi")

	/// `4.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `4_circle_fill_hi` = SFSymbol(identifier: "4.circle.fill.hi")

	/// `4.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `4_square_hi` = SFSymbol(identifier: "4.square.hi")

	/// `4.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `4_square_fill_hi` = SFSymbol(identifier: "4.square.fill.hi")

	/// `5.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `5_circle_hi` = SFSymbol(identifier: "5.circle.hi")

	/// `5.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `5_circle_fill_hi` = SFSymbol(identifier: "5.circle.fill.hi")

	/// `5.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `5_square_hi` = SFSymbol(identifier: "5.square.hi")

	/// `5.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `5_square_fill_hi` = SFSymbol(identifier: "5.square.fill.hi")

	/// `6.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `6_circle_hi` = SFSymbol(identifier: "6.circle.hi")

	/// `6.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `6_circle_fill_hi` = SFSymbol(identifier: "6.circle.fill.hi")

	/// `6.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `6_square_hi` = SFSymbol(identifier: "6.square.hi")

	/// `6.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `6_square_fill_hi` = SFSymbol(identifier: "6.square.fill.hi")

	/// `7.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `7_circle_hi` = SFSymbol(identifier: "7.circle.hi")

	/// `7.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `7_circle_fill_hi` = SFSymbol(identifier: "7.circle.fill.hi")

	/// `7.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `7_square_hi` = SFSymbol(identifier: "7.square.hi")

	/// `7.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `7_square_fill_hi` = SFSymbol(identifier: "7.square.fill.hi")

	/// `8.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `8_circle_hi` = SFSymbol(identifier: "8.circle.hi")

	/// `8.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `8_circle_fill_hi` = SFSymbol(identifier: "8.circle.fill.hi")

	/// `8.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `8_square_hi` = SFSymbol(identifier: "8.square.hi")

	/// `8.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `8_square_fill_hi` = SFSymbol(identifier: "8.square.fill.hi")

	/// `9.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `9_circle_hi` = SFSymbol(identifier: "9.circle.hi")

	/// `9.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `9_circle_fill_hi` = SFSymbol(identifier: "9.circle.fill.hi")

	/// `9.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `9_square_hi` = SFSymbol(identifier: "9.square.hi")

	/// `9.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `9_square_fill_hi` = SFSymbol(identifier: "9.square.fill.hi")

	/// `00.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `00_circle_ar` = SFSymbol(identifier: "00.circle.ar")

	/// `00.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `00_circle_fill_ar` = SFSymbol(identifier: "00.circle.fill.ar")

	/// `00.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `00_square_ar` = SFSymbol(identifier: "00.square.ar")

	/// `00.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `00_square_fill_ar` = SFSymbol(identifier: "00.square.fill.ar")

	/// `01.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `01_circle_ar` = SFSymbol(identifier: "01.circle.ar")

	/// `01.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `01_circle_fill_ar` = SFSymbol(identifier: "01.circle.fill.ar")

	/// `01.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `01_square_ar` = SFSymbol(identifier: "01.square.ar")

	/// `01.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `01_square_fill_ar` = SFSymbol(identifier: "01.square.fill.ar")

	/// `02.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `02_circle_ar` = SFSymbol(identifier: "02.circle.ar")

	/// `02.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `02_circle_fill_ar` = SFSymbol(identifier: "02.circle.fill.ar")

	/// `02.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `02_square_ar` = SFSymbol(identifier: "02.square.ar")

	/// `02.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `02_square_fill_ar` = SFSymbol(identifier: "02.square.fill.ar")

	/// `03.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `03_circle_ar` = SFSymbol(identifier: "03.circle.ar")

	/// `03.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `03_circle_fill_ar` = SFSymbol(identifier: "03.circle.fill.ar")

	/// `03.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `03_square_ar` = SFSymbol(identifier: "03.square.ar")

	/// `03.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `03_square_fill_ar` = SFSymbol(identifier: "03.square.fill.ar")

	/// `04.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `04_circle_ar` = SFSymbol(identifier: "04.circle.ar")

	/// `04.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `04_circle_fill_ar` = SFSymbol(identifier: "04.circle.fill.ar")

	/// `04.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `04_square_ar` = SFSymbol(identifier: "04.square.ar")

	/// `04.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `04_square_fill_ar` = SFSymbol(identifier: "04.square.fill.ar")

	/// `05.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `05_circle_ar` = SFSymbol(identifier: "05.circle.ar")

	/// `05.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `05_circle_fill_ar` = SFSymbol(identifier: "05.circle.fill.ar")

	/// `05.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `05_square_ar` = SFSymbol(identifier: "05.square.ar")

	/// `05.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `05_square_fill_ar` = SFSymbol(identifier: "05.square.fill.ar")

	/// `06.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `06_circle_ar` = SFSymbol(identifier: "06.circle.ar")

	/// `06.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `06_circle_fill_ar` = SFSymbol(identifier: "06.circle.fill.ar")

	/// `06.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `06_square_ar` = SFSymbol(identifier: "06.square.ar")

	/// `06.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `06_square_fill_ar` = SFSymbol(identifier: "06.square.fill.ar")

	/// `07.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `07_circle_ar` = SFSymbol(identifier: "07.circle.ar")

	/// `07.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `07_circle_fill_ar` = SFSymbol(identifier: "07.circle.fill.ar")

	/// `07.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `07_square_ar` = SFSymbol(identifier: "07.square.ar")

	/// `07.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `07_square_fill_ar` = SFSymbol(identifier: "07.square.fill.ar")

	/// `08.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `08_circle_ar` = SFSymbol(identifier: "08.circle.ar")

	/// `08.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `08_circle_fill_ar` = SFSymbol(identifier: "08.circle.fill.ar")

	/// `08.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `08_square_ar` = SFSymbol(identifier: "08.square.ar")

	/// `08.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `08_square_fill_ar` = SFSymbol(identifier: "08.square.fill.ar")

	/// `09.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `09_circle_ar` = SFSymbol(identifier: "09.circle.ar")

	/// `09.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `09_circle_fill_ar` = SFSymbol(identifier: "09.circle.fill.ar")

	/// `09.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `09_square_ar` = SFSymbol(identifier: "09.square.ar")

	/// `09.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `09_square_fill_ar` = SFSymbol(identifier: "09.square.fill.ar")

	/// `10.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `10_circle_ar` = SFSymbol(identifier: "10.circle.ar")

	/// `10.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `10_circle_fill_ar` = SFSymbol(identifier: "10.circle.fill.ar")

	/// `10.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `10_square_ar` = SFSymbol(identifier: "10.square.ar")

	/// `10.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `10_square_fill_ar` = SFSymbol(identifier: "10.square.fill.ar")

	/// `11.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `11_circle_ar` = SFSymbol(identifier: "11.circle.ar")

	/// `11.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `11_circle_fill_ar` = SFSymbol(identifier: "11.circle.fill.ar")

	/// `11.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `11_square_ar` = SFSymbol(identifier: "11.square.ar")

	/// `11.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `11_square_fill_ar` = SFSymbol(identifier: "11.square.fill.ar")

	/// `12.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `12_circle_ar` = SFSymbol(identifier: "12.circle.ar")

	/// `12.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `12_circle_fill_ar` = SFSymbol(identifier: "12.circle.fill.ar")

	/// `12.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `12_square_ar` = SFSymbol(identifier: "12.square.ar")

	/// `12.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `12_square_fill_ar` = SFSymbol(identifier: "12.square.fill.ar")

	/// `13.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `13_circle_ar` = SFSymbol(identifier: "13.circle.ar")

	/// `13.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `13_circle_fill_ar` = SFSymbol(identifier: "13.circle.fill.ar")

	/// `13.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `13_square_ar` = SFSymbol(identifier: "13.square.ar")

	/// `13.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `13_square_fill_ar` = SFSymbol(identifier: "13.square.fill.ar")

	/// `14.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `14_circle_ar` = SFSymbol(identifier: "14.circle.ar")

	/// `14.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `14_circle_fill_ar` = SFSymbol(identifier: "14.circle.fill.ar")

	/// `14.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `14_square_ar` = SFSymbol(identifier: "14.square.ar")

	/// `14.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `14_square_fill_ar` = SFSymbol(identifier: "14.square.fill.ar")

	/// `15.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `15_circle_ar` = SFSymbol(identifier: "15.circle.ar")

	/// `15.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `15_circle_fill_ar` = SFSymbol(identifier: "15.circle.fill.ar")

	/// `15.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `15_square_ar` = SFSymbol(identifier: "15.square.ar")

	/// `15.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `15_square_fill_ar` = SFSymbol(identifier: "15.square.fill.ar")

	/// `16.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `16_circle_ar` = SFSymbol(identifier: "16.circle.ar")

	/// `16.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `16_circle_fill_ar` = SFSymbol(identifier: "16.circle.fill.ar")

	/// `16.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `16_square_ar` = SFSymbol(identifier: "16.square.ar")

	/// `16.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `16_square_fill_ar` = SFSymbol(identifier: "16.square.fill.ar")

	/// `17.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `17_circle_ar` = SFSymbol(identifier: "17.circle.ar")

	/// `17.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `17_circle_fill_ar` = SFSymbol(identifier: "17.circle.fill.ar")

	/// `17.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `17_square_ar` = SFSymbol(identifier: "17.square.ar")

	/// `17.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `17_square_fill_ar` = SFSymbol(identifier: "17.square.fill.ar")

	/// `18.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `18_circle_ar` = SFSymbol(identifier: "18.circle.ar")

	/// `18.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `18_circle_fill_ar` = SFSymbol(identifier: "18.circle.fill.ar")

	/// `18.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `18_square_ar` = SFSymbol(identifier: "18.square.ar")

	/// `18.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `18_square_fill_ar` = SFSymbol(identifier: "18.square.fill.ar")

	/// `19.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `19_circle_ar` = SFSymbol(identifier: "19.circle.ar")

	/// `19.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `19_circle_fill_ar` = SFSymbol(identifier: "19.circle.fill.ar")

	/// `19.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `19_square_ar` = SFSymbol(identifier: "19.square.ar")

	/// `19.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `19_square_fill_ar` = SFSymbol(identifier: "19.square.fill.ar")

	/// `20.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `20_circle_ar` = SFSymbol(identifier: "20.circle.ar")

	/// `20.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `20_circle_fill_ar` = SFSymbol(identifier: "20.circle.fill.ar")

	/// `20.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `20_square_ar` = SFSymbol(identifier: "20.square.ar")

	/// `20.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `20_square_fill_ar` = SFSymbol(identifier: "20.square.fill.ar")

	/// `21.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `21_circle_ar` = SFSymbol(identifier: "21.circle.ar")

	/// `21.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `21_circle_fill_ar` = SFSymbol(identifier: "21.circle.fill.ar")

	/// `21.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `21_square_ar` = SFSymbol(identifier: "21.square.ar")

	/// `21.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `21_square_fill_ar` = SFSymbol(identifier: "21.square.fill.ar")

	/// `22.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `22_circle_ar` = SFSymbol(identifier: "22.circle.ar")

	/// `22.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `22_circle_fill_ar` = SFSymbol(identifier: "22.circle.fill.ar")

	/// `22.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `22_square_ar` = SFSymbol(identifier: "22.square.ar")

	/// `22.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `22_square_fill_ar` = SFSymbol(identifier: "22.square.fill.ar")

	/// `23.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `23_circle_ar` = SFSymbol(identifier: "23.circle.ar")

	/// `23.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `23_circle_fill_ar` = SFSymbol(identifier: "23.circle.fill.ar")

	/// `23.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `23_square_ar` = SFSymbol(identifier: "23.square.ar")

	/// `23.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `23_square_fill_ar` = SFSymbol(identifier: "23.square.fill.ar")

	/// `24.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `24_circle_ar` = SFSymbol(identifier: "24.circle.ar")

	/// `24.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `24_circle_fill_ar` = SFSymbol(identifier: "24.circle.fill.ar")

	/// `24.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `24_square_ar` = SFSymbol(identifier: "24.square.ar")

	/// `24.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `24_square_fill_ar` = SFSymbol(identifier: "24.square.fill.ar")

	/// `25.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `25_circle_ar` = SFSymbol(identifier: "25.circle.ar")

	/// `25.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `25_circle_fill_ar` = SFSymbol(identifier: "25.circle.fill.ar")

	/// `25.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `25_square_ar` = SFSymbol(identifier: "25.square.ar")

	/// `25.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `25_square_fill_ar` = SFSymbol(identifier: "25.square.fill.ar")

	/// `26.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `26_circle_ar` = SFSymbol(identifier: "26.circle.ar")

	/// `26.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `26_circle_fill_ar` = SFSymbol(identifier: "26.circle.fill.ar")

	/// `26.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `26_square_ar` = SFSymbol(identifier: "26.square.ar")

	/// `26.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `26_square_fill_ar` = SFSymbol(identifier: "26.square.fill.ar")

	/// `27.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `27_circle_ar` = SFSymbol(identifier: "27.circle.ar")

	/// `27.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `27_circle_fill_ar` = SFSymbol(identifier: "27.circle.fill.ar")

	/// `27.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `27_square_ar` = SFSymbol(identifier: "27.square.ar")

	/// `27.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `27_square_fill_ar` = SFSymbol(identifier: "27.square.fill.ar")

	/// `28.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `28_circle_ar` = SFSymbol(identifier: "28.circle.ar")

	/// `28.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `28_circle_fill_ar` = SFSymbol(identifier: "28.circle.fill.ar")

	/// `28.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `28_square_ar` = SFSymbol(identifier: "28.square.ar")

	/// `28.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `28_square_fill_ar` = SFSymbol(identifier: "28.square.fill.ar")

	/// `29.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `29_circle_ar` = SFSymbol(identifier: "29.circle.ar")

	/// `29.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `29_circle_fill_ar` = SFSymbol(identifier: "29.circle.fill.ar")

	/// `29.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `29_square_ar` = SFSymbol(identifier: "29.square.ar")

	/// `29.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `29_square_fill_ar` = SFSymbol(identifier: "29.square.fill.ar")

	/// `30.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `30_circle_ar` = SFSymbol(identifier: "30.circle.ar")

	/// `30.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `30_circle_fill_ar` = SFSymbol(identifier: "30.circle.fill.ar")

	/// `30.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `30_square_ar` = SFSymbol(identifier: "30.square.ar")

	/// `30.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `30_square_fill_ar` = SFSymbol(identifier: "30.square.fill.ar")

	/// `31.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `31_circle_ar` = SFSymbol(identifier: "31.circle.ar")

	/// `31.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `31_circle_fill_ar` = SFSymbol(identifier: "31.circle.fill.ar")

	/// `31.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `31_square_ar` = SFSymbol(identifier: "31.square.ar")

	/// `31.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `31_square_fill_ar` = SFSymbol(identifier: "31.square.fill.ar")

	/// `32.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `32_circle_ar` = SFSymbol(identifier: "32.circle.ar")

	/// `32.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `32_circle_fill_ar` = SFSymbol(identifier: "32.circle.fill.ar")

	/// `32.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `32_square_ar` = SFSymbol(identifier: "32.square.ar")

	/// `32.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `32_square_fill_ar` = SFSymbol(identifier: "32.square.fill.ar")

	/// `33.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `33_circle_ar` = SFSymbol(identifier: "33.circle.ar")

	/// `33.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `33_circle_fill_ar` = SFSymbol(identifier: "33.circle.fill.ar")

	/// `33.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `33_square_ar` = SFSymbol(identifier: "33.square.ar")

	/// `33.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `33_square_fill_ar` = SFSymbol(identifier: "33.square.fill.ar")

	/// `34.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `34_circle_ar` = SFSymbol(identifier: "34.circle.ar")

	/// `34.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `34_circle_fill_ar` = SFSymbol(identifier: "34.circle.fill.ar")

	/// `34.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `34_square_ar` = SFSymbol(identifier: "34.square.ar")

	/// `34.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `34_square_fill_ar` = SFSymbol(identifier: "34.square.fill.ar")

	/// `35.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `35_circle_ar` = SFSymbol(identifier: "35.circle.ar")

	/// `35.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `35_circle_fill_ar` = SFSymbol(identifier: "35.circle.fill.ar")

	/// `35.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `35_square_ar` = SFSymbol(identifier: "35.square.ar")

	/// `35.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `35_square_fill_ar` = SFSymbol(identifier: "35.square.fill.ar")

	/// `36.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `36_circle_ar` = SFSymbol(identifier: "36.circle.ar")

	/// `36.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `36_circle_fill_ar` = SFSymbol(identifier: "36.circle.fill.ar")

	/// `36.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `36_square_ar` = SFSymbol(identifier: "36.square.ar")

	/// `36.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `36_square_fill_ar` = SFSymbol(identifier: "36.square.fill.ar")

	/// `37.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `37_circle_ar` = SFSymbol(identifier: "37.circle.ar")

	/// `37.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `37_circle_fill_ar` = SFSymbol(identifier: "37.circle.fill.ar")

	/// `37.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `37_square_ar` = SFSymbol(identifier: "37.square.ar")

	/// `37.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `37_square_fill_ar` = SFSymbol(identifier: "37.square.fill.ar")

	/// `38.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `38_circle_ar` = SFSymbol(identifier: "38.circle.ar")

	/// `38.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `38_circle_fill_ar` = SFSymbol(identifier: "38.circle.fill.ar")

	/// `38.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `38_square_ar` = SFSymbol(identifier: "38.square.ar")

	/// `38.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `38_square_fill_ar` = SFSymbol(identifier: "38.square.fill.ar")

	/// `39.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `39_circle_ar` = SFSymbol(identifier: "39.circle.ar")

	/// `39.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `39_circle_fill_ar` = SFSymbol(identifier: "39.circle.fill.ar")

	/// `39.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `39_square_ar` = SFSymbol(identifier: "39.square.ar")

	/// `39.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `39_square_fill_ar` = SFSymbol(identifier: "39.square.fill.ar")

	/// `40.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `40_circle_ar` = SFSymbol(identifier: "40.circle.ar")

	/// `40.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `40_circle_fill_ar` = SFSymbol(identifier: "40.circle.fill.ar")

	/// `40.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `40_square_ar` = SFSymbol(identifier: "40.square.ar")

	/// `40.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `40_square_fill_ar` = SFSymbol(identifier: "40.square.fill.ar")

	/// `41.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `41_circle_ar` = SFSymbol(identifier: "41.circle.ar")

	/// `41.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `41_circle_fill_ar` = SFSymbol(identifier: "41.circle.fill.ar")

	/// `41.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `41_square_ar` = SFSymbol(identifier: "41.square.ar")

	/// `41.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `41_square_fill_ar` = SFSymbol(identifier: "41.square.fill.ar")

	/// `42.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `42_circle_ar` = SFSymbol(identifier: "42.circle.ar")

	/// `42.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `42_circle_fill_ar` = SFSymbol(identifier: "42.circle.fill.ar")

	/// `42.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `42_square_ar` = SFSymbol(identifier: "42.square.ar")

	/// `42.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `42_square_fill_ar` = SFSymbol(identifier: "42.square.fill.ar")

	/// `43.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `43_circle_ar` = SFSymbol(identifier: "43.circle.ar")

	/// `43.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `43_circle_fill_ar` = SFSymbol(identifier: "43.circle.fill.ar")

	/// `43.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `43_square_ar` = SFSymbol(identifier: "43.square.ar")

	/// `43.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `43_square_fill_ar` = SFSymbol(identifier: "43.square.fill.ar")

	/// `44.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `44_circle_ar` = SFSymbol(identifier: "44.circle.ar")

	/// `44.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `44_circle_fill_ar` = SFSymbol(identifier: "44.circle.fill.ar")

	/// `44.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `44_square_ar` = SFSymbol(identifier: "44.square.ar")

	/// `44.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `44_square_fill_ar` = SFSymbol(identifier: "44.square.fill.ar")

	/// `45.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `45_circle_ar` = SFSymbol(identifier: "45.circle.ar")

	/// `45.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `45_circle_fill_ar` = SFSymbol(identifier: "45.circle.fill.ar")

	/// `45.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `45_square_ar` = SFSymbol(identifier: "45.square.ar")

	/// `45.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `45_square_fill_ar` = SFSymbol(identifier: "45.square.fill.ar")

	/// `46.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `46_circle_ar` = SFSymbol(identifier: "46.circle.ar")

	/// `46.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `46_circle_fill_ar` = SFSymbol(identifier: "46.circle.fill.ar")

	/// `46.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `46_square_ar` = SFSymbol(identifier: "46.square.ar")

	/// `46.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `46_square_fill_ar` = SFSymbol(identifier: "46.square.fill.ar")

	/// `47.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `47_circle_ar` = SFSymbol(identifier: "47.circle.ar")

	/// `47.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `47_circle_fill_ar` = SFSymbol(identifier: "47.circle.fill.ar")

	/// `47.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `47_square_ar` = SFSymbol(identifier: "47.square.ar")

	/// `47.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `47_square_fill_ar` = SFSymbol(identifier: "47.square.fill.ar")

	/// `48.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `48_circle_ar` = SFSymbol(identifier: "48.circle.ar")

	/// `48.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `48_circle_fill_ar` = SFSymbol(identifier: "48.circle.fill.ar")

	/// `48.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `48_square_ar` = SFSymbol(identifier: "48.square.ar")

	/// `48.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `48_square_fill_ar` = SFSymbol(identifier: "48.square.fill.ar")

	/// `49.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `49_circle_ar` = SFSymbol(identifier: "49.circle.ar")

	/// `49.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `49_circle_fill_ar` = SFSymbol(identifier: "49.circle.fill.ar")

	/// `49.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `49_square_ar` = SFSymbol(identifier: "49.square.ar")

	/// `49.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `49_square_fill_ar` = SFSymbol(identifier: "49.square.fill.ar")

	/// `50.circle.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `50_circle_ar` = SFSymbol(identifier: "50.circle.ar")

	/// `50.circle.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `50_circle_fill_ar` = SFSymbol(identifier: "50.circle.fill.ar")

	/// `50.square.ar`
	///
	/// - categories:
	///   - `indices`
	static public let `50_square_ar` = SFSymbol(identifier: "50.square.ar")

	/// `50.square.fill.ar`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `50_square_fill_ar` = SFSymbol(identifier: "50.square.fill.ar")

	/// `00.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `00_circle_hi` = SFSymbol(identifier: "00.circle.hi")

	/// `00.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `00_circle_fill_hi` = SFSymbol(identifier: "00.circle.fill.hi")

	/// `00.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `00_square_hi` = SFSymbol(identifier: "00.square.hi")

	/// `00.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `00_square_fill_hi` = SFSymbol(identifier: "00.square.fill.hi")

	/// `01.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `01_circle_hi` = SFSymbol(identifier: "01.circle.hi")

	/// `01.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `01_circle_fill_hi` = SFSymbol(identifier: "01.circle.fill.hi")

	/// `01.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `01_square_hi` = SFSymbol(identifier: "01.square.hi")

	/// `01.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `01_square_fill_hi` = SFSymbol(identifier: "01.square.fill.hi")

	/// `02.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `02_circle_hi` = SFSymbol(identifier: "02.circle.hi")

	/// `02.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `02_circle_fill_hi` = SFSymbol(identifier: "02.circle.fill.hi")

	/// `02.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `02_square_hi` = SFSymbol(identifier: "02.square.hi")

	/// `02.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `02_square_fill_hi` = SFSymbol(identifier: "02.square.fill.hi")

	/// `03.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `03_circle_hi` = SFSymbol(identifier: "03.circle.hi")

	/// `03.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `03_circle_fill_hi` = SFSymbol(identifier: "03.circle.fill.hi")

	/// `03.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `03_square_hi` = SFSymbol(identifier: "03.square.hi")

	/// `03.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `03_square_fill_hi` = SFSymbol(identifier: "03.square.fill.hi")

	/// `04.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `04_circle_hi` = SFSymbol(identifier: "04.circle.hi")

	/// `04.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `04_circle_fill_hi` = SFSymbol(identifier: "04.circle.fill.hi")

	/// `04.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `04_square_hi` = SFSymbol(identifier: "04.square.hi")

	/// `04.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `04_square_fill_hi` = SFSymbol(identifier: "04.square.fill.hi")

	/// `05.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `05_circle_hi` = SFSymbol(identifier: "05.circle.hi")

	/// `05.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `05_circle_fill_hi` = SFSymbol(identifier: "05.circle.fill.hi")

	/// `05.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `05_square_hi` = SFSymbol(identifier: "05.square.hi")

	/// `05.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `05_square_fill_hi` = SFSymbol(identifier: "05.square.fill.hi")

	/// `06.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `06_circle_hi` = SFSymbol(identifier: "06.circle.hi")

	/// `06.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `06_circle_fill_hi` = SFSymbol(identifier: "06.circle.fill.hi")

	/// `06.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `06_square_hi` = SFSymbol(identifier: "06.square.hi")

	/// `06.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `06_square_fill_hi` = SFSymbol(identifier: "06.square.fill.hi")

	/// `07.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `07_circle_hi` = SFSymbol(identifier: "07.circle.hi")

	/// `07.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `07_circle_fill_hi` = SFSymbol(identifier: "07.circle.fill.hi")

	/// `07.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `07_square_hi` = SFSymbol(identifier: "07.square.hi")

	/// `07.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `07_square_fill_hi` = SFSymbol(identifier: "07.square.fill.hi")

	/// `08.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `08_circle_hi` = SFSymbol(identifier: "08.circle.hi")

	/// `08.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `08_circle_fill_hi` = SFSymbol(identifier: "08.circle.fill.hi")

	/// `08.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `08_square_hi` = SFSymbol(identifier: "08.square.hi")

	/// `08.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `08_square_fill_hi` = SFSymbol(identifier: "08.square.fill.hi")

	/// `09.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `09_circle_hi` = SFSymbol(identifier: "09.circle.hi")

	/// `09.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `09_circle_fill_hi` = SFSymbol(identifier: "09.circle.fill.hi")

	/// `09.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `09_square_hi` = SFSymbol(identifier: "09.square.hi")

	/// `09.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `09_square_fill_hi` = SFSymbol(identifier: "09.square.fill.hi")

	/// `10.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `10_circle_hi` = SFSymbol(identifier: "10.circle.hi")

	/// `10.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `10_circle_fill_hi` = SFSymbol(identifier: "10.circle.fill.hi")

	/// `10.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `10_square_hi` = SFSymbol(identifier: "10.square.hi")

	/// `10.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `10_square_fill_hi` = SFSymbol(identifier: "10.square.fill.hi")

	/// `11.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `11_circle_hi` = SFSymbol(identifier: "11.circle.hi")

	/// `11.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `11_circle_fill_hi` = SFSymbol(identifier: "11.circle.fill.hi")

	/// `11.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `11_square_hi` = SFSymbol(identifier: "11.square.hi")

	/// `11.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `11_square_fill_hi` = SFSymbol(identifier: "11.square.fill.hi")

	/// `12.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `12_circle_hi` = SFSymbol(identifier: "12.circle.hi")

	/// `12.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `12_circle_fill_hi` = SFSymbol(identifier: "12.circle.fill.hi")

	/// `12.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `12_square_hi` = SFSymbol(identifier: "12.square.hi")

	/// `12.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `12_square_fill_hi` = SFSymbol(identifier: "12.square.fill.hi")

	/// `13.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `13_circle_hi` = SFSymbol(identifier: "13.circle.hi")

	/// `13.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `13_circle_fill_hi` = SFSymbol(identifier: "13.circle.fill.hi")

	/// `13.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `13_square_hi` = SFSymbol(identifier: "13.square.hi")

	/// `13.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `13_square_fill_hi` = SFSymbol(identifier: "13.square.fill.hi")

	/// `14.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `14_circle_hi` = SFSymbol(identifier: "14.circle.hi")

	/// `14.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `14_circle_fill_hi` = SFSymbol(identifier: "14.circle.fill.hi")

	/// `14.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `14_square_hi` = SFSymbol(identifier: "14.square.hi")

	/// `14.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `14_square_fill_hi` = SFSymbol(identifier: "14.square.fill.hi")

	/// `15.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `15_circle_hi` = SFSymbol(identifier: "15.circle.hi")

	/// `15.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `15_circle_fill_hi` = SFSymbol(identifier: "15.circle.fill.hi")

	/// `15.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `15_square_hi` = SFSymbol(identifier: "15.square.hi")

	/// `15.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `15_square_fill_hi` = SFSymbol(identifier: "15.square.fill.hi")

	/// `16.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `16_circle_hi` = SFSymbol(identifier: "16.circle.hi")

	/// `16.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `16_circle_fill_hi` = SFSymbol(identifier: "16.circle.fill.hi")

	/// `16.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `16_square_hi` = SFSymbol(identifier: "16.square.hi")

	/// `16.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `16_square_fill_hi` = SFSymbol(identifier: "16.square.fill.hi")

	/// `17.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `17_circle_hi` = SFSymbol(identifier: "17.circle.hi")

	/// `17.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `17_circle_fill_hi` = SFSymbol(identifier: "17.circle.fill.hi")

	/// `17.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `17_square_hi` = SFSymbol(identifier: "17.square.hi")

	/// `17.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `17_square_fill_hi` = SFSymbol(identifier: "17.square.fill.hi")

	/// `18.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `18_circle_hi` = SFSymbol(identifier: "18.circle.hi")

	/// `18.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `18_circle_fill_hi` = SFSymbol(identifier: "18.circle.fill.hi")

	/// `18.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `18_square_hi` = SFSymbol(identifier: "18.square.hi")

	/// `18.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `18_square_fill_hi` = SFSymbol(identifier: "18.square.fill.hi")

	/// `19.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `19_circle_hi` = SFSymbol(identifier: "19.circle.hi")

	/// `19.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `19_circle_fill_hi` = SFSymbol(identifier: "19.circle.fill.hi")

	/// `19.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `19_square_hi` = SFSymbol(identifier: "19.square.hi")

	/// `19.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `19_square_fill_hi` = SFSymbol(identifier: "19.square.fill.hi")

	/// `20.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `20_circle_hi` = SFSymbol(identifier: "20.circle.hi")

	/// `20.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `20_circle_fill_hi` = SFSymbol(identifier: "20.circle.fill.hi")

	/// `20.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `20_square_hi` = SFSymbol(identifier: "20.square.hi")

	/// `20.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `20_square_fill_hi` = SFSymbol(identifier: "20.square.fill.hi")

	/// `21.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `21_circle_hi` = SFSymbol(identifier: "21.circle.hi")

	/// `21.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `21_circle_fill_hi` = SFSymbol(identifier: "21.circle.fill.hi")

	/// `21.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `21_square_hi` = SFSymbol(identifier: "21.square.hi")

	/// `21.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `21_square_fill_hi` = SFSymbol(identifier: "21.square.fill.hi")

	/// `22.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `22_circle_hi` = SFSymbol(identifier: "22.circle.hi")

	/// `22.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `22_circle_fill_hi` = SFSymbol(identifier: "22.circle.fill.hi")

	/// `22.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `22_square_hi` = SFSymbol(identifier: "22.square.hi")

	/// `22.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `22_square_fill_hi` = SFSymbol(identifier: "22.square.fill.hi")

	/// `23.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `23_circle_hi` = SFSymbol(identifier: "23.circle.hi")

	/// `23.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `23_circle_fill_hi` = SFSymbol(identifier: "23.circle.fill.hi")

	/// `23.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `23_square_hi` = SFSymbol(identifier: "23.square.hi")

	/// `23.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `23_square_fill_hi` = SFSymbol(identifier: "23.square.fill.hi")

	/// `24.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `24_circle_hi` = SFSymbol(identifier: "24.circle.hi")

	/// `24.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `24_circle_fill_hi` = SFSymbol(identifier: "24.circle.fill.hi")

	/// `24.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `24_square_hi` = SFSymbol(identifier: "24.square.hi")

	/// `24.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `24_square_fill_hi` = SFSymbol(identifier: "24.square.fill.hi")

	/// `25.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `25_circle_hi` = SFSymbol(identifier: "25.circle.hi")

	/// `25.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `25_circle_fill_hi` = SFSymbol(identifier: "25.circle.fill.hi")

	/// `25.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `25_square_hi` = SFSymbol(identifier: "25.square.hi")

	/// `25.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `25_square_fill_hi` = SFSymbol(identifier: "25.square.fill.hi")

	/// `26.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `26_circle_hi` = SFSymbol(identifier: "26.circle.hi")

	/// `26.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `26_circle_fill_hi` = SFSymbol(identifier: "26.circle.fill.hi")

	/// `26.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `26_square_hi` = SFSymbol(identifier: "26.square.hi")

	/// `26.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `26_square_fill_hi` = SFSymbol(identifier: "26.square.fill.hi")

	/// `27.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `27_circle_hi` = SFSymbol(identifier: "27.circle.hi")

	/// `27.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `27_circle_fill_hi` = SFSymbol(identifier: "27.circle.fill.hi")

	/// `27.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `27_square_hi` = SFSymbol(identifier: "27.square.hi")

	/// `27.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `27_square_fill_hi` = SFSymbol(identifier: "27.square.fill.hi")

	/// `28.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `28_circle_hi` = SFSymbol(identifier: "28.circle.hi")

	/// `28.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `28_circle_fill_hi` = SFSymbol(identifier: "28.circle.fill.hi")

	/// `28.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `28_square_hi` = SFSymbol(identifier: "28.square.hi")

	/// `28.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `28_square_fill_hi` = SFSymbol(identifier: "28.square.fill.hi")

	/// `29.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `29_circle_hi` = SFSymbol(identifier: "29.circle.hi")

	/// `29.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `29_circle_fill_hi` = SFSymbol(identifier: "29.circle.fill.hi")

	/// `29.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `29_square_hi` = SFSymbol(identifier: "29.square.hi")

	/// `29.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `29_square_fill_hi` = SFSymbol(identifier: "29.square.fill.hi")

	/// `30.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `30_circle_hi` = SFSymbol(identifier: "30.circle.hi")

	/// `30.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `30_circle_fill_hi` = SFSymbol(identifier: "30.circle.fill.hi")

	/// `30.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `30_square_hi` = SFSymbol(identifier: "30.square.hi")

	/// `30.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `30_square_fill_hi` = SFSymbol(identifier: "30.square.fill.hi")

	/// `31.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `31_circle_hi` = SFSymbol(identifier: "31.circle.hi")

	/// `31.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `31_circle_fill_hi` = SFSymbol(identifier: "31.circle.fill.hi")

	/// `31.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `31_square_hi` = SFSymbol(identifier: "31.square.hi")

	/// `31.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `31_square_fill_hi` = SFSymbol(identifier: "31.square.fill.hi")

	/// `32.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `32_circle_hi` = SFSymbol(identifier: "32.circle.hi")

	/// `32.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `32_circle_fill_hi` = SFSymbol(identifier: "32.circle.fill.hi")

	/// `32.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `32_square_hi` = SFSymbol(identifier: "32.square.hi")

	/// `32.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `32_square_fill_hi` = SFSymbol(identifier: "32.square.fill.hi")

	/// `33.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `33_circle_hi` = SFSymbol(identifier: "33.circle.hi")

	/// `33.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `33_circle_fill_hi` = SFSymbol(identifier: "33.circle.fill.hi")

	/// `33.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `33_square_hi` = SFSymbol(identifier: "33.square.hi")

	/// `33.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `33_square_fill_hi` = SFSymbol(identifier: "33.square.fill.hi")

	/// `34.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `34_circle_hi` = SFSymbol(identifier: "34.circle.hi")

	/// `34.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `34_circle_fill_hi` = SFSymbol(identifier: "34.circle.fill.hi")

	/// `34.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `34_square_hi` = SFSymbol(identifier: "34.square.hi")

	/// `34.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `34_square_fill_hi` = SFSymbol(identifier: "34.square.fill.hi")

	/// `35.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `35_circle_hi` = SFSymbol(identifier: "35.circle.hi")

	/// `35.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `35_circle_fill_hi` = SFSymbol(identifier: "35.circle.fill.hi")

	/// `35.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `35_square_hi` = SFSymbol(identifier: "35.square.hi")

	/// `35.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `35_square_fill_hi` = SFSymbol(identifier: "35.square.fill.hi")

	/// `36.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `36_circle_hi` = SFSymbol(identifier: "36.circle.hi")

	/// `36.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `36_circle_fill_hi` = SFSymbol(identifier: "36.circle.fill.hi")

	/// `36.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `36_square_hi` = SFSymbol(identifier: "36.square.hi")

	/// `36.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `36_square_fill_hi` = SFSymbol(identifier: "36.square.fill.hi")

	/// `37.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `37_circle_hi` = SFSymbol(identifier: "37.circle.hi")

	/// `37.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `37_circle_fill_hi` = SFSymbol(identifier: "37.circle.fill.hi")

	/// `37.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `37_square_hi` = SFSymbol(identifier: "37.square.hi")

	/// `37.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `37_square_fill_hi` = SFSymbol(identifier: "37.square.fill.hi")

	/// `38.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `38_circle_hi` = SFSymbol(identifier: "38.circle.hi")

	/// `38.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `38_circle_fill_hi` = SFSymbol(identifier: "38.circle.fill.hi")

	/// `38.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `38_square_hi` = SFSymbol(identifier: "38.square.hi")

	/// `38.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `38_square_fill_hi` = SFSymbol(identifier: "38.square.fill.hi")

	/// `39.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `39_circle_hi` = SFSymbol(identifier: "39.circle.hi")

	/// `39.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `39_circle_fill_hi` = SFSymbol(identifier: "39.circle.fill.hi")

	/// `39.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `39_square_hi` = SFSymbol(identifier: "39.square.hi")

	/// `39.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `39_square_fill_hi` = SFSymbol(identifier: "39.square.fill.hi")

	/// `40.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `40_circle_hi` = SFSymbol(identifier: "40.circle.hi")

	/// `40.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `40_circle_fill_hi` = SFSymbol(identifier: "40.circle.fill.hi")

	/// `40.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `40_square_hi` = SFSymbol(identifier: "40.square.hi")

	/// `40.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `40_square_fill_hi` = SFSymbol(identifier: "40.square.fill.hi")

	/// `41.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `41_circle_hi` = SFSymbol(identifier: "41.circle.hi")

	/// `41.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `41_circle_fill_hi` = SFSymbol(identifier: "41.circle.fill.hi")

	/// `41.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `41_square_hi` = SFSymbol(identifier: "41.square.hi")

	/// `41.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `41_square_fill_hi` = SFSymbol(identifier: "41.square.fill.hi")

	/// `42.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `42_circle_hi` = SFSymbol(identifier: "42.circle.hi")

	/// `42.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `42_circle_fill_hi` = SFSymbol(identifier: "42.circle.fill.hi")

	/// `42.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `42_square_hi` = SFSymbol(identifier: "42.square.hi")

	/// `42.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `42_square_fill_hi` = SFSymbol(identifier: "42.square.fill.hi")

	/// `43.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `43_circle_hi` = SFSymbol(identifier: "43.circle.hi")

	/// `43.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `43_circle_fill_hi` = SFSymbol(identifier: "43.circle.fill.hi")

	/// `43.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `43_square_hi` = SFSymbol(identifier: "43.square.hi")

	/// `43.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `43_square_fill_hi` = SFSymbol(identifier: "43.square.fill.hi")

	/// `44.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `44_circle_hi` = SFSymbol(identifier: "44.circle.hi")

	/// `44.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `44_circle_fill_hi` = SFSymbol(identifier: "44.circle.fill.hi")

	/// `44.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `44_square_hi` = SFSymbol(identifier: "44.square.hi")

	/// `44.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `44_square_fill_hi` = SFSymbol(identifier: "44.square.fill.hi")

	/// `45.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `45_circle_hi` = SFSymbol(identifier: "45.circle.hi")

	/// `45.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `45_circle_fill_hi` = SFSymbol(identifier: "45.circle.fill.hi")

	/// `45.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `45_square_hi` = SFSymbol(identifier: "45.square.hi")

	/// `45.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `45_square_fill_hi` = SFSymbol(identifier: "45.square.fill.hi")

	/// `46.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `46_circle_hi` = SFSymbol(identifier: "46.circle.hi")

	/// `46.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `46_circle_fill_hi` = SFSymbol(identifier: "46.circle.fill.hi")

	/// `46.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `46_square_hi` = SFSymbol(identifier: "46.square.hi")

	/// `46.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `46_square_fill_hi` = SFSymbol(identifier: "46.square.fill.hi")

	/// `47.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `47_circle_hi` = SFSymbol(identifier: "47.circle.hi")

	/// `47.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `47_circle_fill_hi` = SFSymbol(identifier: "47.circle.fill.hi")

	/// `47.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `47_square_hi` = SFSymbol(identifier: "47.square.hi")

	/// `47.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `47_square_fill_hi` = SFSymbol(identifier: "47.square.fill.hi")

	/// `48.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `48_circle_hi` = SFSymbol(identifier: "48.circle.hi")

	/// `48.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `48_circle_fill_hi` = SFSymbol(identifier: "48.circle.fill.hi")

	/// `48.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `48_square_hi` = SFSymbol(identifier: "48.square.hi")

	/// `48.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `48_square_fill_hi` = SFSymbol(identifier: "48.square.fill.hi")

	/// `49.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `49_circle_hi` = SFSymbol(identifier: "49.circle.hi")

	/// `49.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `49_circle_fill_hi` = SFSymbol(identifier: "49.circle.fill.hi")

	/// `49.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `49_square_hi` = SFSymbol(identifier: "49.square.hi")

	/// `49.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `49_square_fill_hi` = SFSymbol(identifier: "49.square.fill.hi")

	/// `50.circle.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `variable`
	static public let `50_circle_hi` = SFSymbol(identifier: "50.circle.hi")

	/// `50.circle.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `50_circle_fill_hi` = SFSymbol(identifier: "50.circle.fill.hi")

	/// `50.square.hi`
	///
	/// - categories:
	///   - `indices`
	static public let `50_square_hi` = SFSymbol(identifier: "50.square.hi")

	/// `50.square.fill.hi`
	///
	/// - categories:
	///   - `indices`
	///   - `multicolor`
	static public let `50_square_fill_hi` = SFSymbol(identifier: "50.square.fill.hi")
}