//
//  SFSymbol+Symbols.2022.1.swift
//
//  Automatically generated by sf-symbol-member-gen
//  Do not edit directly!
//  swift-format-ignore-file

extension SFSymbol {
	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let backpack_circle = SFSymbol(rawValue: "backpack.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let backpack_circle_fill = SFSymbol(rawValue: "backpack.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let person_crop_circle_dashed = SFSymbol(rawValue: "person.crop.circle.dashed")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let figure_run_square_stack = SFSymbol(rawValue: "figure.run.square.stack")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let figure_run_square_stack_fill = SFSymbol(rawValue: "figure.run.square.stack.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let lane = SFSymbol(rawValue: "lane")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `1_lane` = SFSymbol(rawValue: "1.lane")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `2_lane` = SFSymbol(rawValue: "2.lane")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `3_lane` = SFSymbol(rawValue: "3.lane")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `4_lane` = SFSymbol(rawValue: "4.lane")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `5_lane` = SFSymbol(rawValue: "5.lane")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `6_lane` = SFSymbol(rawValue: "6.lane")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `7_lane` = SFSymbol(rawValue: "7.lane")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `8_lane` = SFSymbol(rawValue: "8.lane")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `9_lane` = SFSymbol(rawValue: "9.lane")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `10_lane` = SFSymbol(rawValue: "10.lane")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `11_lane` = SFSymbol(rawValue: "11.lane")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `12_lane` = SFSymbol(rawValue: "12.lane")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let snowflake_slash = SFSymbol(rawValue: "snowflake.slash")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let play_square_stack = SFSymbol(rawValue: "play.square.stack")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let play_square_stack_fill = SFSymbol(rawValue: "play.square.stack.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let sos = SFSymbol(rawValue: "sos")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let sos_circle = SFSymbol(rawValue: "sos.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let sos_circle_fill = SFSymbol(rawValue: "sos.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let bolt_trianglebadge_exclamationmark = SFSymbol(rawValue: "bolt.trianglebadge.exclamationmark")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let bolt_trianglebadge_exclamationmark_fill = SFSymbol(rawValue: "bolt.trianglebadge.exclamationmark.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let handbag = SFSymbol(rawValue: "handbag")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let handbag_fill = SFSymbol(rawValue: "handbag.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let cross_case_circle = SFSymbol(rawValue: "cross.case.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let cross_case_circle_fill = SFSymbol(rawValue: "cross.case.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let suitcase_rolling = SFSymbol(rawValue: "suitcase.rolling")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let suitcase_rolling_fill = SFSymbol(rawValue: "suitcase.rolling.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let toilet_circle = SFSymbol(rawValue: "toilet.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let toilet_circle_fill = SFSymbol(rawValue: "toilet.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let tent_circle = SFSymbol(rawValue: "tent.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let tent_circle_fill = SFSymbol(rawValue: "tent.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let tent_2 = SFSymbol(rawValue: "tent.2")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let tent_2_fill = SFSymbol(rawValue: "tent.2.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let tent_2_circle = SFSymbol(rawValue: "tent.2.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let tent_2_circle_fill = SFSymbol(rawValue: "tent.2.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let house_lodge = SFSymbol(rawValue: "house.lodge")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let house_lodge_fill = SFSymbol(rawValue: "house.lodge.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let house_lodge_circle = SFSymbol(rawValue: "house.lodge.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let house_lodge_circle_fill = SFSymbol(rawValue: "house.lodge.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let house_and_flag = SFSymbol(rawValue: "house.and.flag")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let house_and_flag_fill = SFSymbol(rawValue: "house.and.flag.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let house_and_flag_circle = SFSymbol(rawValue: "house.and.flag.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let house_and_flag_circle_fill = SFSymbol(rawValue: "house.and.flag.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let signpost_left_circle = SFSymbol(rawValue: "signpost.left.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let signpost_left_circle_fill = SFSymbol(rawValue: "signpost.left.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let signpost_right_circle = SFSymbol(rawValue: "signpost.right.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let signpost_right_circle_fill = SFSymbol(rawValue: "signpost.right.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let signpost_right_and_left = SFSymbol(rawValue: "signpost.right.and.left")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let signpost_right_and_left_fill = SFSymbol(rawValue: "signpost.right.and.left.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let signpost_right_and_left_circle = SFSymbol(rawValue: "signpost.right.and.left.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let signpost_right_and_left_circle_fill = SFSymbol(rawValue: "signpost.right.and.left.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let signpost_and_arrowtriangle_up = SFSymbol(rawValue: "signpost.and.arrowtriangle.up")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let signpost_and_arrowtriangle_up_fill = SFSymbol(rawValue: "signpost.and.arrowtriangle.up.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let signpost_and_arrowtriangle_up_circle = SFSymbol(rawValue: "signpost.and.arrowtriangle.up.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let signpost_and_arrowtriangle_up_circle_fill = SFSymbol(rawValue: "signpost.and.arrowtriangle.up.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let mountain_2 = SFSymbol(rawValue: "mountain.2")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let mountain_2_fill = SFSymbol(rawValue: "mountain.2.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let mountain_2_circle = SFSymbol(rawValue: "mountain.2.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let mountain_2_circle_fill = SFSymbol(rawValue: "mountain.2.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let lock_open_rotation = SFSymbol(rawValue: "lock.open.rotation")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let key_radiowaves_forward = SFSymbol(rawValue: "key.radiowaves.forward")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let key_radiowaves_forward_fill = SFSymbol(rawValue: "key.radiowaves.forward.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let key_horizontal = SFSymbol(rawValue: "key.horizontal")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let key_horizontal_fill = SFSymbol(rawValue: "key.horizontal.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let questionmark_key_filled = SFSymbol(rawValue: "questionmark.key.filled")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let laptopcomputer_slash = SFSymbol(rawValue: "laptopcomputer.slash")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let macbook_and_iphone = SFSymbol(rawValue: "macbook.and.iphone")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let macbook_and_ipad = SFSymbol(rawValue: "macbook.and.ipad")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen1 = SFSymbol(rawValue: "iphone.gen1")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen1_circle = SFSymbol(rawValue: "iphone.gen1.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen1_circle_fill = SFSymbol(rawValue: "iphone.gen1.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen1_landscape = SFSymbol(rawValue: "iphone.gen1.landscape")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen1_radiowaves_left_and_right = SFSymbol(rawValue: "iphone.gen1.radiowaves.left.and.right")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen1_radiowaves_left_and_right_circle = SFSymbol(rawValue: "iphone.gen1.radiowaves.left.and.right.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen1_radiowaves_left_and_right_circle_fill = SFSymbol(rawValue: "iphone.gen1.radiowaves.left.and.right.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen1_slash = SFSymbol(rawValue: "iphone.gen1.slash")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen1_slash_circle = SFSymbol(rawValue: "iphone.gen1.slash.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen1_slash_circle_fill = SFSymbol(rawValue: "iphone.gen1.slash.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen1_badge_play = SFSymbol(rawValue: "iphone.gen1.badge.play")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen2 = SFSymbol(rawValue: "iphone.gen2")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen2_circle = SFSymbol(rawValue: "iphone.gen2.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen2_circle_fill = SFSymbol(rawValue: "iphone.gen2.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen2_landscape = SFSymbol(rawValue: "iphone.gen2.landscape")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen2_radiowaves_left_and_right = SFSymbol(rawValue: "iphone.gen2.radiowaves.left.and.right")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen2_radiowaves_left_and_right_circle = SFSymbol(rawValue: "iphone.gen2.radiowaves.left.and.right.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen2_radiowaves_left_and_right_circle_fill = SFSymbol(rawValue: "iphone.gen2.radiowaves.left.and.right.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen2_slash = SFSymbol(rawValue: "iphone.gen2.slash")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen2_slash_circle = SFSymbol(rawValue: "iphone.gen2.slash.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen2_slash_circle_fill = SFSymbol(rawValue: "iphone.gen2.slash.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen2_badge_play = SFSymbol(rawValue: "iphone.gen2.badge.play")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen3 = SFSymbol(rawValue: "iphone.gen3")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen3_circle = SFSymbol(rawValue: "iphone.gen3.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen3_circle_fill = SFSymbol(rawValue: "iphone.gen3.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen3_landscape = SFSymbol(rawValue: "iphone.gen3.landscape")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen3_radiowaves_left_and_right = SFSymbol(rawValue: "iphone.gen3.radiowaves.left.and.right")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen3_radiowaves_left_and_right_circle = SFSymbol(rawValue: "iphone.gen3.radiowaves.left.and.right.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen3_radiowaves_left_and_right_circle_fill = SFSymbol(rawValue: "iphone.gen3.radiowaves.left.and.right.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen3_slash = SFSymbol(rawValue: "iphone.gen3.slash")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen3_slash_circle = SFSymbol(rawValue: "iphone.gen3.slash.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen3_slash_circle_fill = SFSymbol(rawValue: "iphone.gen3.slash.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let iphone_gen3_badge_play = SFSymbol(rawValue: "iphone.gen3.badge.play")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let ipad_gen1 = SFSymbol(rawValue: "ipad.gen1")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let ipad_gen1_badge_play = SFSymbol(rawValue: "ipad.gen1.badge.play")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let ipad_gen1_landscape = SFSymbol(rawValue: "ipad.gen1.landscape")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let ipad_gen1_landscape_badge_play = SFSymbol(rawValue: "ipad.gen1.landscape.badge.play")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let ipad_gen2 = SFSymbol(rawValue: "ipad.gen2")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let ipad_gen2_badge_play = SFSymbol(rawValue: "ipad.gen2.badge.play")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let ipad_gen2_landscape = SFSymbol(rawValue: "ipad.gen2.landscape")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let ipad_gen2_landscape_badge_play = SFSymbol(rawValue: "ipad.gen2.landscape.badge.play")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_front_waves_up = SFSymbol(rawValue: "car.front.waves.up")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_front_waves_up_fill = SFSymbol(rawValue: "car.front.waves.up.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_rear = SFSymbol(rawValue: "car.rear")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_rear_fill = SFSymbol(rawValue: "car.rear.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_rear_waves_up = SFSymbol(rawValue: "car.rear.waves.up")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_rear_waves_up_fill = SFSymbol(rawValue: "car.rear.waves.up.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_rear_and_tire_marks = SFSymbol(rawValue: "car.rear.and.tire.marks")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_rear_and_tire_marks_slash = SFSymbol(rawValue: "car.rear.and.tire.marks.slash")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let sailboat_circle = SFSymbol(rawValue: "sailboat.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let sailboat_circle_fill = SFSymbol(rawValue: "sailboat.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let stroller = SFSymbol(rawValue: "stroller")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let stroller_fill = SFSymbol(rawValue: "stroller.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let engine_combustion = SFSymbol(rawValue: "engine.combustion")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let engine_combustion_fill = SFSymbol(rawValue: "engine.combustion.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let headlight_fog = SFSymbol(rawValue: "headlight.fog")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let headlight_fog_fill = SFSymbol(rawValue: "headlight.fog.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let taillight_fog = SFSymbol(rawValue: "taillight.fog")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let taillight_fog_fill = SFSymbol(rawValue: "taillight.fog.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let headlight_daytime = SFSymbol(rawValue: "headlight.daytime")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let headlight_daytime_fill = SFSymbol(rawValue: "headlight.daytime.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let light_overhead_right = SFSymbol(rawValue: "light.overhead.right")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let light_overhead_right_fill = SFSymbol(rawValue: "light.overhead.right.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let light_overhead_left = SFSymbol(rawValue: "light.overhead.left")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let light_overhead_left_fill = SFSymbol(rawValue: "light.overhead.left.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let glowplug = SFSymbol(rawValue: "glowplug")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let info_windshield = SFSymbol(rawValue: "info.windshield")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let heat_element_windshield = SFSymbol(rawValue: "heat.element.windshield")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let windshield_front_and_spray = SFSymbol(rawValue: "windshield.front.and.spray")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let windshield_front_and_wiper_and_spray = SFSymbol(rawValue: "windshield.front.and.wiper.and.spray")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let windshield_front_and_fluid_and_spray = SFSymbol(rawValue: "windshield.front.and.fluid.and.spray")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let windshield_front_and_wiper_intermittent = SFSymbol(rawValue: "windshield.front.and.wiper.intermittent")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let windshield_front_and_heat_waves = SFSymbol(rawValue: "windshield.front.and.heat.waves")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let windshield_front_and_wiper_exclamationmark = SFSymbol(rawValue: "windshield.front.and.wiper.exclamationmark")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let windshield_rear_and_spray = SFSymbol(rawValue: "windshield.rear.and.spray")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let windshield_rear_and_wiper_and_spray = SFSymbol(rawValue: "windshield.rear.and.wiper.and.spray")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let windshield_rear_and_fluid_and_spray = SFSymbol(rawValue: "windshield.rear.and.fluid.and.spray")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let windshield_rear_and_wiper_intermittent = SFSymbol(rawValue: "windshield.rear.and.wiper.intermittent")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let windshield_rear_and_wiper_and_drop = SFSymbol(rawValue: "windshield.rear.and.wiper.and.drop")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let windshield_rear_and_heat_waves = SFSymbol(rawValue: "windshield.rear.and.heat.waves")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let windshield_rear_and_wiper_exclamationmark = SFSymbol(rawValue: "windshield.rear.and.wiper.exclamationmark")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let mirror_side_left_and_heat_waves = SFSymbol(rawValue: "mirror.side.left.and.heat.waves")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let mirror_side_right_and_heat_waves = SFSymbol(rawValue: "mirror.side.right.and.heat.waves")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let mirror_side_left_and_arrow_turn_down_right = SFSymbol(rawValue: "mirror.side.left.and.arrow.turn.down.right")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let mirror_side_right_and_arrow_turn_down_left = SFSymbol(rawValue: "mirror.side.right.and.arrow.turn.down.left")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `1_brakesignal` = SFSymbol(rawValue: "1.brakesignal")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `2_brakesignal` = SFSymbol(rawValue: "2.brakesignal")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let abs_brakesignal_slash = SFSymbol(rawValue: "abs.brakesignal.slash")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let hand_raised_brakesignal = SFSymbol(rawValue: "hand.raised.brakesignal")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let hand_raised_brakesignal_slash = SFSymbol(rawValue: "hand.raised.brakesignal.slash")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let retarder_brakesignal = SFSymbol(rawValue: "retarder.brakesignal")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let transmission = SFSymbol(rawValue: "transmission")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let exclamationmark_transmission = SFSymbol(rawValue: "exclamationmark.transmission")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let thermometer_transmission = SFSymbol(rawValue: "thermometer.transmission")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let fluid_transmission = SFSymbol(rawValue: "fluid.transmission")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let oilcan = SFSymbol(rawValue: "oilcan")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let oilcan_fill = SFSymbol(rawValue: "oilcan.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let figure_seated_seatbelt = SFSymbol(rawValue: "figure.seated.seatbelt")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let figure_seated_seatbelt_and_airbag_on = SFSymbol(rawValue: "figure.seated.seatbelt.and.airbag.on")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let figure_seated_seatbelt_and_airbag_off = SFSymbol(rawValue: "figure.seated.seatbelt.and.airbag.off")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let hazardsign = SFSymbol(rawValue: "hazardsign")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let hazardsign_fill = SFSymbol(rawValue: "hazardsign.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let wrongwaysign = SFSymbol(rawValue: "wrongwaysign")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let wrongwaysign_fill = SFSymbol(rawValue: "wrongwaysign.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let thermometer_and_liquid_waves = SFSymbol(rawValue: "thermometer.and.liquid.waves")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let steeringwheel = SFSymbol(rawValue: "steeringwheel")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let steeringwheel_slash = SFSymbol(rawValue: "steeringwheel.slash")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let steeringwheel_and_heat_waves = SFSymbol(rawValue: "steeringwheel.and.heat.waves")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let steeringwheel_exclamationmark = SFSymbol(rawValue: "steeringwheel.exclamationmark")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let steeringwheel_and_key = SFSymbol(rawValue: "steeringwheel.and.key")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_side = SFSymbol(rawValue: "car.side")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_side_fill = SFSymbol(rawValue: "car.side.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_side_front_open = SFSymbol(rawValue: "car.side.front.open")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_side_front_open_fill = SFSymbol(rawValue: "car.side.front.open.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_side_rear_open = SFSymbol(rawValue: "car.side.rear.open")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_side_rear_open_fill = SFSymbol(rawValue: "car.side.rear.open.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_side_air_circulate = SFSymbol(rawValue: "car.side.air.circulate")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_side_air_circulate_fill = SFSymbol(rawValue: "car.side.air.circulate.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_side_air_fresh = SFSymbol(rawValue: "car.side.air.fresh")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_side_air_fresh_fill = SFSymbol(rawValue: "car.side.air.fresh.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_side_and_exclamationmark = SFSymbol(rawValue: "car.side.and.exclamationmark")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_side_and_exclamationmark_fill = SFSymbol(rawValue: "car.side.and.exclamationmark.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_side_arrowtriangle_up_arrowtriangle_down = SFSymbol(rawValue: "car.side.arrowtriangle.up.arrowtriangle.down")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_side_arrowtriangle_up_arrowtriangle_down_fill = SFSymbol(rawValue: "car.side.arrowtriangle.up.arrowtriangle.down.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_side_arrowtriangle_up = SFSymbol(rawValue: "car.side.arrowtriangle.up")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_side_arrowtriangle_up_fill = SFSymbol(rawValue: "car.side.arrowtriangle.up.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_side_arrowtriangle_down = SFSymbol(rawValue: "car.side.arrowtriangle.down")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_side_arrowtriangle_down_fill = SFSymbol(rawValue: "car.side.arrowtriangle.down.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let suv_side = SFSymbol(rawValue: "suv.side")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let suv_side_fill = SFSymbol(rawValue: "suv.side.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let suv_side_front_open = SFSymbol(rawValue: "suv.side.front.open")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let suv_side_front_open_fill = SFSymbol(rawValue: "suv.side.front.open.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let suv_side_rear_open = SFSymbol(rawValue: "suv.side.rear.open")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let suv_side_rear_open_fill = SFSymbol(rawValue: "suv.side.rear.open.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let suv_side_air_circulate = SFSymbol(rawValue: "suv.side.air.circulate")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let suv_side_air_circulate_fill = SFSymbol(rawValue: "suv.side.air.circulate.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let suv_side_air_fresh = SFSymbol(rawValue: "suv.side.air.fresh")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let suv_side_air_fresh_fill = SFSymbol(rawValue: "suv.side.air.fresh.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let suv_side_and_exclamationmark = SFSymbol(rawValue: "suv.side.and.exclamationmark")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let suv_side_and_exclamationmark_fill = SFSymbol(rawValue: "suv.side.and.exclamationmark.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let suv_side_arrowtriangle_up_arrowtriangle_down = SFSymbol(rawValue: "suv.side.arrowtriangle.up.arrowtriangle.down")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let suv_side_arrowtriangle_up_arrowtriangle_down_fill = SFSymbol(rawValue: "suv.side.arrowtriangle.up.arrowtriangle.down.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let suv_side_arrowtriangle_up = SFSymbol(rawValue: "suv.side.arrowtriangle.up")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let suv_side_arrowtriangle_up_fill = SFSymbol(rawValue: "suv.side.arrowtriangle.up.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let suv_side_arrowtriangle_down = SFSymbol(rawValue: "suv.side.arrowtriangle.down")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let suv_side_arrowtriangle_down_fill = SFSymbol(rawValue: "suv.side.arrowtriangle.down.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_left_open = SFSymbol(rawValue: "car.top.door.front.left.open")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_left_open_fill = SFSymbol(rawValue: "car.top.door.front.left.open.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_right_open = SFSymbol(rawValue: "car.top.door.front.right.open")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_right_open_fill = SFSymbol(rawValue: "car.top.door.front.right.open.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_rear_left_open = SFSymbol(rawValue: "car.top.door.rear.left.open")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_rear_left_open_fill = SFSymbol(rawValue: "car.top.door.rear.left.open.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_rear_right_open = SFSymbol(rawValue: "car.top.door.rear.right.open")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_rear_right_open_fill = SFSymbol(rawValue: "car.top.door.rear.right.open.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_left_and_front_right_open = SFSymbol(rawValue: "car.top.door.front.left.and.front.right.open")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_left_and_front_right_open_fill = SFSymbol(rawValue: "car.top.door.front.left.and.front.right.open.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_rear_left_and_rear_right_open = SFSymbol(rawValue: "car.top.door.rear.left.and.rear.right.open")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_rear_left_and_rear_right_open_fill = SFSymbol(rawValue: "car.top.door.rear.left.and.rear.right.open.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_left_and_rear_left_open = SFSymbol(rawValue: "car.top.door.front.left.and.rear.left.open")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_left_and_rear_left_open_fill = SFSymbol(rawValue: "car.top.door.front.left.and.rear.left.open.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_right_and_rear_right_open = SFSymbol(rawValue: "car.top.door.front.right.and.rear.right.open")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_right_and_rear_right_open_fill = SFSymbol(rawValue: "car.top.door.front.right.and.rear.right.open.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_left_and_rear_right_open = SFSymbol(rawValue: "car.top.door.front.left.and.rear.right.open")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_left_and_rear_right_open_fill = SFSymbol(rawValue: "car.top.door.front.left.and.rear.right.open.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_right_and_rear_left_open = SFSymbol(rawValue: "car.top.door.front.right.and.rear.left.open")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_right_and_rear_left_open_fill = SFSymbol(rawValue: "car.top.door.front.right.and.rear.left.open.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_left_and_front_right_and_rear_left_open = SFSymbol(rawValue: "car.top.door.front.left.and.front.right.and.rear.left.open")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_left_and_front_right_and_rear_left_open_fill = SFSymbol(rawValue: "car.top.door.front.left.and.front.right.and.rear.left.open.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_left_and_front_right_and_rear_right_open = SFSymbol(rawValue: "car.top.door.front.left.and.front.right.and.rear.right.open")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_left_and_front_right_and_rear_right_open_fill = SFSymbol(rawValue: "car.top.door.front.left.and.front.right.and.rear.right.open.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_left_and_rear_left_and_rear_right_open = SFSymbol(rawValue: "car.top.door.front.left.and.rear.left.and.rear.right.open")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_left_and_rear_left_and_rear_right_open_fill = SFSymbol(rawValue: "car.top.door.front.left.and.rear.left.and.rear.right.open.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_right_and_rear_left_and_rear_right_open = SFSymbol(rawValue: "car.top.door.front.right.and.rear.left.and.rear.right.open")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_right_and_rear_left_and_rear_right_open_fill = SFSymbol(rawValue: "car.top.door.front.right.and.rear.left.and.rear.right.open.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_left_and_front_right_and_rear_left_and_rear_right_open = SFSymbol(rawValue: "car.top.door.front.left.and.front.right.and.rear.left.and.rear.right.open")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_door_front_left_and_front_right_and_rear_left_and_rear_right_open_fill = SFSymbol(rawValue: "car.top.door.front.left.and.front.right.and.rear.left.and.rear.right.open.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_radiowaves_rear_right = SFSymbol(rawValue: "car.top.radiowaves.rear.right")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_radiowaves_rear_right_fill = SFSymbol(rawValue: "car.top.radiowaves.rear.right.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_radiowaves_rear_left = SFSymbol(rawValue: "car.top.radiowaves.rear.left")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_radiowaves_rear_left_fill = SFSymbol(rawValue: "car.top.radiowaves.rear.left.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_radiowaves_front = SFSymbol(rawValue: "car.top.radiowaves.front")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_radiowaves_front_fill = SFSymbol(rawValue: "car.top.radiowaves.front.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_radiowaves_rear = SFSymbol(rawValue: "car.top.radiowaves.rear")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_radiowaves_rear_fill = SFSymbol(rawValue: "car.top.radiowaves.rear.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_radiowaves_rear_left_and_rear_right = SFSymbol(rawValue: "car.top.radiowaves.rear.left.and.rear.right")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_radiowaves_rear_left_and_rear_right_fill = SFSymbol(rawValue: "car.top.radiowaves.rear.left.and.rear.right.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_lane_dashed_departure_left = SFSymbol(rawValue: "car.top.lane.dashed.departure.left")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_lane_dashed_departure_left_fill = SFSymbol(rawValue: "car.top.lane.dashed.departure.left.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_lane_dashed_departure_right = SFSymbol(rawValue: "car.top.lane.dashed.departure.right")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_lane_dashed_departure_right_fill = SFSymbol(rawValue: "car.top.lane.dashed.departure.right.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_lane_dashed_arrowtriangle_inward = SFSymbol(rawValue: "car.top.lane.dashed.arrowtriangle.inward")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_lane_dashed_arrowtriangle_inward_fill = SFSymbol(rawValue: "car.top.lane.dashed.arrowtriangle.inward.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_lane_dashed_badge_steeringwheel = SFSymbol(rawValue: "car.top.lane.dashed.badge.steeringwheel")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_top_lane_dashed_badge_steeringwheel_fill = SFSymbol(rawValue: "car.top.lane.dashed.badge.steeringwheel.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let autostartstop = SFSymbol(rawValue: "autostartstop")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let autostartstop_slash = SFSymbol(rawValue: "autostartstop.slash")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let autostartstop_trianglebadge_exclamationmark = SFSymbol(rawValue: "autostartstop.trianglebadge.exclamationmark")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let batteryblock = SFSymbol(rawValue: "batteryblock")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let batteryblock_fill = SFSymbol(rawValue: "batteryblock.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let batteryblock_slash = SFSymbol(rawValue: "batteryblock.slash")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let batteryblock_slash_fill = SFSymbol(rawValue: "batteryblock.slash.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let minus_plus_batteryblock_slash = SFSymbol(rawValue: "minus.plus.batteryblock.slash")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let minus_plus_batteryblock_slash_fill = SFSymbol(rawValue: "minus.plus.batteryblock.slash.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let minus_plus_and_fluid_batteryblock = SFSymbol(rawValue: "minus.plus.and.fluid.batteryblock")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let minus_plus_batteryblock_exclamationmark = SFSymbol(rawValue: "minus.plus.batteryblock.exclamationmark")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let minus_plus_batteryblock_exclamationmark_fill = SFSymbol(rawValue: "minus.plus.batteryblock.exclamationmark.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let minus_plus_batteryblock_stack = SFSymbol(rawValue: "minus.plus.batteryblock.stack")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let minus_plus_batteryblock_stack_fill = SFSymbol(rawValue: "minus.plus.batteryblock.stack.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let minus_plus_batteryblock_stack_exclamationmark = SFSymbol(rawValue: "minus.plus.batteryblock.stack.exclamationmark")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let minus_plus_batteryblock_stack_exclamationmark_fill = SFSymbol(rawValue: "minus.plus.batteryblock.stack.exclamationmark.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let road_lane_arrowtriangle_2_inward = SFSymbol(rawValue: "road.lane.arrowtriangle.2.inward")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_rear_road_lane = SFSymbol(rawValue: "car.rear.road.lane")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let car_rear_road_lane_dashed = SFSymbol(rawValue: "car.rear.road.lane.dashed")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let snowflake_road_lane = SFSymbol(rawValue: "snowflake.road.lane")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let snowflake_road_lane_dashed = SFSymbol(rawValue: "snowflake.road.lane.dashed")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let steeringwheel_road_lane = SFSymbol(rawValue: "steeringwheel.road.lane")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let steeringwheel_road_lane_dashed = SFSymbol(rawValue: "steeringwheel.road.lane.dashed")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let abs = SFSymbol(rawValue: "abs")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let abs_circle = SFSymbol(rawValue: "abs.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let abs_circle_fill = SFSymbol(rawValue: "abs.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let mph = SFSymbol(rawValue: "mph")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let mph_circle = SFSymbol(rawValue: "mph.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let mph_circle_fill = SFSymbol(rawValue: "mph.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let kph = SFSymbol(rawValue: "kph")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let kph_circle = SFSymbol(rawValue: "kph.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let kph_circle_fill = SFSymbol(rawValue: "kph.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let fish_circle = SFSymbol(rawValue: "fish.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let fish_circle_fill = SFSymbol(rawValue: "fish.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let tree = SFSymbol(rawValue: "tree")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let tree_fill = SFSymbol(rawValue: "tree.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let tree_circle = SFSymbol(rawValue: "tree.circle")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let tree_circle_fill = SFSymbol(rawValue: "tree.circle.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let hand_raised_app = SFSymbol(rawValue: "hand.raised.app")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let hand_raised_app_fill = SFSymbol(rawValue: "hand.raised.app.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let ellipsis_viewfinder = SFSymbol(rawValue: "ellipsis.viewfinder")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let mug = SFSymbol(rawValue: "mug")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let mug_fill = SFSymbol(rawValue: "mug.fill")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let chart_dots_scatter = SFSymbol(rawValue: "chart.dots.scatter")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `0_circle_ar` = SFSymbol(rawValue: "0.circle.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `0_circle_fill_ar` = SFSymbol(rawValue: "0.circle.fill.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `0_square_ar` = SFSymbol(rawValue: "0.square.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `0_square_fill_ar` = SFSymbol(rawValue: "0.square.fill.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `1_circle_ar` = SFSymbol(rawValue: "1.circle.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `1_circle_fill_ar` = SFSymbol(rawValue: "1.circle.fill.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `1_square_ar` = SFSymbol(rawValue: "1.square.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `1_square_fill_ar` = SFSymbol(rawValue: "1.square.fill.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `2_circle_ar` = SFSymbol(rawValue: "2.circle.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `2_circle_fill_ar` = SFSymbol(rawValue: "2.circle.fill.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `2_square_ar` = SFSymbol(rawValue: "2.square.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `2_square_fill_ar` = SFSymbol(rawValue: "2.square.fill.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `3_circle_ar` = SFSymbol(rawValue: "3.circle.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `3_circle_fill_ar` = SFSymbol(rawValue: "3.circle.fill.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `3_square_ar` = SFSymbol(rawValue: "3.square.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `3_square_fill_ar` = SFSymbol(rawValue: "3.square.fill.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `4_circle_ar` = SFSymbol(rawValue: "4.circle.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `4_circle_fill_ar` = SFSymbol(rawValue: "4.circle.fill.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `4_square_ar` = SFSymbol(rawValue: "4.square.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `4_square_fill_ar` = SFSymbol(rawValue: "4.square.fill.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `5_circle_ar` = SFSymbol(rawValue: "5.circle.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `5_circle_fill_ar` = SFSymbol(rawValue: "5.circle.fill.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `5_square_ar` = SFSymbol(rawValue: "5.square.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `5_square_fill_ar` = SFSymbol(rawValue: "5.square.fill.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `6_circle_ar` = SFSymbol(rawValue: "6.circle.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `6_circle_fill_ar` = SFSymbol(rawValue: "6.circle.fill.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `6_square_ar` = SFSymbol(rawValue: "6.square.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `6_square_fill_ar` = SFSymbol(rawValue: "6.square.fill.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `7_circle_ar` = SFSymbol(rawValue: "7.circle.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `7_circle_fill_ar` = SFSymbol(rawValue: "7.circle.fill.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `7_square_ar` = SFSymbol(rawValue: "7.square.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `7_square_fill_ar` = SFSymbol(rawValue: "7.square.fill.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `8_circle_ar` = SFSymbol(rawValue: "8.circle.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `8_circle_fill_ar` = SFSymbol(rawValue: "8.circle.fill.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `8_square_ar` = SFSymbol(rawValue: "8.square.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `8_square_fill_ar` = SFSymbol(rawValue: "8.square.fill.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `9_circle_ar` = SFSymbol(rawValue: "9.circle.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `9_circle_fill_ar` = SFSymbol(rawValue: "9.circle.fill.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `9_square_ar` = SFSymbol(rawValue: "9.square.ar")

	@available(watchOS 9.1, macOS 13.0, tvOS 16.1, visionOS 1.0, iOS 16.1, *)
	static public let `9_square_fill_ar` = SFSymbol(rawValue: "9.square.fill.ar")
}