//
//  SFSymbols.2020.swift
//
//  Automatically generated by sf-symbol-member-gen
//  Do not edit directly!
//  swift-format-ignore-file

@_documentation(visibility: internal)
@available(iOS 14.0, macOS 11.0, tvOS 14.0, visionOS 1.0, watchOS 7.0, *)
extension SFSymbol {
	static public let rectangle_and_pencil_and_ellipsis = SFSymbol(identifier: "rectangle.and.pencil.and.ellipsis")

	static public let rectangle_and_pencil_and_ellipsis_rtl = SFSymbol(identifier: "rectangle.and.pencil.and.ellipsis.rtl")

	static public let scribble_variable = SFSymbol(identifier: "scribble.variable")

	static public let highlighter = SFSymbol(identifier: "highlighter")

	static public let pencil_tip_crop_circle_badge_arrow_forward = SFSymbol(identifier: "pencil.tip.crop.circle.badge.arrow.forward")

	static public let folder_badge_questionmark = SFSymbol(identifier: "folder.badge.questionmark")

	static public let folder_fill_badge_questionmark = SFSymbol(identifier: "folder.fill.badge.questionmark")

	static public let folder_badge_questionmark_ar = SFSymbol(identifier: "folder.badge.questionmark.ar")

	static public let folder_fill_badge_questionmark_ar = SFSymbol(identifier: "folder.fill.badge.questionmark.ar")

	static public let square_grid_3x1_folder_badge_plus = SFSymbol(identifier: "square.grid.3x1.folder.badge.plus")

	static public let square_grid_3x1_folder_fill_badge_plus = SFSymbol(identifier: "square.grid.3x1.folder.fill.badge.plus")

	static public let plus_rectangle_on_folder = SFSymbol(identifier: "plus.rectangle.on.folder")

	static public let questionmark_folder = SFSymbol(identifier: "questionmark.folder")

	static public let questionmark_folder_fill = SFSymbol(identifier: "questionmark.folder.fill")

	static public let questionmark_folder_ar = SFSymbol(identifier: "questionmark.folder.ar")

	static public let questionmark_folder_fill_ar = SFSymbol(identifier: "questionmark.folder.fill.ar")

	static public let paperplane_circle = SFSymbol(identifier: "paperplane.circle")

	static public let paperplane_circle_fill = SFSymbol(identifier: "paperplane.circle.fill")

	static public let tray_circle = SFSymbol(identifier: "tray.circle")

	static public let tray_circle_fill = SFSymbol(identifier: "tray.circle.fill")

	static public let externaldrive = SFSymbol(identifier: "externaldrive")

	static public let externaldrive_fill = SFSymbol(identifier: "externaldrive.fill")

	static public let externaldrive_badge_plus = SFSymbol(identifier: "externaldrive.badge.plus")

	static public let externaldrive_fill_badge_plus = SFSymbol(identifier: "externaldrive.fill.badge.plus")

	static public let externaldrive_badge_minus = SFSymbol(identifier: "externaldrive.badge.minus")

	static public let externaldrive_fill_badge_minus = SFSymbol(identifier: "externaldrive.fill.badge.minus")

	static public let externaldrive_badge_checkmark = SFSymbol(identifier: "externaldrive.badge.checkmark")

	static public let externaldrive_fill_badge_checkmark = SFSymbol(identifier: "externaldrive.fill.badge.checkmark")

	static public let externaldrive_badge_xmark = SFSymbol(identifier: "externaldrive.badge.xmark")

	static public let externaldrive_fill_badge_xmark = SFSymbol(identifier: "externaldrive.fill.badge.xmark")

	static public let externaldrive_badge_person_crop = SFSymbol(identifier: "externaldrive.badge.person.crop")

	static public let externaldrive_fill_badge_person_crop = SFSymbol(identifier: "externaldrive.fill.badge.person.crop")

	static public let externaldrive_badge_wifi = SFSymbol(identifier: "externaldrive.badge.wifi")

	static public let externaldrive_fill_badge_wifi = SFSymbol(identifier: "externaldrive.fill.badge.wifi")

	static public let externaldrive_badge_icloud = SFSymbol(identifier: "externaldrive.badge.icloud")

	static public let externaldrive_fill_badge_icloud = SFSymbol(identifier: "externaldrive.fill.badge.icloud")

	static public let externaldrive_badge_timemachine = SFSymbol(identifier: "externaldrive.badge.timemachine")

	static public let externaldrive_fill_badge_timemachine = SFSymbol(identifier: "externaldrive.fill.badge.timemachine")

	static public let internaldrive = SFSymbol(identifier: "internaldrive")

	static public let internaldrive_fill = SFSymbol(identifier: "internaldrive.fill")

	static public let opticaldiscdrive = SFSymbol(identifier: "opticaldiscdrive")

	static public let opticaldiscdrive_fill = SFSymbol(identifier: "opticaldiscdrive.fill")

	static public let externaldrive_connected_to_line_below = SFSymbol(identifier: "externaldrive.connected.to.line.below")

	static public let externaldrive_connected_to_line_below_fill = SFSymbol(identifier: "externaldrive.connected.to.line.below.fill")

	static public let archivebox_circle = SFSymbol(identifier: "archivebox.circle")

	static public let archivebox_circle_fill = SFSymbol(identifier: "archivebox.circle.fill")

	static public let xmark_bin = SFSymbol(identifier: "xmark.bin")

	static public let xmark_bin_fill = SFSymbol(identifier: "xmark.bin.fill")

	static public let xmark_bin_circle = SFSymbol(identifier: "xmark.bin.circle")

	static public let xmark_bin_circle_fill = SFSymbol(identifier: "xmark.bin.circle.fill")

	static public let list_bullet_rectangle = SFSymbol(identifier: "list.bullet.rectangle")

	static public let calendar_badge_clock = SFSymbol(identifier: "calendar.badge.clock")

	static public let calendar_badge_clock_rtl = SFSymbol(identifier: "calendar.badge.clock.rtl")

	static public let calendar_badge_exclamationmark = SFSymbol(identifier: "calendar.badge.exclamationmark")

	static public let arrowshape_turn_up_backward = SFSymbol(identifier: "arrowshape.turn.up.backward")

	static public let arrowshape_turn_up_backward_fill = SFSymbol(identifier: "arrowshape.turn.up.backward.fill")

	static public let arrowshape_turn_up_backward_circle = SFSymbol(identifier: "arrowshape.turn.up.backward.circle")

	static public let arrowshape_turn_up_backward_circle_fill = SFSymbol(identifier: "arrowshape.turn.up.backward.circle.fill")

	static public let arrowshape_turn_up_forward = SFSymbol(identifier: "arrowshape.turn.up.forward")

	static public let arrowshape_turn_up_forward_fill = SFSymbol(identifier: "arrowshape.turn.up.forward.fill")

	static public let arrowshape_turn_up_forward_circle = SFSymbol(identifier: "arrowshape.turn.up.forward.circle")

	static public let arrowshape_turn_up_forward_circle_fill = SFSymbol(identifier: "arrowshape.turn.up.forward.circle.fill")

	static public let arrowshape_turn_up_left_2_circle = SFSymbol(identifier: "arrowshape.turn.up.left.2.circle")

	static public let arrowshape_turn_up_left_2_circle_fill = SFSymbol(identifier: "arrowshape.turn.up.left.2.circle.fill")

	static public let arrowshape_turn_up_backward_2 = SFSymbol(identifier: "arrowshape.turn.up.backward.2")

	static public let arrowshape_turn_up_backward_2_fill = SFSymbol(identifier: "arrowshape.turn.up.backward.2.fill")

	static public let arrowshape_turn_up_backward_2_circle = SFSymbol(identifier: "arrowshape.turn.up.backward.2.circle")

	static public let arrowshape_turn_up_backward_2_circle_fill = SFSymbol(identifier: "arrowshape.turn.up.backward.2.circle.fill")

	static public let arrowshape_zigzag_right = SFSymbol(identifier: "arrowshape.zigzag.right")

	static public let arrowshape_zigzag_right_fill = SFSymbol(identifier: "arrowshape.zigzag.right.fill")

	static public let arrowshape_zigzag_forward = SFSymbol(identifier: "arrowshape.zigzag.forward")

	static public let arrowshape_zigzag_forward_fill = SFSymbol(identifier: "arrowshape.zigzag.forward.fill")

	static public let arrowshape_bounce_right = SFSymbol(identifier: "arrowshape.bounce.right")

	static public let arrowshape_bounce_right_fill = SFSymbol(identifier: "arrowshape.bounce.right.fill")

	static public let arrowshape_bounce_forward = SFSymbol(identifier: "arrowshape.bounce.forward")

	static public let arrowshape_bounce_forward_fill = SFSymbol(identifier: "arrowshape.bounce.forward.fill")

	static public let books_vertical = SFSymbol(identifier: "books.vertical")

	static public let books_vertical_fill = SFSymbol(identifier: "books.vertical.fill")

	static public let book_closed = SFSymbol(identifier: "book.closed")

	static public let book_closed_fill = SFSymbol(identifier: "book.closed.fill")

	static public let text_book_closed = SFSymbol(identifier: "text.book.closed")

	static public let text_book_closed_fill = SFSymbol(identifier: "text.book.closed.fill")

	static public let greetingcard = SFSymbol(identifier: "greetingcard")

	static public let greetingcard_fill = SFSymbol(identifier: "greetingcard.fill")

	static public let newspaper = SFSymbol(identifier: "newspaper")

	static public let newspaper_fill = SFSymbol(identifier: "newspaper.fill")

	static public let bookmark_circle = SFSymbol(identifier: "bookmark.circle")

	static public let bookmark_circle_fill = SFSymbol(identifier: "bookmark.circle.fill")

	static public let bookmark_slash = SFSymbol(identifier: "bookmark.slash")

	static public let bookmark_slash_fill = SFSymbol(identifier: "bookmark.slash.fill")

	static public let graduationcap = SFSymbol(identifier: "graduationcap")

	static public let graduationcap_fill = SFSymbol(identifier: "graduationcap.fill")

	static public let ruler = SFSymbol(identifier: "ruler")

	static public let ruler_fill = SFSymbol(identifier: "ruler.fill")

	static public let paperclip_badge_ellipsis = SFSymbol(identifier: "paperclip.badge.ellipsis")

	static public let rectangle_dashed_and_paperclip = SFSymbol(identifier: "rectangle.dashed.and.paperclip")

	static public let link_badge_plus = SFSymbol(identifier: "link.badge.plus")

	static public let person_fill_turn_right = SFSymbol(identifier: "person.fill.turn.right")

	static public let person_fill_turn_down = SFSymbol(identifier: "person.fill.turn.down")

	static public let person_fill_turn_left = SFSymbol(identifier: "person.fill.turn.left")

	static public let person_fill_checkmark = SFSymbol(identifier: "person.fill.checkmark")

	static public let person_fill_checkmark_rtl = SFSymbol(identifier: "person.fill.checkmark.rtl")

	static public let person_fill_xmark = SFSymbol(identifier: "person.fill.xmark")

	static public let person_fill_xmark_rtl = SFSymbol(identifier: "person.fill.xmark.rtl")

	static public let person_fill_questionmark = SFSymbol(identifier: "person.fill.questionmark")

	static public let person_fill_questionmark_rtl = SFSymbol(identifier: "person.fill.questionmark.rtl")

	static public let person_fill_questionmark_ar = SFSymbol(identifier: "person.fill.questionmark.ar")

	static public let person_fill_badge_plus = SFSymbol(identifier: "person.fill.badge.plus")

	static public let person_fill_badge_minus = SFSymbol(identifier: "person.fill.badge.minus")

	static public let person_2_circle = SFSymbol(identifier: "person.2.circle")

	static public let person_2_circle_fill = SFSymbol(identifier: "person.2.circle.fill")

	static public let person_crop_circle_badge_questionmark = SFSymbol(identifier: "person.crop.circle.badge.questionmark")

	static public let person_crop_circle_badge_questionmark_ar = SFSymbol(identifier: "person.crop.circle.badge.questionmark.ar")

	static public let person_crop_circle_badge_exclamationmark = SFSymbol(identifier: "person.crop.circle.badge.exclamationmark")

	static public let arrow_up_and_person_rectangle_portrait = SFSymbol(identifier: "arrow.up.and.person.rectangle.portrait")

	static public let arrow_up_and_person_rectangle_turn_right = SFSymbol(identifier: "arrow.up.and.person.rectangle.turn.right")

	static public let arrow_up_and_person_rectangle_turn_left = SFSymbol(identifier: "arrow.up.and.person.rectangle.turn.left")

	static public let square_and_at_rectangle = SFSymbol(identifier: "square.and.at.rectangle")

	static public let figure_stand = SFSymbol(identifier: "figure.stand")

	static public let figure_stand_line_dotted_figure_stand = SFSymbol(identifier: "figure.stand.line.dotted.figure.stand")

	static public let figure_walk = SFSymbol(identifier: "figure.walk")

	static public let figure_walk_circle = SFSymbol(identifier: "figure.walk.circle")

	static public let figure_walk_circle_fill = SFSymbol(identifier: "figure.walk.circle.fill")

	static public let figure_walk_diamond = SFSymbol(identifier: "figure.walk.diamond")

	static public let figure_walk_diamond_fill = SFSymbol(identifier: "figure.walk.diamond.fill")

	static public let figure_wave = SFSymbol(identifier: "figure.wave")

	static public let figure_wave_circle = SFSymbol(identifier: "figure.wave.circle")

	static public let figure_wave_circle_fill = SFSymbol(identifier: "figure.wave.circle.fill")

	static public let command_circle = SFSymbol(identifier: "command.circle")

	static public let command_circle_fill = SFSymbol(identifier: "command.circle.fill")

	static public let command_square = SFSymbol(identifier: "command.square")

	static public let command_square_fill = SFSymbol(identifier: "command.square.fill")

	static public let restart = SFSymbol(identifier: "restart")

	static public let restart_circle = SFSymbol(identifier: "restart.circle")

	static public let sleep = SFSymbol(identifier: "sleep")

	static public let wake = SFSymbol(identifier: "wake")

	static public let fn = SFSymbol(identifier: "fn")

	static public let togglepower = SFSymbol(identifier: "togglepower")

	static public let poweron = SFSymbol(identifier: "poweron")

	static public let poweroff = SFSymbol(identifier: "poweroff")

	static public let powersleep = SFSymbol(identifier: "powersleep")

	static public let eject_circle = SFSymbol(identifier: "eject.circle")

	static public let eject_circle_fill = SFSymbol(identifier: "eject.circle.fill")

	static public let mount = SFSymbol(identifier: "mount")

	static public let mount_fill = SFSymbol(identifier: "mount.fill")

	static public let filemenu_and_selection = SFSymbol(identifier: "filemenu.and.selection")

	static public let keyboard_badge_ellipsis = SFSymbol(identifier: "keyboard.badge.ellipsis")

	static public let keyboard_chevron_compact_left = SFSymbol(identifier: "keyboard.chevron.compact.left")

	static public let keyboard_onehanded_left = SFSymbol(identifier: "keyboard.onehanded.left")

	static public let keyboard_onehanded_right = SFSymbol(identifier: "keyboard.onehanded.right")

	static public let network = SFSymbol(identifier: "network")

	static public let sparkle = SFSymbol(identifier: "sparkle")

	static public let thermometer_sun_fill = SFSymbol(identifier: "thermometer.sun.fill")

	static public let drop = SFSymbol(identifier: "drop")

	static public let drop_fill = SFSymbol(identifier: "drop.fill")

	static public let play_slash = SFSymbol(identifier: "play.slash")

	static public let play_slash_fill = SFSymbol(identifier: "play.slash.fill")

	static public let record_circle = SFSymbol(identifier: "record.circle")

	static public let record_circle_fill = SFSymbol(identifier: "record.circle.fill")

	static public let backward_frame = SFSymbol(identifier: "backward.frame")

	static public let backward_frame_fill = SFSymbol(identifier: "backward.frame.fill")

	static public let forward_frame = SFSymbol(identifier: "forward.frame")

	static public let forward_frame_fill = SFSymbol(identifier: "forward.frame.fill")

	static public let infinity = SFSymbol(identifier: "infinity")

	static public let megaphone = SFSymbol(identifier: "megaphone")

	static public let megaphone_fill = SFSymbol(identifier: "megaphone.fill")

	static public let speaker_slash_circle = SFSymbol(identifier: "speaker.slash.circle")

	static public let speaker_slash_circle_fill = SFSymbol(identifier: "speaker.slash.circle.fill")

	static public let speaker_slash_circle_rtl = SFSymbol(identifier: "speaker.slash.circle.rtl")

	static public let speaker_slash_circle_fill_rtl = SFSymbol(identifier: "speaker.slash.circle.fill.rtl")

	static public let speaker_wave_1 = SFSymbol(identifier: "speaker.wave.1")

	static public let speaker_wave_1_fill = SFSymbol(identifier: "speaker.wave.1.fill")

	static public let speaker_wave_2 = SFSymbol(identifier: "speaker.wave.2")

	static public let speaker_wave_2_fill = SFSymbol(identifier: "speaker.wave.2.fill")

	static public let speaker_wave_2_circle = SFSymbol(identifier: "speaker.wave.2.circle")

	static public let speaker_wave_2_circle_fill = SFSymbol(identifier: "speaker.wave.2.circle.fill")

	static public let speaker_wave_3 = SFSymbol(identifier: "speaker.wave.3")

	static public let speaker_wave_3_fill = SFSymbol(identifier: "speaker.wave.3.fill")

	static public let badge_plus_radiowaves_forward = SFSymbol(identifier: "badge.plus.radiowaves.forward")

	static public let music_quarternote_3 = SFSymbol(identifier: "music.quarternote.3")

	static public let swift = SFSymbol(identifier: "swift")

	static public let `1_magnifyingglass_ar` = SFSymbol(identifier: "1.magnifyingglass.ar")

	static public let arrow_up_left_and_down_right_magnifyingglass = SFSymbol(identifier: "arrow.up.left.and.down.right.magnifyingglass")

	static public let text_magnifyingglass = SFSymbol(identifier: "text.magnifyingglass")

	static public let text_magnifyingglass_rtl = SFSymbol(identifier: "text.magnifyingglass.rtl")

	static public let loupe = SFSymbol(identifier: "loupe")

	static public let line_diagonal = SFSymbol(identifier: "line.diagonal")

	static public let target = SFSymbol(identifier: "target")

	static public let circle_dashed = SFSymbol(identifier: "circle.dashed")

	static public let circlebadge = SFSymbol(identifier: "circlebadge")

	static public let circlebadge_fill = SFSymbol(identifier: "circlebadge.fill")

	static public let circlebadge_2 = SFSymbol(identifier: "circlebadge.2")

	static public let circlebadge_2_fill = SFSymbol(identifier: "circlebadge.2.fill")

	static public let placeholdertext_fill = SFSymbol(identifier: "placeholdertext.fill")

	static public let square_slash = SFSymbol(identifier: "square.slash")

	static public let square_slash_fill = SFSymbol(identifier: "square.slash.fill")

	static public let square_split_diagonal_2x2 = SFSymbol(identifier: "square.split.diagonal.2x2")

	static public let square_split_diagonal_2x2_fill = SFSymbol(identifier: "square.split.diagonal.2x2.fill")

	static public let square_split_diagonal = SFSymbol(identifier: "square.split.diagonal")

	static public let square_split_diagonal_fill = SFSymbol(identifier: "square.split.diagonal.fill")

	static public let square_dashed = SFSymbol(identifier: "square.dashed")

	static public let questionmark_square_dashed = SFSymbol(identifier: "questionmark.square.dashed")

	static public let questionmark_square_dashed_ar = SFSymbol(identifier: "questionmark.square.dashed.ar")

	static public let circle_square = SFSymbol(identifier: "circle.square")

	static public let square_on_square_dashed = SFSymbol(identifier: "square.on.square.dashed")

	static public let r_square_on_square = SFSymbol(identifier: "r.square.on.square")

	static public let j_square_on_square = SFSymbol(identifier: "j.square.on.square")

	static public let h_square_on_square = SFSymbol(identifier: "h.square.on.square")

	static public let square_grid_3x3 = SFSymbol(identifier: "square.grid.3x3")

	static public let square_grid_3x3_fill = SFSymbol(identifier: "square.grid.3x3.fill")

	static public let square_grid_3x1_below_line_grid_1x2 = SFSymbol(identifier: "square.grid.3x1.below.line.grid.1x2")

	static public let squareshape = SFSymbol(identifier: "squareshape")

	static public let squareshape_fill = SFSymbol(identifier: "squareshape.fill")

	static public let dot_squareshape = SFSymbol(identifier: "dot.squareshape")

	static public let dot_squareshape_fill = SFSymbol(identifier: "dot.squareshape.fill")

	static public let arrow_down_app = SFSymbol(identifier: "arrow.down.app")

	static public let arrow_down_app_fill = SFSymbol(identifier: "arrow.down.app.fill")

	static public let arrow_up_forward_app = SFSymbol(identifier: "arrow.up.forward.app")

	static public let arrow_up_forward_app_fill = SFSymbol(identifier: "arrow.up.forward.app.fill")

	static public let appclip = SFSymbol(identifier: "appclip")

	static public let rectangle_slash = SFSymbol(identifier: "rectangle.slash")

	static public let rectangle_slash_fill = SFSymbol(identifier: "rectangle.slash.fill")

	static public let rectangle_split_2x1 = SFSymbol(identifier: "rectangle.split.2x1")

	static public let rectangle_split_2x1_fill = SFSymbol(identifier: "rectangle.split.2x1.fill")

	static public let rectangle_split_1x2 = SFSymbol(identifier: "rectangle.split.1x2")

	static public let rectangle_split_1x2_fill = SFSymbol(identifier: "rectangle.split.1x2.fill")

	static public let rectangle_split_2x2 = SFSymbol(identifier: "rectangle.split.2x2")

	static public let rectangle_split_2x2_fill = SFSymbol(identifier: "rectangle.split.2x2.fill")

	static public let tablecells = SFSymbol(identifier: "tablecells")

	static public let tablecells_fill = SFSymbol(identifier: "tablecells.fill")

	static public let tablecells_badge_ellipsis = SFSymbol(identifier: "tablecells.badge.ellipsis")

	static public let arrow_up_right_and_arrow_down_left_rectangle = SFSymbol(identifier: "arrow.up.right.and.arrow.down.left.rectangle")

	static public let arrow_up_right_and_arrow_down_left_rectangle_fill = SFSymbol(identifier: "arrow.up.right.and.arrow.down.left.rectangle.fill")

	static public let rectangle_on_rectangle_slash = SFSymbol(identifier: "rectangle.on.rectangle.slash")

	static public let rectangle_portrait = SFSymbol(identifier: "rectangle.portrait")

	static public let rectangle_portrait_fill = SFSymbol(identifier: "rectangle.portrait.fill")

	static public let capsule_portrait = SFSymbol(identifier: "capsule.portrait")

	static public let capsule_portrait_fill = SFSymbol(identifier: "capsule.portrait.fill")

	static public let oval = SFSymbol(identifier: "oval")

	static public let oval_fill = SFSymbol(identifier: "oval.fill")

	static public let oval_portrait = SFSymbol(identifier: "oval.portrait")

	static public let oval_portrait_fill = SFSymbol(identifier: "oval.portrait.fill")

	static public let diamond = SFSymbol(identifier: "diamond")

	static public let diamond_fill = SFSymbol(identifier: "diamond.fill")

	static public let octagon = SFSymbol(identifier: "octagon")

	static public let octagon_fill = SFSymbol(identifier: "octagon.fill")

	static public let seal = SFSymbol(identifier: "seal")

	static public let seal_fill = SFSymbol(identifier: "seal.fill")

	static public let bolt_heart = SFSymbol(identifier: "bolt.heart")

	static public let bolt_heart_fill = SFSymbol(identifier: "bolt.heart.fill")

	static public let arrow_up_heart = SFSymbol(identifier: "arrow.up.heart")

	static public let arrow_up_heart_fill = SFSymbol(identifier: "arrow.up.heart.fill")

	static public let arrow_down_heart = SFSymbol(identifier: "arrow.down.heart")

	static public let arrow_down_heart_fill = SFSymbol(identifier: "arrow.down.heart.fill")

	static public let star_square = SFSymbol(identifier: "star.square")

	static public let star_square_fill = SFSymbol(identifier: "star.square.fill")

	static public let line_horizontal_star_fill_line_horizontal = SFSymbol(identifier: "line.horizontal.star.fill.line.horizontal")

	static public let flag_slash_circle = SFSymbol(identifier: "flag.slash.circle")

	static public let flag_slash_circle_fill = SFSymbol(identifier: "flag.slash.circle.fill")

	static public let flag_badge_ellipsis = SFSymbol(identifier: "flag.badge.ellipsis")

	static public let flag_badge_ellipsis_fill = SFSymbol(identifier: "flag.badge.ellipsis.fill")

	static public let bell_slash_circle = SFSymbol(identifier: "bell.slash.circle")

	static public let bell_slash_circle_fill = SFSymbol(identifier: "bell.slash.circle.fill")

	static public let bell_badge = SFSymbol(identifier: "bell.badge")

	static public let bell_badge_fill = SFSymbol(identifier: "bell.badge.fill")

	static public let tag_slash = SFSymbol(identifier: "tag.slash")

	static public let tag_slash_fill = SFSymbol(identifier: "tag.slash.fill")

	static public let bolt_slash_circle = SFSymbol(identifier: "bolt.slash.circle")

	static public let bolt_slash_circle_fill = SFSymbol(identifier: "bolt.slash.circle.fill")

	static public let checkmark_icloud = SFSymbol(identifier: "checkmark.icloud")

	static public let checkmark_icloud_fill = SFSymbol(identifier: "checkmark.icloud.fill")

	static public let key_icloud = SFSymbol(identifier: "key.icloud")

	static public let key_icloud_fill = SFSymbol(identifier: "key.icloud.fill")

	static public let camera_badge_ellipsis = SFSymbol(identifier: "camera.badge.ellipsis")

	static public let arrow_up_message = SFSymbol(identifier: "arrow.up.message")

	static public let arrow_up_message_fill = SFSymbol(identifier: "arrow.up.message.fill")

	static public let plus_message = SFSymbol(identifier: "plus.message")

	static public let plus_message_fill = SFSymbol(identifier: "plus.message.fill")

	static public let quote_bubble_rtl = SFSymbol(identifier: "quote.bubble.rtl")

	static public let quote_bubble_fill_rtl = SFSymbol(identifier: "quote.bubble.fill.rtl")

	static public let text_bubble_rtl = SFSymbol(identifier: "text.bubble.rtl")

	static public let text_bubble_fill_rtl = SFSymbol(identifier: "text.bubble.fill.rtl")

	static public let ellipsis_bubble = SFSymbol(identifier: "ellipsis.bubble")

	static public let ellipsis_bubble_fill = SFSymbol(identifier: "ellipsis.bubble.fill")

	static public let phone_connection = SFSymbol(identifier: "phone.connection")

	static public let teletype_circle = SFSymbol(identifier: "teletype.circle")

	static public let teletype_circle_fill = SFSymbol(identifier: "teletype.circle.fill")

	static public let video_fill_badge_plus = SFSymbol(identifier: "video.fill.badge.plus")

	static public let video_badge_checkmark = SFSymbol(identifier: "video.badge.checkmark")

	static public let video_fill_badge_checkmark = SFSymbol(identifier: "video.fill.badge.checkmark")

	static public let questionmark_video_ar = SFSymbol(identifier: "questionmark.video.ar")

	static public let questionmark_video_fill_ar = SFSymbol(identifier: "questionmark.video.fill.ar")

	static public let mail_stack = SFSymbol(identifier: "mail.stack")

	static public let mail_stack_fill = SFSymbol(identifier: "mail.stack.fill")

	static public let mail = SFSymbol(identifier: "mail")

	static public let mail_fill = SFSymbol(identifier: "mail.fill")

	static public let mail_and_text_magnifyingglass = SFSymbol(identifier: "mail.and.text.magnifyingglass")

	static public let mail_and_text_magnifyingglass_rtl = SFSymbol(identifier: "mail.and.text.magnifyingglass.rtl")

	static public let rectangle_and_text_magnifyingglass = SFSymbol(identifier: "rectangle.and.text.magnifyingglass")

	static public let rectangle_and_text_magnifyingglass_rtl = SFSymbol(identifier: "rectangle.and.text.magnifyingglass.rtl")

	static public let gearshape = SFSymbol(identifier: "gearshape")

	static public let gearshape_fill = SFSymbol(identifier: "gearshape.fill")

	static public let gearshape_2 = SFSymbol(identifier: "gearshape.2")

	static public let gearshape_2_fill = SFSymbol(identifier: "gearshape.2.fill")

	static public let signature_ar = SFSymbol(identifier: "signature.ar")

	static public let signature_he = SFSymbol(identifier: "signature.he")

	static public let line_3_crossed_swirl_circle = SFSymbol(identifier: "line.3.crossed.swirl.circle")

	static public let line_3_crossed_swirl_circle_fill = SFSymbol(identifier: "line.3.crossed.swirl.circle.fill")

	static public let ellipsis_rectangle = SFSymbol(identifier: "ellipsis.rectangle")

	static public let ellipsis_rectangle_fill = SFSymbol(identifier: "ellipsis.rectangle.fill")

	static public let bag_circle = SFSymbol(identifier: "bag.circle")

	static public let bag_circle_fill = SFSymbol(identifier: "bag.circle.fill")

	static public let creditcard_circle = SFSymbol(identifier: "creditcard.circle")

	static public let creditcard_circle_fill = SFSymbol(identifier: "creditcard.circle.fill")

	static public let giftcard = SFSymbol(identifier: "giftcard")

	static public let giftcard_fill = SFSymbol(identifier: "giftcard.fill")

	static public let wallet_pass = SFSymbol(identifier: "wallet.pass")

	static public let wallet_pass_fill = SFSymbol(identifier: "wallet.pass.fill")

	static public let gyroscope = SFSymbol(identifier: "gyroscope")

	static public let barometer = SFSymbol(identifier: "barometer")

	static public let metronome_fill = SFSymbol(identifier: "metronome.fill")

	static public let amplifier = SFSymbol(identifier: "amplifier")

	static public let die_face_1 = SFSymbol(identifier: "die.face.1")

	static public let die_face_1_fill = SFSymbol(identifier: "die.face.1.fill")

	static public let die_face_2 = SFSymbol(identifier: "die.face.2")

	static public let die_face_2_fill = SFSymbol(identifier: "die.face.2.fill")

	static public let die_face_3 = SFSymbol(identifier: "die.face.3")

	static public let die_face_3_fill = SFSymbol(identifier: "die.face.3.fill")

	static public let die_face_4 = SFSymbol(identifier: "die.face.4")

	static public let die_face_4_fill = SFSymbol(identifier: "die.face.4.fill")

	static public let die_face_5 = SFSymbol(identifier: "die.face.5")

	static public let die_face_5_fill = SFSymbol(identifier: "die.face.5.fill")

	static public let die_face_6 = SFSymbol(identifier: "die.face.6")

	static public let die_face_6_fill = SFSymbol(identifier: "die.face.6.fill")

	static public let pianokeys = SFSymbol(identifier: "pianokeys")

	static public let pianokeys_inverse = SFSymbol(identifier: "pianokeys.inverse")

	static public let paintbrush_pointed = SFSymbol(identifier: "paintbrush.pointed")

	static public let paintbrush_pointed_fill = SFSymbol(identifier: "paintbrush.pointed.fill")

	static public let level = SFSymbol(identifier: "level")

	static public let level_fill = SFSymbol(identifier: "level.fill")

	static public let wrench_and_screwdriver = SFSymbol(identifier: "wrench.and.screwdriver")

	static public let wrench_and_screwdriver_fill = SFSymbol(identifier: "wrench.and.screwdriver.fill")

	static public let applescript = SFSymbol(identifier: "applescript")

	static public let applescript_fill = SFSymbol(identifier: "applescript.fill")

	static public let scroll = SFSymbol(identifier: "scroll")

	static public let scroll_fill = SFSymbol(identifier: "scroll.fill")

	static public let stethoscope = SFSymbol(identifier: "stethoscope")

	static public let printer_dotmatrix = SFSymbol(identifier: "printer.dotmatrix")

	static public let printer_dotmatrix_fill = SFSymbol(identifier: "printer.dotmatrix.fill")

	static public let scanner = SFSymbol(identifier: "scanner")

	static public let scanner_fill = SFSymbol(identifier: "scanner.fill")

	static public let faxmachine = SFSymbol(identifier: "faxmachine")

	static public let `case` = SFSymbol(identifier: "case")

	static public let case_fill = SFSymbol(identifier: "case.fill")

	static public let latch_2_case = SFSymbol(identifier: "latch.2.case")

	static public let latch_2_case_fill = SFSymbol(identifier: "latch.2.case.fill")

	static public let cross_case = SFSymbol(identifier: "cross.case")

	static public let cross_case_fill = SFSymbol(identifier: "cross.case.fill")

	static public let puzzlepiece = SFSymbol(identifier: "puzzlepiece")

	static public let puzzlepiece_fill = SFSymbol(identifier: "puzzlepiece.fill")

	static public let house_circle = SFSymbol(identifier: "house.circle")

	static public let house_circle_fill = SFSymbol(identifier: "house.circle.fill")

	static public let music_note_house = SFSymbol(identifier: "music.note.house")

	static public let music_note_house_fill = SFSymbol(identifier: "music.note.house.fill")

	static public let building_columns = SFSymbol(identifier: "building.columns")

	static public let building_columns_fill = SFSymbol(identifier: "building.columns.fill")

	static public let signpost_left = SFSymbol(identifier: "signpost.left")

	static public let signpost_left_fill = SFSymbol(identifier: "signpost.left.fill")

	static public let signpost_right = SFSymbol(identifier: "signpost.right")

	static public let signpost_right_fill = SFSymbol(identifier: "signpost.right.fill")

	static public let square_split_bottomrightquarter = SFSymbol(identifier: "square.split.bottomrightquarter")

	static public let square_split_bottomrightquarter_fill = SFSymbol(identifier: "square.split.bottomrightquarter.fill")

	static public let building = SFSymbol(identifier: "building")

	static public let building_fill = SFSymbol(identifier: "building.fill")

	static public let building_2 = SFSymbol(identifier: "building.2")

	static public let building_2_fill = SFSymbol(identifier: "building.2.fill")

	static public let building_2_crop_circle = SFSymbol(identifier: "building.2.crop.circle")

	static public let building_2_crop_circle_fill = SFSymbol(identifier: "building.2.crop.circle.fill")

	static public let lock_square = SFSymbol(identifier: "lock.square")

	static public let lock_square_fill = SFSymbol(identifier: "lock.square.fill")

	static public let lock_square_stack = SFSymbol(identifier: "lock.square.stack")

	static public let lock_square_stack_fill = SFSymbol(identifier: "lock.square.stack.fill")

	static public let lock_rectangle = SFSymbol(identifier: "lock.rectangle")

	static public let lock_rectangle_fill = SFSymbol(identifier: "lock.rectangle.fill")

	static public let lock_rectangle_stack = SFSymbol(identifier: "lock.rectangle.stack")

	static public let lock_rectangle_stack_fill = SFSymbol(identifier: "lock.rectangle.stack.fill")

	static public let lock_rectangle_on_rectangle = SFSymbol(identifier: "lock.rectangle.on.rectangle")

	static public let lock_rectangle_on_rectangle_fill = SFSymbol(identifier: "lock.rectangle.on.rectangle.fill")

	static public let key = SFSymbol(identifier: "key")

	static public let key_fill = SFSymbol(identifier: "key.fill")

	static public let move_3d = SFSymbol(identifier: "move.3d")

	static public let scale_3d = SFSymbol(identifier: "scale.3d")

	static public let rotate_3d = SFSymbol(identifier: "rotate.3d")

	static public let cpu = SFSymbol(identifier: "cpu")

	static public let memorychip = SFSymbol(identifier: "memorychip")

	static public let opticaldisc = SFSymbol(identifier: "opticaldisc")

	static public let display = SFSymbol(identifier: "display")

	static public let display_trianglebadge_exclamationmark = SFSymbol(identifier: "display.trianglebadge.exclamationmark")

	static public let display_2 = SFSymbol(identifier: "display.2")

	static public let pc = SFSymbol(identifier: "pc")

	static public let macpro_gen1 = SFSymbol(identifier: "macpro.gen1")

	static public let macpro_gen2 = SFSymbol(identifier: "macpro.gen2")

	static public let macpro_gen2_fill = SFSymbol(identifier: "macpro.gen2.fill")

	static public let macpro_gen3 = SFSymbol(identifier: "macpro.gen3")

	static public let macpro_gen3_server = SFSymbol(identifier: "macpro.gen3.server")

	static public let server_rack = SFSymbol(identifier: "server.rack")

	static public let xserve = SFSymbol(identifier: "xserve")

	static public let laptopcomputer = SFSymbol(identifier: "laptopcomputer")

	static public let macmini = SFSymbol(identifier: "macmini")

	static public let macmini_fill = SFSymbol(identifier: "macmini.fill")

	static public let airport_express = SFSymbol(identifier: "airport.express")

	static public let airport_extreme = SFSymbol(identifier: "airport.extreme")

	static public let airport_extreme_tower = SFSymbol(identifier: "airport.extreme.tower")

	static public let ipod = SFSymbol(identifier: "ipod")

	static public let flipphone = SFSymbol(identifier: "flipphone")

	static public let candybarphone = SFSymbol(identifier: "candybarphone")

	static public let iphone = SFSymbol(identifier: "iphone")

	static public let iphone_radiowaves_left_and_right = SFSymbol(identifier: "iphone.radiowaves.left.and.right")

	static public let iphone_slash = SFSymbol(identifier: "iphone.slash")

	static public let arrow_turn_up_forward_iphone = SFSymbol(identifier: "arrow.turn.up.forward.iphone")

	static public let arrow_turn_up_forward_iphone_fill = SFSymbol(identifier: "arrow.turn.up.forward.iphone.fill")

	static public let apps_iphone = SFSymbol(identifier: "apps.iphone")

	static public let apps_iphone_badge_plus = SFSymbol(identifier: "apps.iphone.badge.plus")

	static public let apps_iphone_landscape = SFSymbol(identifier: "apps.iphone.landscape")

	static public let apps_iphone_landscape_rtl = SFSymbol(identifier: "apps.iphone.landscape.rtl")

	static public let ipad = SFSymbol(identifier: "ipad")

	static public let ipad_landscape = SFSymbol(identifier: "ipad.landscape")

	static public let apps_ipad = SFSymbol(identifier: "apps.ipad")

	static public let apps_ipad_landscape = SFSymbol(identifier: "apps.ipad.landscape")

	static public let applewatch = SFSymbol(identifier: "applewatch")

	static public let applewatch_watchface = SFSymbol(identifier: "applewatch.watchface")

	static public let applewatch_radiowaves_left_and_right = SFSymbol(identifier: "applewatch.radiowaves.left.and.right")

	static public let applewatch_slash = SFSymbol(identifier: "applewatch.slash")

	static public let headphones_circle = SFSymbol(identifier: "headphones.circle")

	static public let headphones_circle_fill = SFSymbol(identifier: "headphones.circle.fill")

	static public let earpods = SFSymbol(identifier: "earpods")

	static public let airpods = SFSymbol(identifier: "airpods")

	static public let airpod_right = SFSymbol(identifier: "airpod.right")

	static public let airpod_left = SFSymbol(identifier: "airpod.left")

	static public let homepod = SFSymbol(identifier: "homepod")

	static public let homepod_fill = SFSymbol(identifier: "homepod.fill")

	static public let homepod_2 = SFSymbol(identifier: "homepod.2")

	static public let homepod_2_fill = SFSymbol(identifier: "homepod.2.fill")

	static public let hifispeaker_and_homepod = SFSymbol(identifier: "hifispeaker.and.homepod")

	static public let hifispeaker_and_homepod_fill = SFSymbol(identifier: "hifispeaker.and.homepod.fill")

	static public let hifispeaker_2 = SFSymbol(identifier: "hifispeaker.2")

	static public let hifispeaker_2_fill = SFSymbol(identifier: "hifispeaker.2.fill")

	static public let appletv = SFSymbol(identifier: "appletv")

	static public let appletv_fill = SFSymbol(identifier: "appletv.fill")

	static public let `4k_tv` = SFSymbol(identifier: "4k.tv")

	static public let `4k_tv_fill` = SFSymbol(identifier: "4k.tv.fill")

	static public let tv_and_hifispeaker_fill = SFSymbol(identifier: "tv.and.hifispeaker.fill")

	static public let radio = SFSymbol(identifier: "radio")

	static public let radio_fill = SFSymbol(identifier: "radio.fill")

	static public let dot_radiowaves_forward = SFSymbol(identifier: "dot.radiowaves.forward")

	static public let wave_3_left = SFSymbol(identifier: "wave.3.left")

	static public let wave_3_left_circle = SFSymbol(identifier: "wave.3.left.circle")

	static public let wave_3_left_circle_fill = SFSymbol(identifier: "wave.3.left.circle.fill")

	static public let wave_3_backward = SFSymbol(identifier: "wave.3.backward")

	static public let wave_3_backward_circle = SFSymbol(identifier: "wave.3.backward.circle")

	static public let wave_3_backward_circle_fill = SFSymbol(identifier: "wave.3.backward.circle.fill")

	static public let wave_3_right = SFSymbol(identifier: "wave.3.right")

	static public let wave_3_right_circle = SFSymbol(identifier: "wave.3.right.circle")

	static public let wave_3_right_circle_fill = SFSymbol(identifier: "wave.3.right.circle.fill")

	static public let wave_3_forward = SFSymbol(identifier: "wave.3.forward")

	static public let wave_3_forward_circle = SFSymbol(identifier: "wave.3.forward.circle")

	static public let wave_3_forward_circle_fill = SFSymbol(identifier: "wave.3.forward.circle.fill")

	static public let pip = SFSymbol(identifier: "pip")

	static public let pip_fill = SFSymbol(identifier: "pip.fill")

	static public let pip_exit = SFSymbol(identifier: "pip.exit")

	static public let pip_enter = SFSymbol(identifier: "pip.enter")

	static public let pip_swap = SFSymbol(identifier: "pip.swap")

	static public let pip_remove = SFSymbol(identifier: "pip.remove")

	static public let timeline_selection = SFSymbol(identifier: "timeline.selection")

	static public let rectangle_arrowtriangle_2_outward = SFSymbol(identifier: "rectangle.arrowtriangle.2.outward")

	static public let rectangle_arrowtriangle_2_inward = SFSymbol(identifier: "rectangle.arrowtriangle.2.inward")

	static public let rectangle_portrait_arrowtriangle_2_outward = SFSymbol(identifier: "rectangle.portrait.arrowtriangle.2.outward")

	static public let rectangle_portrait_arrowtriangle_2_inward = SFSymbol(identifier: "rectangle.portrait.arrowtriangle.2.inward")

	static public let guitars_fill = SFSymbol(identifier: "guitars.fill")

	static public let airplane_circle = SFSymbol(identifier: "airplane.circle")

	static public let airplane_circle_fill = SFSymbol(identifier: "airplane.circle.fill")

	static public let car_circle = SFSymbol(identifier: "car.circle")

	static public let car_circle_fill = SFSymbol(identifier: "car.circle.fill")

	static public let bolt_car = SFSymbol(identifier: "bolt.car")

	static public let bolt_car_fill = SFSymbol(identifier: "bolt.car.fill")

	static public let car_2 = SFSymbol(identifier: "car.2")

	static public let car_2_fill = SFSymbol(identifier: "car.2.fill")

	static public let bus = SFSymbol(identifier: "bus")

	static public let bus_fill = SFSymbol(identifier: "bus.fill")

	static public let bus_doubledecker = SFSymbol(identifier: "bus.doubledecker")

	static public let bus_doubledecker_fill = SFSymbol(identifier: "bus.doubledecker.fill")

	static public let tram = SFSymbol(identifier: "tram")

	static public let tram_circle = SFSymbol(identifier: "tram.circle")

	static public let tram_circle_fill = SFSymbol(identifier: "tram.circle.fill")

	static public let bicycle = SFSymbol(identifier: "bicycle")

	static public let bicycle_circle = SFSymbol(identifier: "bicycle.circle")

	static public let bicycle_circle_fill = SFSymbol(identifier: "bicycle.circle.fill")

	static public let minus_plus_batteryblock = SFSymbol(identifier: "minus.plus.batteryblock")

	static public let minus_plus_batteryblock_fill = SFSymbol(identifier: "minus.plus.batteryblock.fill")

	static public let lungs = SFSymbol(identifier: "lungs")

	static public let lungs_fill = SFSymbol(identifier: "lungs.fill")

	static public let pills = SFSymbol(identifier: "pills")

	static public let pills_fill = SFSymbol(identifier: "pills.fill")

	static public let cross = SFSymbol(identifier: "cross")

	static public let cross_fill = SFSymbol(identifier: "cross.fill")

	static public let cross_circle = SFSymbol(identifier: "cross.circle")

	static public let cross_circle_fill = SFSymbol(identifier: "cross.circle.fill")

	static public let staroflife_circle = SFSymbol(identifier: "staroflife.circle")

	static public let staroflife_circle_fill = SFSymbol(identifier: "staroflife.circle.fill")

	static public let heart_text_square = SFSymbol(identifier: "heart.text.square")

	static public let heart_text_square_fill = SFSymbol(identifier: "heart.text.square.fill")

	static public let ladybug = SFSymbol(identifier: "ladybug")

	static public let ladybug_fill = SFSymbol(identifier: "ladybug.fill")

	static public let leaf = SFSymbol(identifier: "leaf")

	static public let leaf_fill = SFSymbol(identifier: "leaf.fill")

	static public let crown = SFSymbol(identifier: "crown")

	static public let crown_fill = SFSymbol(identifier: "crown.fill")

	static public let ticket = SFSymbol(identifier: "ticket")

	static public let ticket_fill = SFSymbol(identifier: "ticket.fill")

	static public let face_smiling = SFSymbol(identifier: "face.smiling")

	static public let face_dashed = SFSymbol(identifier: "face.dashed")

	static public let face_dashed_fill = SFSymbol(identifier: "face.dashed.fill")

	static public let eye_circle = SFSymbol(identifier: "eye.circle")

	static public let eye_circle_fill = SFSymbol(identifier: "eye.circle.fill")

	static public let eyes = SFSymbol(identifier: "eyes")

	static public let eyes_inverse = SFSymbol(identifier: "eyes.inverse")

	static public let eyebrow = SFSymbol(identifier: "eyebrow")

	static public let nose = SFSymbol(identifier: "nose")

	static public let nose_fill = SFSymbol(identifier: "nose.fill")

	static public let comb = SFSymbol(identifier: "comb")

	static public let comb_fill = SFSymbol(identifier: "comb.fill")

	static public let mustache = SFSymbol(identifier: "mustache")

	static public let mustache_fill = SFSymbol(identifier: "mustache.fill")

	static public let mouth = SFSymbol(identifier: "mouth")

	static public let mouth_fill = SFSymbol(identifier: "mouth.fill")

	static public let ear_fill = SFSymbol(identifier: "ear.fill")

	static public let ear_badge_checkmark = SFSymbol(identifier: "ear.badge.checkmark")

	static public let ear_trianglebadge_exclamationmark = SFSymbol(identifier: "ear.trianglebadge.exclamationmark")

	static public let hand_point_up_left = SFSymbol(identifier: "hand.point.up.left")

	static public let hand_point_up_left_fill = SFSymbol(identifier: "hand.point.up.left.fill")

	static public let hand_tap = SFSymbol(identifier: "hand.tap")

	static public let hand_tap_fill = SFSymbol(identifier: "hand.tap.fill")

	static public let hand_point_up = SFSymbol(identifier: "hand.point.up")

	static public let hand_point_up_fill = SFSymbol(identifier: "hand.point.up.fill")

	static public let hand_point_up_braille = SFSymbol(identifier: "hand.point.up.braille")

	static public let hand_point_up_braille_fill = SFSymbol(identifier: "hand.point.up.braille.fill")

	static public let hand_point_down = SFSymbol(identifier: "hand.point.down")

	static public let hand_point_down_fill = SFSymbol(identifier: "hand.point.down.fill")

	static public let hand_wave = SFSymbol(identifier: "hand.wave")

	static public let hand_wave_fill = SFSymbol(identifier: "hand.wave.fill")

	static public let hands_clap = SFSymbol(identifier: "hands.clap")

	static public let hands_clap_fill = SFSymbol(identifier: "hands.clap.fill")

	static public let plus_viewfinder = SFSymbol(identifier: "plus.viewfinder")

	static public let location_viewfinder = SFSymbol(identifier: "location.viewfinder")

	static public let location_fill_viewfinder = SFSymbol(identifier: "location.fill.viewfinder")

	static public let person_fill_viewfinder = SFSymbol(identifier: "person.fill.viewfinder")

	static public let text_below_photo = SFSymbol(identifier: "text.below.photo")

	static public let text_below_photo_fill = SFSymbol(identifier: "text.below.photo.fill")

	static public let camera_metering_center_weighted_average = SFSymbol(identifier: "camera.metering.center.weighted.average")

	static public let camera_metering_center_weighted = SFSymbol(identifier: "camera.metering.center.weighted")

	static public let camera_metering_matrix = SFSymbol(identifier: "camera.metering.matrix")

	static public let camera_metering_multispot = SFSymbol(identifier: "camera.metering.multispot")

	static public let camera_metering_none = SFSymbol(identifier: "camera.metering.none")

	static public let camera_metering_partial = SFSymbol(identifier: "camera.metering.partial")

	static public let camera_metering_spot = SFSymbol(identifier: "camera.metering.spot")

	static public let camera_metering_unknown = SFSymbol(identifier: "camera.metering.unknown")

	static public let camera_metering_unknown_ar = SFSymbol(identifier: "camera.metering.unknown.ar")

	static public let camera_aperture = SFSymbol(identifier: "camera.aperture")

	static public let rectangle_dashed = SFSymbol(identifier: "rectangle.dashed")

	static public let rectangle_dashed_badge_record = SFSymbol(identifier: "rectangle.dashed.badge.record")

	static public let rectangle_badge_plus = SFSymbol(identifier: "rectangle.badge.plus")

	static public let rectangle_fill_badge_plus = SFSymbol(identifier: "rectangle.fill.badge.plus")

	static public let rectangle_badge_minus = SFSymbol(identifier: "rectangle.badge.minus")

	static public let rectangle_fill_badge_minus = SFSymbol(identifier: "rectangle.fill.badge.minus")

	static public let photo_on_rectangle_angled = SFSymbol(identifier: "photo.on.rectangle.angled")

	static public let sparkles_rectangle_stack = SFSymbol(identifier: "sparkles.rectangle.stack")

	static public let sparkles_rectangle_stack_fill = SFSymbol(identifier: "sparkles.rectangle.stack.fill")

	static public let sidebar_leading = SFSymbol(identifier: "sidebar.leading")

	static public let sidebar_trailing = SFSymbol(identifier: "sidebar.trailing")

	static public let sidebar_squares_left = SFSymbol(identifier: "sidebar.squares.left")

	static public let sidebar_squares_right = SFSymbol(identifier: "sidebar.squares.right")

	static public let sidebar_squares_leading = SFSymbol(identifier: "sidebar.squares.leading")

	static public let sidebar_squares_trailing = SFSymbol(identifier: "sidebar.squares.trailing")

	static public let macwindow_badge_plus = SFSymbol(identifier: "macwindow.badge.plus")

	static public let dock_rectangle = SFSymbol(identifier: "dock.rectangle")

	static public let dock_arrow_up_rectangle = SFSymbol(identifier: "dock.arrow.up.rectangle")

	static public let dock_arrow_down_rectangle = SFSymbol(identifier: "dock.arrow.down.rectangle")

	static public let menubar_rectangle = SFSymbol(identifier: "menubar.rectangle")

	static public let menubar_dock_rectangle = SFSymbol(identifier: "menubar.dock.rectangle")

	static public let menubar_dock_rectangle_badge_record = SFSymbol(identifier: "menubar.dock.rectangle.badge.record")

	static public let menubar_arrow_up_rectangle = SFSymbol(identifier: "menubar.arrow.up.rectangle")

	static public let menubar_arrow_down_rectangle = SFSymbol(identifier: "menubar.arrow.down.rectangle")

	static public let macwindow_on_rectangle = SFSymbol(identifier: "macwindow.on.rectangle")

	static public let macwindow_on_rectangle_rtl = SFSymbol(identifier: "macwindow.on.rectangle.rtl")

	static public let text_and_command_macwindow = SFSymbol(identifier: "text.and.command.macwindow")

	static public let keyboard_macwindow = SFSymbol(identifier: "keyboard.macwindow")

	static public let mosaic = SFSymbol(identifier: "mosaic")

	static public let mosaic_fill = SFSymbol(identifier: "mosaic.fill")

	static public let square_on_square_squareshape_controlhandles = SFSymbol(identifier: "square.on.square.squareshape.controlhandles")

	static public let squareshape_controlhandles_on_squareshape_controlhandles = SFSymbol(identifier: "squareshape.controlhandles.on.squareshape.controlhandles")

	static public let rectangle_connected_to_line_below = SFSymbol(identifier: "rectangle.connected.to.line.below")

	static public let switch_2 = SFSymbol(identifier: "switch.2")

	static public let lineweight = SFSymbol(identifier: "lineweight")

	static public let slider_vertical_3 = SFSymbol(identifier: "slider.vertical.3")

	static public let cube_transparent = SFSymbol(identifier: "cube.transparent")

	static public let cube_transparent_fill = SFSymbol(identifier: "cube.transparent.fill")

	static public let shippingbox = SFSymbol(identifier: "shippingbox")

	static public let shippingbox_fill = SFSymbol(identifier: "shippingbox.fill")

	static public let cone = SFSymbol(identifier: "cone")

	static public let cone_fill = SFSymbol(identifier: "cone.fill")

	static public let pyramid = SFSymbol(identifier: "pyramid")

	static public let pyramid_fill = SFSymbol(identifier: "pyramid.fill")

	static public let square_stack_3d_down_forward = SFSymbol(identifier: "square.stack.3d.down.forward")

	static public let square_stack_3d_down_forward_fill = SFSymbol(identifier: "square.stack.3d.down.forward.fill")

	static public let square_stack_3d_forward_dottedline = SFSymbol(identifier: "square.stack.3d.forward.dottedline")

	static public let square_stack_3d_forward_dottedline_fill = SFSymbol(identifier: "square.stack.3d.forward.dottedline.fill")

	static public let deskclock = SFSymbol(identifier: "deskclock")

	static public let deskclock_fill = SFSymbol(identifier: "deskclock.fill")

	static public let timer_square = SFSymbol(identifier: "timer.square")

	static public let l_joystick = SFSymbol(identifier: "l.joystick")

	static public let l_joystick_fill = SFSymbol(identifier: "l.joystick.fill")

	static public let r_joystick = SFSymbol(identifier: "r.joystick")

	static public let r_joystick_fill = SFSymbol(identifier: "r.joystick.fill")

	static public let circle_grid_cross = SFSymbol(identifier: "circle.grid.cross")

	static public let circle_grid_cross_fill = SFSymbol(identifier: "circle.grid.cross.fill")

	static public let dpad = SFSymbol(identifier: "dpad")

	static public let dpad_fill = SFSymbol(identifier: "dpad.fill")

	static public let circle_circle = SFSymbol(identifier: "circle.circle")

	static public let circle_circle_fill = SFSymbol(identifier: "circle.circle.fill")

	static public let square_circle = SFSymbol(identifier: "square.circle")

	static public let square_circle_fill = SFSymbol(identifier: "square.circle.fill")

	static public let triangle_circle = SFSymbol(identifier: "triangle.circle")

	static public let triangle_circle_fill = SFSymbol(identifier: "triangle.circle.fill")

	static public let paintpalette = SFSymbol(identifier: "paintpalette")

	static public let paintpalette_fill = SFSymbol(identifier: "paintpalette.fill")

	static public let cylinder = SFSymbol(identifier: "cylinder")

	static public let cylinder_fill = SFSymbol(identifier: "cylinder.fill")

	static public let cylinder_split_1x2 = SFSymbol(identifier: "cylinder.split.1x2")

	static public let cylinder_split_1x2_fill = SFSymbol(identifier: "cylinder.split.1x2.fill")

	static public let chart_bar_xaxis = SFSymbol(identifier: "chart.bar.xaxis")

	static public let dot_squareshape_split_2x2 = SFSymbol(identifier: "dot.squareshape.split.2x2")

	static public let squareshape_split_2x2 = SFSymbol(identifier: "squareshape.split.2x2")

	static public let squareshape_split_3x3 = SFSymbol(identifier: "squareshape.split.3x3")

	static public let waveform_path_ecg_rectangle = SFSymbol(identifier: "waveform.path.ecg.rectangle")

	static public let waveform_path_ecg_rectangle_fill = SFSymbol(identifier: "waveform.path.ecg.rectangle.fill")

	static public let simcard = SFSymbol(identifier: "simcard")

	static public let simcard_fill = SFSymbol(identifier: "simcard.fill")

	static public let simcard_2 = SFSymbol(identifier: "simcard.2")

	static public let simcard_2_fill = SFSymbol(identifier: "simcard.2.fill")

	static public let sdcard = SFSymbol(identifier: "sdcard")

	static public let sdcard_fill = SFSymbol(identifier: "sdcard.fill")

	static public let esim = SFSymbol(identifier: "esim")

	static public let esim_fill = SFSymbol(identifier: "esim.fill")

	static public let touchid = SFSymbol(identifier: "touchid")

	static public let bonjour = SFSymbol(identifier: "bonjour")

	static public let atom = SFSymbol(identifier: "atom")

	static public let scalemass = SFSymbol(identifier: "scalemass")

	static public let scalemass_fill = SFSymbol(identifier: "scalemass.fill")

	static public let gift_circle = SFSymbol(identifier: "gift.circle")

	static public let gift_circle_fill = SFSymbol(identifier: "gift.circle.fill")

	static public let hourglass_badge_plus = SFSymbol(identifier: "hourglass.badge.plus")

	static public let banknote = SFSymbol(identifier: "banknote")

	static public let banknote_fill = SFSymbol(identifier: "banknote.fill")

	static public let camera_filters = SFSymbol(identifier: "camera.filters")

	static public let arrowtriangle_left_and_line_vertical_and_arrowtriangle_right = SFSymbol(identifier: "arrowtriangle.left.and.line.vertical.and.arrowtriangle.right")

	static public let arrowtriangle_right_and_line_vertical_and_arrowtriangle_left = SFSymbol(identifier: "arrowtriangle.right.and.line.vertical.and.arrowtriangle.left")

	static public let lifepreserver = SFSymbol(identifier: "lifepreserver")

	static public let lifepreserver_fill = SFSymbol(identifier: "lifepreserver.fill")

	static public let dot_arrowtriangles_up_right_down_left_circle = SFSymbol(identifier: "dot.arrowtriangles.up.right.down.left.circle")

	static public let binoculars = SFSymbol(identifier: "binoculars")

	static public let binoculars_fill = SFSymbol(identifier: "binoculars.fill")

	static public let square_fill_text_grid_1x2 = SFSymbol(identifier: "square.fill.text.grid.1x2")

	static public let list_triangle = SFSymbol(identifier: "list.triangle")

	static public let list_number_ar = SFSymbol(identifier: "list.number.ar")

	static public let list_star = SFSymbol(identifier: "list.star")

	static public let text_badge_checkmark_rtl = SFSymbol(identifier: "text.badge.checkmark.rtl")

	static public let text_quote_rtl = SFSymbol(identifier: "text.quote.rtl")

	static public let text_redaction = SFSymbol(identifier: "text.redaction")

	static public let list_and_film = SFSymbol(identifier: "list.and.film")

	static public let shadow = SFSymbol(identifier: "shadow")

	static public let k = SFSymbol(identifier: "k")

	static public let sum_ar = SFSymbol(identifier: "sum.ar")

	static public let percent_ar = SFSymbol(identifier: "percent.ar")

	static public let paragraphsign = SFSymbol(identifier: "paragraphsign")

	static public let at_circle = SFSymbol(identifier: "at.circle")

	static public let at_circle_fill = SFSymbol(identifier: "at.circle.fill")

	static public let questionmark_ar = SFSymbol(identifier: "questionmark.ar")

	static public let questionmark_circle_ar = SFSymbol(identifier: "questionmark.circle.ar")

	static public let questionmark_circle_fill_ar = SFSymbol(identifier: "questionmark.circle.fill.ar")

	static public let questionmark_square_ar = SFSymbol(identifier: "questionmark.square.ar")

	static public let questionmark_square_fill_ar = SFSymbol(identifier: "questionmark.square.fill.ar")

	static public let questionmark_diamond_ar = SFSymbol(identifier: "questionmark.diamond.ar")

	static public let questionmark_diamond_fill_ar = SFSymbol(identifier: "questionmark.diamond.fill.ar")

	static public let exclamationmark_2 = SFSymbol(identifier: "exclamationmark.2")

	static public let exclamationmark_3 = SFSymbol(identifier: "exclamationmark.3")

	static public let plus_rectangle_portrait = SFSymbol(identifier: "plus.rectangle.portrait")

	static public let plus_rectangle_portrait_fill = SFSymbol(identifier: "plus.rectangle.portrait.fill")

	static public let plus_diamond = SFSymbol(identifier: "plus.diamond")

	static public let plus_diamond_fill = SFSymbol(identifier: "plus.diamond.fill")

	static public let minus_rectangle_portrait = SFSymbol(identifier: "minus.rectangle.portrait")

	static public let minus_rectangle_portrait_fill = SFSymbol(identifier: "minus.rectangle.portrait.fill")

	static public let minus_diamond = SFSymbol(identifier: "minus.diamond")

	static public let minus_diamond_fill = SFSymbol(identifier: "minus.diamond.fill")

	static public let curlybraces = SFSymbol(identifier: "curlybraces")

	static public let curlybraces_square = SFSymbol(identifier: "curlybraces.square")

	static public let curlybraces_square_fill = SFSymbol(identifier: "curlybraces.square.fill")

	static public let xmark_rectangle_portrait = SFSymbol(identifier: "xmark.rectangle.portrait")

	static public let xmark_rectangle_portrait_fill = SFSymbol(identifier: "xmark.rectangle.portrait.fill")

	static public let xmark_diamond = SFSymbol(identifier: "xmark.diamond")

	static public let xmark_diamond_fill = SFSymbol(identifier: "xmark.diamond.fill")

	static public let checkmark_rectangle_portrait = SFSymbol(identifier: "checkmark.rectangle.portrait")

	static public let checkmark_rectangle_portrait_fill = SFSymbol(identifier: "checkmark.rectangle.portrait.fill")

	static public let chevron_backward = SFSymbol(identifier: "chevron.backward")

	static public let chevron_backward_circle = SFSymbol(identifier: "chevron.backward.circle")

	static public let chevron_backward_circle_fill = SFSymbol(identifier: "chevron.backward.circle.fill")

	static public let chevron_backward_square = SFSymbol(identifier: "chevron.backward.square")

	static public let chevron_backward_square_fill = SFSymbol(identifier: "chevron.backward.square.fill")

	static public let chevron_forward = SFSymbol(identifier: "chevron.forward")

	static public let chevron_forward_circle = SFSymbol(identifier: "chevron.forward.circle")

	static public let chevron_forward_circle_fill = SFSymbol(identifier: "chevron.forward.circle.fill")

	static public let chevron_forward_square = SFSymbol(identifier: "chevron.forward.square")

	static public let chevron_forward_square_fill = SFSymbol(identifier: "chevron.forward.square.fill")

	static public let chevron_backward_2 = SFSymbol(identifier: "chevron.backward.2")

	static public let chevron_forward_2 = SFSymbol(identifier: "chevron.forward.2")

	static public let arrow_backward = SFSymbol(identifier: "arrow.backward")

	static public let arrow_backward_circle = SFSymbol(identifier: "arrow.backward.circle")

	static public let arrow_backward_circle_fill = SFSymbol(identifier: "arrow.backward.circle.fill")

	static public let arrow_backward_square = SFSymbol(identifier: "arrow.backward.square")

	static public let arrow_backward_square_fill = SFSymbol(identifier: "arrow.backward.square.fill")

	static public let arrow_forward = SFSymbol(identifier: "arrow.forward")

	static public let arrow_forward_circle = SFSymbol(identifier: "arrow.forward.circle")

	static public let arrow_forward_circle_fill = SFSymbol(identifier: "arrow.forward.circle.fill")

	static public let arrow_forward_square = SFSymbol(identifier: "arrow.forward.square")

	static public let arrow_forward_square_fill = SFSymbol(identifier: "arrow.forward.square.fill")

	static public let arrow_up_backward = SFSymbol(identifier: "arrow.up.backward")

	static public let arrow_up_backward_circle = SFSymbol(identifier: "arrow.up.backward.circle")

	static public let arrow_up_backward_circle_fill = SFSymbol(identifier: "arrow.up.backward.circle.fill")

	static public let arrow_up_backward_square = SFSymbol(identifier: "arrow.up.backward.square")

	static public let arrow_up_backward_square_fill = SFSymbol(identifier: "arrow.up.backward.square.fill")

	static public let arrow_up_forward = SFSymbol(identifier: "arrow.up.forward")

	static public let arrow_up_forward_circle = SFSymbol(identifier: "arrow.up.forward.circle")

	static public let arrow_up_forward_circle_fill = SFSymbol(identifier: "arrow.up.forward.circle.fill")

	static public let arrow_up_forward_square = SFSymbol(identifier: "arrow.up.forward.square")

	static public let arrow_up_forward_square_fill = SFSymbol(identifier: "arrow.up.forward.square.fill")

	static public let arrow_down_backward = SFSymbol(identifier: "arrow.down.backward")

	static public let arrow_down_backward_circle = SFSymbol(identifier: "arrow.down.backward.circle")

	static public let arrow_down_backward_circle_fill = SFSymbol(identifier: "arrow.down.backward.circle.fill")

	static public let arrow_down_backward_square = SFSymbol(identifier: "arrow.down.backward.square")

	static public let arrow_down_backward_square_fill = SFSymbol(identifier: "arrow.down.backward.square.fill")

	static public let arrow_down_forward = SFSymbol(identifier: "arrow.down.forward")

	static public let arrow_down_forward_circle = SFSymbol(identifier: "arrow.down.forward.circle")

	static public let arrow_down_forward_circle_fill = SFSymbol(identifier: "arrow.down.forward.circle.fill")

	static public let arrow_down_forward_square = SFSymbol(identifier: "arrow.down.forward.square")

	static public let arrow_down_forward_square_fill = SFSymbol(identifier: "arrow.down.forward.square.fill")

	static public let arrow_left_arrow_right = SFSymbol(identifier: "arrow.left.arrow.right")

	static public let arrow_left_arrow_right_circle = SFSymbol(identifier: "arrow.left.arrow.right.circle")

	static public let arrow_left_arrow_right_circle_fill = SFSymbol(identifier: "arrow.left.arrow.right.circle.fill")

	static public let arrow_left_arrow_right_square = SFSymbol(identifier: "arrow.left.arrow.right.square")

	static public let arrow_left_arrow_right_square_fill = SFSymbol(identifier: "arrow.left.arrow.right.square.fill")

	static public let arrow_uturn_backward = SFSymbol(identifier: "arrow.uturn.backward")

	static public let arrow_uturn_backward_circle = SFSymbol(identifier: "arrow.uturn.backward.circle")

	static public let arrow_uturn_backward_circle_fill = SFSymbol(identifier: "arrow.uturn.backward.circle.fill")

	static public let arrow_uturn_backward_circle_badge_ellipsis = SFSymbol(identifier: "arrow.uturn.backward.circle.badge.ellipsis")

	static public let arrow_uturn_backward_square = SFSymbol(identifier: "arrow.uturn.backward.square")

	static public let arrow_uturn_backward_square_fill = SFSymbol(identifier: "arrow.uturn.backward.square.fill")

	static public let arrow_uturn_forward = SFSymbol(identifier: "arrow.uturn.forward")

	static public let arrow_uturn_forward_circle = SFSymbol(identifier: "arrow.uturn.forward.circle")

	static public let arrow_uturn_forward_circle_fill = SFSymbol(identifier: "arrow.uturn.forward.circle.fill")

	static public let arrow_uturn_forward_square = SFSymbol(identifier: "arrow.uturn.forward.square")

	static public let arrow_uturn_forward_square_fill = SFSymbol(identifier: "arrow.uturn.forward.square.fill")

	static public let arrow_up_and_down_and_arrow_left_and_right = SFSymbol(identifier: "arrow.up.and.down.and.arrow.left.and.right")

	static public let arrow_up_left_and_down_right_and_arrow_up_right_and_down_left = SFSymbol(identifier: "arrow.up.left.and.down.right.and.arrow.up.right.and.down.left")

	static public let arrow_up_left_and_arrow_down_right_circle = SFSymbol(identifier: "arrow.up.left.and.arrow.down.right.circle")

	static public let arrow_up_left_and_arrow_down_right_circle_fill = SFSymbol(identifier: "arrow.up.left.and.arrow.down.right.circle.fill")

	static public let arrow_up_backward_and_arrow_down_forward = SFSymbol(identifier: "arrow.up.backward.and.arrow.down.forward")

	static public let arrow_up_backward_and_arrow_down_forward_circle = SFSymbol(identifier: "arrow.up.backward.and.arrow.down.forward.circle")

	static public let arrow_up_backward_and_arrow_down_forward_circle_fill = SFSymbol(identifier: "arrow.up.backward.and.arrow.down.forward.circle.fill")

	static public let arrow_down_right_and_arrow_up_left_circle = SFSymbol(identifier: "arrow.down.right.and.arrow.up.left.circle")

	static public let arrow_down_right_and_arrow_up_left_circle_fill = SFSymbol(identifier: "arrow.down.right.and.arrow.up.left.circle.fill")

	static public let arrow_down_forward_and_arrow_up_backward = SFSymbol(identifier: "arrow.down.forward.and.arrow.up.backward")

	static public let arrow_down_forward_and_arrow_up_backward_circle = SFSymbol(identifier: "arrow.down.forward.and.arrow.up.backward.circle")

	static public let arrow_down_forward_and_arrow_up_backward_circle_fill = SFSymbol(identifier: "arrow.down.forward.and.arrow.up.backward.circle.fill")

	static public let arrowtriangle_backward = SFSymbol(identifier: "arrowtriangle.backward")

	static public let arrowtriangle_backward_fill = SFSymbol(identifier: "arrowtriangle.backward.fill")

	static public let arrowtriangle_backward_circle = SFSymbol(identifier: "arrowtriangle.backward.circle")

	static public let arrowtriangle_backward_circle_fill = SFSymbol(identifier: "arrowtriangle.backward.circle.fill")

	static public let arrowtriangle_backward_square = SFSymbol(identifier: "arrowtriangle.backward.square")

	static public let arrowtriangle_backward_square_fill = SFSymbol(identifier: "arrowtriangle.backward.square.fill")

	static public let arrowtriangle_forward = SFSymbol(identifier: "arrowtriangle.forward")

	static public let arrowtriangle_forward_fill = SFSymbol(identifier: "arrowtriangle.forward.fill")

	static public let arrowtriangle_forward_circle = SFSymbol(identifier: "arrowtriangle.forward.circle")

	static public let arrowtriangle_forward_circle_fill = SFSymbol(identifier: "arrowtriangle.forward.circle.fill")

	static public let arrowtriangle_forward_square = SFSymbol(identifier: "arrowtriangle.forward.square")

	static public let arrowtriangle_forward_square_fill = SFSymbol(identifier: "arrowtriangle.forward.square.fill")

	static public let shekelsign_circle = SFSymbol(identifier: "shekelsign.circle")

	static public let shekelsign_circle_fill = SFSymbol(identifier: "shekelsign.circle.fill")

	static public let shekelsign_square = SFSymbol(identifier: "shekelsign.square")

	static public let shekelsign_square_fill = SFSymbol(identifier: "shekelsign.square.fill")
}