//
//  SFSymbols.2022.swift
//
//  Automatically generated by sf-symbol-member-gen
//  Do not edit directly!
//  swift-format-ignore-file

@_documentation(visibility: internal)
@available(iOS 16.0, macOS 13.0, tvOS 16.0, visionOS 1.0, watchOS 9.0, *)
extension SFSymbol {
	static public let rectangle_portrait_and_arrow_forward = SFSymbol(identifier: "rectangle.portrait.and.arrow.forward")

	static public let rectangle_portrait_and_arrow_forward_fill = SFSymbol(identifier: "rectangle.portrait.and.arrow.forward.fill")

	static public let pencil_line = SFSymbol(identifier: "pencil.line")

	static public let eraser = SFSymbol(identifier: "eraser")

	static public let eraser_fill = SFSymbol(identifier: "eraser.fill")

	static public let eraser_line_dashed = SFSymbol(identifier: "eraser.line.dashed")

	static public let eraser_line_dashed_fill = SFSymbol(identifier: "eraser.line.dashed.fill")

	static public let square_and_pencil_circle = SFSymbol(identifier: "square.and.pencil.circle")

	static public let square_and_pencil_circle_fill = SFSymbol(identifier: "square.and.pencil.circle.fill")

	static public let externaldrive_badge_questionmark = SFSymbol(identifier: "externaldrive.badge.questionmark")

	static public let externaldrive_fill_badge_questionmark = SFSymbol(identifier: "externaldrive.fill.badge.questionmark")

	static public let externaldrive_badge_questionmark_ar = SFSymbol(identifier: "externaldrive.badge.questionmark.ar")

	static public let externaldrive_fill_badge_questionmark_ar = SFSymbol(identifier: "externaldrive.fill.badge.questionmark.ar")

	static public let externaldrive_badge_exclamationmark = SFSymbol(identifier: "externaldrive.badge.exclamationmark")

	static public let externaldrive_fill_badge_exclamationmark = SFSymbol(identifier: "externaldrive.fill.badge.exclamationmark")

	static public let externaldrive_trianglebadge_exclamationmark = SFSymbol(identifier: "externaldrive.trianglebadge.exclamationmark")

	static public let externaldrive_fill_trianglebadge_exclamationmark = SFSymbol(identifier: "externaldrive.fill.trianglebadge.exclamationmark")

	static public let clipboard = SFSymbol(identifier: "clipboard")

	static public let clipboard_fill = SFSymbol(identifier: "clipboard.fill")

	static public let list_bullet_clipboard = SFSymbol(identifier: "list.bullet.clipboard")

	static public let list_bullet_clipboard_fill = SFSymbol(identifier: "list.bullet.clipboard.fill")

	static public let list_clipboard = SFSymbol(identifier: "list.clipboard")

	static public let list_clipboard_fill = SFSymbol(identifier: "list.clipboard.fill")

	static public let arrowshape_left = SFSymbol(identifier: "arrowshape.left")

	static public let arrowshape_left_fill = SFSymbol(identifier: "arrowshape.left.fill")

	static public let arrowshape_backward = SFSymbol(identifier: "arrowshape.backward")

	static public let arrowshape_backward_fill = SFSymbol(identifier: "arrowshape.backward.fill")

	static public let arrowshape_right = SFSymbol(identifier: "arrowshape.right")

	static public let arrowshape_right_fill = SFSymbol(identifier: "arrowshape.right.fill")

	static public let arrowshape_forward = SFSymbol(identifier: "arrowshape.forward")

	static public let arrowshape_forward_fill = SFSymbol(identifier: "arrowshape.forward.fill")

	static public let arrowshape_turn_up_backward_badge_clock = SFSymbol(identifier: "arrowshape.turn.up.backward.badge.clock")

	static public let arrowshape_turn_up_backward_badge_clock_fill = SFSymbol(identifier: "arrowshape.turn.up.backward.badge.clock.fill")

	static public let arrowshape_turn_up_backward_badge_clock_rtl = SFSymbol(identifier: "arrowshape.turn.up.backward.badge.clock.rtl")

	static public let arrowshape_turn_up_backward_badge_clock_fill_rtl = SFSymbol(identifier: "arrowshape.turn.up.backward.badge.clock.fill.rtl")

	static public let pencil_and_ruler = SFSymbol(identifier: "pencil.and.ruler")

	static public let pencil_and_ruler_fill = SFSymbol(identifier: "pencil.and.ruler.fill")

	static public let backpack = SFSymbol(identifier: "backpack")

	static public let backpack_fill = SFSymbol(identifier: "backpack.fill")

	static public let person_badge_shield_checkmark = SFSymbol(identifier: "person.badge.shield.checkmark")

	static public let person_badge_shield_checkmark_fill = SFSymbol(identifier: "person.badge.shield.checkmark.fill")

	static public let person_2_slash = SFSymbol(identifier: "person.2.slash")

	static public let person_2_slash_fill = SFSymbol(identifier: "person.2.slash.fill")

	static public let person_2_badge_gearshape = SFSymbol(identifier: "person.2.badge.gearshape")

	static public let person_2_badge_gearshape_fill = SFSymbol(identifier: "person.2.badge.gearshape.fill")

	static public let person_line_dotted_person = SFSymbol(identifier: "person.line.dotted.person")

	static public let person_line_dotted_person_fill = SFSymbol(identifier: "person.line.dotted.person.fill")

	static public let person_bust = SFSymbol(identifier: "person.bust")

	static public let person_bust_fill = SFSymbol(identifier: "person.bust.fill")

	static public let person_crop_rectangle_badge_plus = SFSymbol(identifier: "person.crop.rectangle.badge.plus")

	static public let person_crop_rectangle_badge_plus_fill = SFSymbol(identifier: "person.crop.rectangle.badge.plus.fill")

	static public let person_and_background_dotted = SFSymbol(identifier: "person.and.background.dotted")

	static public let figure_arms_open = SFSymbol(identifier: "figure.arms.open")

	static public let figure_2_arms_open = SFSymbol(identifier: "figure.2.arms.open")

	static public let figure_2_and_child_holdinghands = SFSymbol(identifier: "figure.2.and.child.holdinghands")

	static public let figure_and_child_holdinghands = SFSymbol(identifier: "figure.and.child.holdinghands")

	static public let figure_walk_arrival = SFSymbol(identifier: "figure.walk.arrival")

	static public let figure_walk_departure = SFSymbol(identifier: "figure.walk.departure")

	static public let figure_walk_motion = SFSymbol(identifier: "figure.walk.motion")

	static public let figure_fall = SFSymbol(identifier: "figure.fall")

	static public let figure_fall_circle = SFSymbol(identifier: "figure.fall.circle")

	static public let figure_fall_circle_fill = SFSymbol(identifier: "figure.fall.circle.fill")

	static public let figure_run = SFSymbol(identifier: "figure.run")

	static public let figure_run_circle = SFSymbol(identifier: "figure.run.circle")

	static public let figure_run_circle_fill = SFSymbol(identifier: "figure.run.circle.fill")

	static public let figure_roll_runningpace = SFSymbol(identifier: "figure.roll.runningpace")

	static public let figure_american_football = SFSymbol(identifier: "figure.american.football")

	static public let figure_archery = SFSymbol(identifier: "figure.archery")

	static public let figure_australian_football = SFSymbol(identifier: "figure.australian.football")

	static public let figure_badminton = SFSymbol(identifier: "figure.badminton")

	static public let figure_barre = SFSymbol(identifier: "figure.barre")

	static public let figure_baseball = SFSymbol(identifier: "figure.baseball")

	static public let figure_basketball = SFSymbol(identifier: "figure.basketball")

	static public let figure_bowling = SFSymbol(identifier: "figure.bowling")

	static public let figure_boxing = SFSymbol(identifier: "figure.boxing")

	static public let figure_climbing = SFSymbol(identifier: "figure.climbing")

	static public let figure_cooldown = SFSymbol(identifier: "figure.cooldown")

	static public let figure_core_training = SFSymbol(identifier: "figure.core.training")

	static public let figure_cricket = SFSymbol(identifier: "figure.cricket")

	static public let figure_skiing_crosscountry = SFSymbol(identifier: "figure.skiing.crosscountry")

	static public let figure_cross_training = SFSymbol(identifier: "figure.cross.training")

	static public let figure_curling = SFSymbol(identifier: "figure.curling")

	static public let figure_dance = SFSymbol(identifier: "figure.dance")

	static public let figure_disc_sports = SFSymbol(identifier: "figure.disc.sports")

	static public let figure_skiing_downhill = SFSymbol(identifier: "figure.skiing.downhill")

	static public let figure_elliptical = SFSymbol(identifier: "figure.elliptical")

	static public let figure_equestrian_sports = SFSymbol(identifier: "figure.equestrian.sports")

	static public let figure_fencing = SFSymbol(identifier: "figure.fencing")

	static public let figure_fishing = SFSymbol(identifier: "figure.fishing")

	static public let figure_flexibility = SFSymbol(identifier: "figure.flexibility")

	static public let figure_strengthtraining_functional = SFSymbol(identifier: "figure.strengthtraining.functional")

	static public let figure_golf = SFSymbol(identifier: "figure.golf")

	static public let figure_gymnastics = SFSymbol(identifier: "figure.gymnastics")

	static public let figure_hand_cycling = SFSymbol(identifier: "figure.hand.cycling")

	static public let figure_handball = SFSymbol(identifier: "figure.handball")

	static public let figure_highintensity_intervaltraining = SFSymbol(identifier: "figure.highintensity.intervaltraining")

	static public let figure_hiking = SFSymbol(identifier: "figure.hiking")

	static public let figure_hockey = SFSymbol(identifier: "figure.hockey")

	static public let figure_hunting = SFSymbol(identifier: "figure.hunting")

	static public let figure_indoor_cycle = SFSymbol(identifier: "figure.indoor.cycle")

	static public let figure_jumprope = SFSymbol(identifier: "figure.jumprope")

	static public let figure_kickboxing = SFSymbol(identifier: "figure.kickboxing")

	static public let figure_lacrosse = SFSymbol(identifier: "figure.lacrosse")

	static public let figure_martial_arts = SFSymbol(identifier: "figure.martial.arts")

	static public let figure_mind_and_body = SFSymbol(identifier: "figure.mind.and.body")

	static public let figure_mixed_cardio = SFSymbol(identifier: "figure.mixed.cardio")

	static public let figure_open_water_swim = SFSymbol(identifier: "figure.open.water.swim")

	static public let figure_outdoor_cycle = SFSymbol(identifier: "figure.outdoor.cycle")

	static public let oar_2_crossed = SFSymbol(identifier: "oar.2.crossed")

	static public let figure_pickleball = SFSymbol(identifier: "figure.pickleball")

	static public let figure_pilates = SFSymbol(identifier: "figure.pilates")

	static public let figure_play = SFSymbol(identifier: "figure.play")

	static public let figure_pool_swim = SFSymbol(identifier: "figure.pool.swim")

	static public let figure_racquetball = SFSymbol(identifier: "figure.racquetball")

	static public let figure_rolling = SFSymbol(identifier: "figure.rolling")

	static public let figure_rugby = SFSymbol(identifier: "figure.rugby")

	static public let figure_sailing = SFSymbol(identifier: "figure.sailing")

	static public let figure_snowboarding = SFSymbol(identifier: "figure.snowboarding")

	static public let figure_socialdance = SFSymbol(identifier: "figure.socialdance")

	static public let figure_softball = SFSymbol(identifier: "figure.softball")

	static public let figure_squash = SFSymbol(identifier: "figure.squash")

	static public let figure_stair_stepper = SFSymbol(identifier: "figure.stair.stepper")

	static public let figure_stairs = SFSymbol(identifier: "figure.stairs")

	static public let figure_step_training = SFSymbol(identifier: "figure.step.training")

	static public let figure_surfing = SFSymbol(identifier: "figure.surfing")

	static public let figure_table_tennis = SFSymbol(identifier: "figure.table.tennis")

	static public let figure_taichi = SFSymbol(identifier: "figure.taichi")

	static public let figure_tennis = SFSymbol(identifier: "figure.tennis")

	static public let figure_track_and_field = SFSymbol(identifier: "figure.track.and.field")

	static public let figure_strengthtraining_traditional = SFSymbol(identifier: "figure.strengthtraining.traditional")

	static public let figure_volleyball = SFSymbol(identifier: "figure.volleyball")

	static public let figure_water_fitness = SFSymbol(identifier: "figure.water.fitness")

	static public let figure_waterpolo = SFSymbol(identifier: "figure.waterpolo")

	static public let figure_wrestling = SFSymbol(identifier: "figure.wrestling")

	static public let figure_yoga = SFSymbol(identifier: "figure.yoga")

	static public let baseball_diamond_bases = SFSymbol(identifier: "baseball.diamond.bases")

	static public let dumbbell = SFSymbol(identifier: "dumbbell")

	static public let dumbbell_fill = SFSymbol(identifier: "dumbbell.fill")

	static public let sportscourt_circle = SFSymbol(identifier: "sportscourt.circle")

	static public let sportscourt_circle_fill = SFSymbol(identifier: "sportscourt.circle.fill")

	static public let soccerball = SFSymbol(identifier: "soccerball")

	static public let soccerball_inverse = SFSymbol(identifier: "soccerball.inverse")

	static public let soccerball_circle = SFSymbol(identifier: "soccerball.circle")

	static public let soccerball_circle_inverse = SFSymbol(identifier: "soccerball.circle.inverse")

	static public let soccerball_circle_fill = SFSymbol(identifier: "soccerball.circle.fill")

	static public let soccerball_circle_fill_inverse = SFSymbol(identifier: "soccerball.circle.fill.inverse")

	static public let baseball = SFSymbol(identifier: "baseball")

	static public let baseball_fill = SFSymbol(identifier: "baseball.fill")

	static public let baseball_circle = SFSymbol(identifier: "baseball.circle")

	static public let baseball_circle_fill = SFSymbol(identifier: "baseball.circle.fill")

	static public let basketball = SFSymbol(identifier: "basketball")

	static public let basketball_fill = SFSymbol(identifier: "basketball.fill")

	static public let basketball_circle = SFSymbol(identifier: "basketball.circle")

	static public let basketball_circle_fill = SFSymbol(identifier: "basketball.circle.fill")

	static public let tennis_racket = SFSymbol(identifier: "tennis.racket")

	static public let tennis_racket_circle = SFSymbol(identifier: "tennis.racket.circle")

	static public let tennis_racket_circle_fill = SFSymbol(identifier: "tennis.racket.circle.fill")

	static public let hockey_puck = SFSymbol(identifier: "hockey.puck")

	static public let hockey_puck_fill = SFSymbol(identifier: "hockey.puck.fill")

	static public let hockey_puck_circle = SFSymbol(identifier: "hockey.puck.circle")

	static public let hockey_puck_circle_fill = SFSymbol(identifier: "hockey.puck.circle.fill")

	static public let cricket_ball = SFSymbol(identifier: "cricket.ball")

	static public let cricket_ball_fill = SFSymbol(identifier: "cricket.ball.fill")

	static public let cricket_ball_circle = SFSymbol(identifier: "cricket.ball.circle")

	static public let cricket_ball_circle_fill = SFSymbol(identifier: "cricket.ball.circle.fill")

	static public let tennisball = SFSymbol(identifier: "tennisball")

	static public let tennisball_fill = SFSymbol(identifier: "tennisball.fill")

	static public let tennisball_circle = SFSymbol(identifier: "tennisball.circle")

	static public let tennisball_circle_fill = SFSymbol(identifier: "tennisball.circle.fill")

	static public let volleyball = SFSymbol(identifier: "volleyball")

	static public let volleyball_fill = SFSymbol(identifier: "volleyball.fill")

	static public let volleyball_circle = SFSymbol(identifier: "volleyball.circle")

	static public let volleyball_circle_fill = SFSymbol(identifier: "volleyball.circle.fill")

	static public let trophy = SFSymbol(identifier: "trophy")

	static public let trophy_fill = SFSymbol(identifier: "trophy.fill")

	static public let trophy_circle = SFSymbol(identifier: "trophy.circle")

	static public let trophy_circle_fill = SFSymbol(identifier: "trophy.circle.fill")

	static public let medal = SFSymbol(identifier: "medal")

	static public let medal_fill = SFSymbol(identifier: "medal.fill")

	static public let space = SFSymbol(identifier: "space")

	static public let chevron_left_to_line = SFSymbol(identifier: "chevron.left.to.line")

	static public let chevron_right_to_line = SFSymbol(identifier: "chevron.right.to.line")

	static public let chevron_backward_to_line = SFSymbol(identifier: "chevron.backward.to.line")

	static public let chevron_forward_to_line = SFSymbol(identifier: "chevron.forward.to.line")

	static public let keyboard_badge_ellipsis_fill = SFSymbol(identifier: "keyboard.badge.ellipsis.fill")

	static public let keyboard_badge_eye = SFSymbol(identifier: "keyboard.badge.eye")

	static public let keyboard_badge_eye_fill = SFSymbol(identifier: "keyboard.badge.eye.fill")

	static public let keyboard_chevron_compact_down_fill = SFSymbol(identifier: "keyboard.chevron.compact.down.fill")

	static public let keyboard_chevron_compact_left_fill = SFSymbol(identifier: "keyboard.chevron.compact.left.fill")

	static public let keyboard_onehanded_left_fill = SFSymbol(identifier: "keyboard.onehanded.left.fill")

	static public let keyboard_onehanded_right_fill = SFSymbol(identifier: "keyboard.onehanded.right.fill")

	static public let globe_central_south_asia = SFSymbol(identifier: "globe.central.south.asia")

	static public let globe_central_south_asia_fill = SFSymbol(identifier: "globe.central.south.asia.fill")

	static public let sun_max_trianglebadge_exclamationmark = SFSymbol(identifier: "sun.max.trianglebadge.exclamationmark")

	static public let sun_max_trianglebadge_exclamationmark_fill = SFSymbol(identifier: "sun.max.trianglebadge.exclamationmark.fill")

	static public let sunrise_circle = SFSymbol(identifier: "sunrise.circle")

	static public let sunrise_circle_fill = SFSymbol(identifier: "sunrise.circle.fill")

	static public let sunset_circle = SFSymbol(identifier: "sunset.circle")

	static public let sunset_circle_fill = SFSymbol(identifier: "sunset.circle.fill")

	static public let sun_dust_circle = SFSymbol(identifier: "sun.dust.circle")

	static public let sun_dust_circle_fill = SFSymbol(identifier: "sun.dust.circle.fill")

	static public let sun_haze_circle = SFSymbol(identifier: "sun.haze.circle")

	static public let sun_haze_circle_fill = SFSymbol(identifier: "sun.haze.circle.fill")

	static public let moonphase_new_moon = SFSymbol(identifier: "moonphase.new.moon")

	static public let moonphase_waxing_crescent = SFSymbol(identifier: "moonphase.waxing.crescent")

	static public let moonphase_first_quarter = SFSymbol(identifier: "moonphase.first.quarter")

	static public let moonphase_waxing_gibbous = SFSymbol(identifier: "moonphase.waxing.gibbous")

	static public let moonphase_full_moon = SFSymbol(identifier: "moonphase.full.moon")

	static public let moonphase_waning_gibbous = SFSymbol(identifier: "moonphase.waning.gibbous")

	static public let moonphase_last_quarter = SFSymbol(identifier: "moonphase.last.quarter")

	static public let moonphase_waning_crescent = SFSymbol(identifier: "moonphase.waning.crescent")

	static public let moonphase_new_moon_inverse = SFSymbol(identifier: "moonphase.new.moon.inverse")

	static public let moonphase_waxing_crescent_inverse = SFSymbol(identifier: "moonphase.waxing.crescent.inverse")

	static public let moonphase_first_quarter_inverse = SFSymbol(identifier: "moonphase.first.quarter.inverse")

	static public let moonphase_waxing_gibbous_inverse = SFSymbol(identifier: "moonphase.waxing.gibbous.inverse")

	static public let moonphase_full_moon_inverse = SFSymbol(identifier: "moonphase.full.moon.inverse")

	static public let moonphase_waning_gibbous_inverse = SFSymbol(identifier: "moonphase.waning.gibbous.inverse")

	static public let moonphase_last_quarter_inverse = SFSymbol(identifier: "moonphase.last.quarter.inverse")

	static public let moonphase_waning_crescent_inverse = SFSymbol(identifier: "moonphase.waning.crescent.inverse")

	static public let moon_haze = SFSymbol(identifier: "moon.haze")

	static public let moon_haze_fill = SFSymbol(identifier: "moon.haze.fill")

	static public let moon_haze_circle = SFSymbol(identifier: "moon.haze.circle")

	static public let moon_haze_circle_fill = SFSymbol(identifier: "moon.haze.circle.fill")

	static public let moon_stars_circle = SFSymbol(identifier: "moon.stars.circle")

	static public let moon_stars_circle_fill = SFSymbol(identifier: "moon.stars.circle.fill")

	static public let cloud_circle = SFSymbol(identifier: "cloud.circle")

	static public let cloud_circle_fill = SFSymbol(identifier: "cloud.circle.fill")

	static public let cloud_drizzle_circle = SFSymbol(identifier: "cloud.drizzle.circle")

	static public let cloud_drizzle_circle_fill = SFSymbol(identifier: "cloud.drizzle.circle.fill")

	static public let cloud_rain_circle = SFSymbol(identifier: "cloud.rain.circle")

	static public let cloud_rain_circle_fill = SFSymbol(identifier: "cloud.rain.circle.fill")

	static public let cloud_heavyrain_circle = SFSymbol(identifier: "cloud.heavyrain.circle")

	static public let cloud_heavyrain_circle_fill = SFSymbol(identifier: "cloud.heavyrain.circle.fill")

	static public let cloud_fog_circle = SFSymbol(identifier: "cloud.fog.circle")

	static public let cloud_fog_circle_fill = SFSymbol(identifier: "cloud.fog.circle.fill")

	static public let cloud_hail_circle = SFSymbol(identifier: "cloud.hail.circle")

	static public let cloud_hail_circle_fill = SFSymbol(identifier: "cloud.hail.circle.fill")

	static public let cloud_snow_circle = SFSymbol(identifier: "cloud.snow.circle")

	static public let cloud_snow_circle_fill = SFSymbol(identifier: "cloud.snow.circle.fill")

	static public let cloud_sleet_circle = SFSymbol(identifier: "cloud.sleet.circle")

	static public let cloud_sleet_circle_fill = SFSymbol(identifier: "cloud.sleet.circle.fill")

	static public let cloud_bolt_circle = SFSymbol(identifier: "cloud.bolt.circle")

	static public let cloud_bolt_circle_fill = SFSymbol(identifier: "cloud.bolt.circle.fill")

	static public let cloud_bolt_rain_circle = SFSymbol(identifier: "cloud.bolt.rain.circle")

	static public let cloud_bolt_rain_circle_fill = SFSymbol(identifier: "cloud.bolt.rain.circle.fill")

	static public let cloud_sun_circle = SFSymbol(identifier: "cloud.sun.circle")

	static public let cloud_sun_circle_fill = SFSymbol(identifier: "cloud.sun.circle.fill")

	static public let cloud_sun_rain_circle = SFSymbol(identifier: "cloud.sun.rain.circle")

	static public let cloud_sun_rain_circle_fill = SFSymbol(identifier: "cloud.sun.rain.circle.fill")

	static public let cloud_sun_bolt_circle = SFSymbol(identifier: "cloud.sun.bolt.circle")

	static public let cloud_sun_bolt_circle_fill = SFSymbol(identifier: "cloud.sun.bolt.circle.fill")

	static public let cloud_moon_circle = SFSymbol(identifier: "cloud.moon.circle")

	static public let cloud_moon_circle_fill = SFSymbol(identifier: "cloud.moon.circle.fill")

	static public let cloud_moon_rain_circle = SFSymbol(identifier: "cloud.moon.rain.circle")

	static public let cloud_moon_rain_circle_fill = SFSymbol(identifier: "cloud.moon.rain.circle.fill")

	static public let cloud_moon_bolt_circle = SFSymbol(identifier: "cloud.moon.bolt.circle")

	static public let cloud_moon_bolt_circle_fill = SFSymbol(identifier: "cloud.moon.bolt.circle.fill")

	static public let smoke_circle = SFSymbol(identifier: "smoke.circle")

	static public let smoke_circle_fill = SFSymbol(identifier: "smoke.circle.fill")

	static public let wind_circle = SFSymbol(identifier: "wind.circle")

	static public let wind_circle_fill = SFSymbol(identifier: "wind.circle.fill")

	static public let wind_snow_circle = SFSymbol(identifier: "wind.snow.circle")

	static public let wind_snow_circle_fill = SFSymbol(identifier: "wind.snow.circle.fill")

	static public let tornado_circle = SFSymbol(identifier: "tornado.circle")

	static public let tornado_circle_fill = SFSymbol(identifier: "tornado.circle.fill")

	static public let tropicalstorm_circle = SFSymbol(identifier: "tropicalstorm.circle")

	static public let tropicalstorm_circle_fill = SFSymbol(identifier: "tropicalstorm.circle.fill")

	static public let hurricane_circle = SFSymbol(identifier: "hurricane.circle")

	static public let hurricane_circle_fill = SFSymbol(identifier: "hurricane.circle.fill")

	static public let thermometer_sun_circle = SFSymbol(identifier: "thermometer.sun.circle")

	static public let thermometer_sun_circle_fill = SFSymbol(identifier: "thermometer.sun.circle.fill")

	static public let thermometer_snowflake_circle = SFSymbol(identifier: "thermometer.snowflake.circle")

	static public let thermometer_snowflake_circle_fill = SFSymbol(identifier: "thermometer.snowflake.circle.fill")

	static public let thermometer_low = SFSymbol(identifier: "thermometer.low")

	static public let thermometer_medium = SFSymbol(identifier: "thermometer.medium")

	static public let thermometer_high = SFSymbol(identifier: "thermometer.high")

	static public let thermometer_medium_slash = SFSymbol(identifier: "thermometer.medium.slash")

	static public let water_waves = SFSymbol(identifier: "water.waves")

	static public let water_waves_slash = SFSymbol(identifier: "water.waves.slash")

	static public let drop_degreesign = SFSymbol(identifier: "drop.degreesign")

	static public let drop_degreesign_fill = SFSymbol(identifier: "drop.degreesign.fill")

	static public let drop_degreesign_slash = SFSymbol(identifier: "drop.degreesign.slash")

	static public let drop_degreesign_slash_fill = SFSymbol(identifier: "drop.degreesign.slash.fill")

	static public let drop_degreesign_slash_rtl = SFSymbol(identifier: "drop.degreesign.slash.rtl")

	static public let drop_degreesign_slash_fill_rtl = SFSymbol(identifier: "drop.degreesign.slash.fill.rtl")

	static public let beach_umbrella = SFSymbol(identifier: "beach.umbrella")

	static public let beach_umbrella_fill = SFSymbol(identifier: "beach.umbrella.fill")

	static public let umbrella_percent = SFSymbol(identifier: "umbrella.percent")

	static public let umbrella_percent_fill = SFSymbol(identifier: "umbrella.percent.fill")

	static public let umbrella_percent_ar = SFSymbol(identifier: "umbrella.percent.ar")

	static public let umbrella_percent_fill_ar = SFSymbol(identifier: "umbrella.percent.fill.ar")

	static public let playpause_circle = SFSymbol(identifier: "playpause.circle")

	static public let playpause_circle_fill = SFSymbol(identifier: "playpause.circle.fill")

	static public let backward_end_circle = SFSymbol(identifier: "backward.end.circle")

	static public let backward_end_circle_fill = SFSymbol(identifier: "backward.end.circle.fill")

	static public let forward_end_circle = SFSymbol(identifier: "forward.end.circle")

	static public let forward_end_circle_fill = SFSymbol(identifier: "forward.end.circle.fill")

	static public let speaker_square = SFSymbol(identifier: "speaker.square")

	static public let speaker_square_fill = SFSymbol(identifier: "speaker.square.fill")

	static public let speaker_plus = SFSymbol(identifier: "speaker.plus")

	static public let speaker_plus_fill = SFSymbol(identifier: "speaker.plus.fill")

	static public let speaker_minus = SFSymbol(identifier: "speaker.minus")

	static public let speaker_minus_fill = SFSymbol(identifier: "speaker.minus.fill")

	static public let square_dotted = SFSymbol(identifier: "square.dotted")

	static public let square_on_square_badge_person_crop = SFSymbol(identifier: "square.on.square.badge.person.crop")

	static public let square_on_square_badge_person_crop_fill = SFSymbol(identifier: "square.on.square.badge.person.crop.fill")

	static public let star_square_on_square = SFSymbol(identifier: "star.square.on.square")

	static public let star_square_on_square_fill = SFSymbol(identifier: "star.square.on.square.fill")

	static public let square_on_square_intersection_dashed = SFSymbol(identifier: "square.on.square.intersection.dashed")

	static public let rectangle_portrait_on_rectangle_portrait_angled = SFSymbol(identifier: "rectangle.portrait.on.rectangle.portrait.angled")

	static public let rectangle_portrait_on_rectangle_portrait_angled_fill = SFSymbol(identifier: "rectangle.portrait.on.rectangle.portrait.angled.fill")

	static public let fleuron = SFSymbol(identifier: "fleuron")

	static public let fleuron_fill = SFSymbol(identifier: "fleuron.fill")

	static public let firewall = SFSymbol(identifier: "firewall")

	static public let firewall_fill = SFSymbol(identifier: "firewall.fill")

	static public let flag_2_crossed_circle = SFSymbol(identifier: "flag.2.crossed.circle")

	static public let flag_2_crossed_circle_fill = SFSymbol(identifier: "flag.2.crossed.circle.fill")

	static public let location_slash_circle = SFSymbol(identifier: "location.slash.circle")

	static public let location_slash_circle_fill = SFSymbol(identifier: "location.slash.circle.fill")

	static public let bell_and_waves_left_and_right = SFSymbol(identifier: "bell.and.waves.left.and.right")

	static public let bell_and_waves_left_and_right_fill = SFSymbol(identifier: "bell.and.waves.left.and.right.fill")

	static public let bolt_badge_clock = SFSymbol(identifier: "bolt.badge.clock")

	static public let bolt_badge_clock_fill = SFSymbol(identifier: "bolt.badge.clock.fill")

	static public let message_badge = SFSymbol(identifier: "message.badge")

	static public let message_badge_filled_fill = SFSymbol(identifier: "message.badge.filled.fill")

	static public let message_badge_circle = SFSymbol(identifier: "message.badge.circle")

	static public let message_badge_circle_fill = SFSymbol(identifier: "message.badge.circle.fill")

	static public let message_badge_fill = SFSymbol(identifier: "message.badge.fill")

	static public let message_badge_rtl = SFSymbol(identifier: "message.badge.rtl")

	static public let message_badge_filled_fill_rtl = SFSymbol(identifier: "message.badge.filled.fill.rtl")

	static public let message_badge_circle_rtl = SFSymbol(identifier: "message.badge.circle.rtl")

	static public let message_badge_circle_fill_rtl = SFSymbol(identifier: "message.badge.circle.fill.rtl")

	static public let message_badge_fill_rtl = SFSymbol(identifier: "message.badge.fill.rtl")

	static public let checkmark_message = SFSymbol(identifier: "checkmark.message")

	static public let checkmark_message_fill = SFSymbol(identifier: "checkmark.message.fill")

	static public let arrow_down_message = SFSymbol(identifier: "arrow.down.message")

	static public let arrow_down_message_fill = SFSymbol(identifier: "arrow.down.message.fill")

	static public let ellipsis_message = SFSymbol(identifier: "ellipsis.message")

	static public let ellipsis_message_fill = SFSymbol(identifier: "ellipsis.message.fill")

	static public let info_bubble = SFSymbol(identifier: "info.bubble")

	static public let info_bubble_fill = SFSymbol(identifier: "info.bubble.fill")

	static public let questionmark_bubble = SFSymbol(identifier: "questionmark.bubble")

	static public let questionmark_bubble_fill = SFSymbol(identifier: "questionmark.bubble.fill")

	static public let questionmark_bubble_ar = SFSymbol(identifier: "questionmark.bubble.ar")

	static public let questionmark_bubble_fill_ar = SFSymbol(identifier: "questionmark.bubble.fill.ar")

	static public let phone_badge_checkmark = SFSymbol(identifier: "phone.badge.checkmark")

	static public let phone_fill_badge_checkmark = SFSymbol(identifier: "phone.fill.badge.checkmark")

	static public let phone_connection_fill = SFSymbol(identifier: "phone.connection.fill")

	static public let phone_arrow_up_right_fill = SFSymbol(identifier: "phone.arrow.up.right.fill")

	static public let phone_arrow_up_right_circle = SFSymbol(identifier: "phone.arrow.up.right.circle")

	static public let phone_arrow_up_right_circle_fill = SFSymbol(identifier: "phone.arrow.up.right.circle.fill")

	static public let phone_arrow_down_left_fill = SFSymbol(identifier: "phone.arrow.down.left.fill")

	static public let phone_arrow_right_fill = SFSymbol(identifier: "phone.arrow.right.fill")

	static public let phone_down_waves_left_and_right = SFSymbol(identifier: "phone.down.waves.left.and.right")

	static public let deskview = SFSymbol(identifier: "deskview")

	static public let deskview_fill = SFSymbol(identifier: "deskview.fill")

	static public let envelope_open_badge_clock = SFSymbol(identifier: "envelope.open.badge.clock")

	static public let gear_badge = SFSymbol(identifier: "gear.badge")

	static public let gear_badge_rtl = SFSymbol(identifier: "gear.badge.rtl")

	static public let bag_badge_questionmark = SFSymbol(identifier: "bag.badge.questionmark")

	static public let bag_fill_badge_questionmark = SFSymbol(identifier: "bag.fill.badge.questionmark")

	static public let bag_badge_questionmark_ar = SFSymbol(identifier: "bag.badge.questionmark.ar")

	static public let bag_fill_badge_questionmark_ar = SFSymbol(identifier: "bag.fill.badge.questionmark.ar")

	static public let cart_badge_questionmark = SFSymbol(identifier: "cart.badge.questionmark")

	static public let cart_fill_badge_questionmark = SFSymbol(identifier: "cart.fill.badge.questionmark")

	static public let cart_badge_questionmark_ar = SFSymbol(identifier: "cart.badge.questionmark.ar")

	static public let cart_fill_badge_questionmark_ar = SFSymbol(identifier: "cart.fill.badge.questionmark.ar")

	static public let cart_badge_questionmark_rtl = SFSymbol(identifier: "cart.badge.questionmark.rtl")

	static public let cart_fill_badge_questionmark_rtl = SFSymbol(identifier: "cart.fill.badge.questionmark.rtl")

	static public let basket = SFSymbol(identifier: "basket")

	static public let basket_fill = SFSymbol(identifier: "basket.fill")

	static public let dial_low = SFSymbol(identifier: "dial.low")

	static public let dial_low_fill = SFSymbol(identifier: "dial.low.fill")

	static public let dial_medium = SFSymbol(identifier: "dial.medium")

	static public let dial_medium_fill = SFSymbol(identifier: "dial.medium.fill")

	static public let dial_high = SFSymbol(identifier: "dial.high")

	static public let dial_high_fill = SFSymbol(identifier: "dial.high.fill")

	static public let nosign_app = SFSymbol(identifier: "nosign.app")

	static public let nosign_app_fill = SFSymbol(identifier: "nosign.app.fill")

	static public let wrench_adjustable = SFSymbol(identifier: "wrench.adjustable")

	static public let wrench_adjustable_fill = SFSymbol(identifier: "wrench.adjustable.fill")

	static public let faxmachine_fill = SFSymbol(identifier: "faxmachine.fill")

	static public let theatermask_and_paintbrush = SFSymbol(identifier: "theatermask.and.paintbrush")

	static public let theatermask_and_paintbrush_fill = SFSymbol(identifier: "theatermask.and.paintbrush.fill")

	static public let lightbulb_2 = SFSymbol(identifier: "lightbulb.2")

	static public let lightbulb_2_fill = SFSymbol(identifier: "lightbulb.2.fill")

	static public let lightbulb_led = SFSymbol(identifier: "lightbulb.led")

	static public let lightbulb_led_fill = SFSymbol(identifier: "lightbulb.led.fill")

	static public let lightbulb_led_wide = SFSymbol(identifier: "lightbulb.led.wide")

	static public let lightbulb_led_wide_fill = SFSymbol(identifier: "lightbulb.led.wide.fill")

	static public let fan_oscillation = SFSymbol(identifier: "fan.oscillation")

	static public let fan_oscillation_fill = SFSymbol(identifier: "fan.oscillation.fill")

	static public let fan_desk = SFSymbol(identifier: "fan.desk")

	static public let fan_desk_fill = SFSymbol(identifier: "fan.desk.fill")

	static public let fan_floor = SFSymbol(identifier: "fan.floor")

	static public let fan_floor_fill = SFSymbol(identifier: "fan.floor.fill")

	static public let fan_ceiling = SFSymbol(identifier: "fan.ceiling")

	static public let fan_ceiling_fill = SFSymbol(identifier: "fan.ceiling.fill")

	static public let fan_and_light_ceiling = SFSymbol(identifier: "fan.and.light.ceiling")

	static public let fan_and_light_ceiling_fill = SFSymbol(identifier: "fan.and.light.ceiling.fill")

	static public let lamp_desk = SFSymbol(identifier: "lamp.desk")

	static public let lamp_desk_fill = SFSymbol(identifier: "lamp.desk.fill")

	static public let lamp_table = SFSymbol(identifier: "lamp.table")

	static public let lamp_table_fill = SFSymbol(identifier: "lamp.table.fill")

	static public let lamp_floor = SFSymbol(identifier: "lamp.floor")

	static public let lamp_floor_fill = SFSymbol(identifier: "lamp.floor.fill")

	static public let lamp_ceiling = SFSymbol(identifier: "lamp.ceiling")

	static public let lamp_ceiling_fill = SFSymbol(identifier: "lamp.ceiling.fill")

	static public let lamp_ceiling_inverse = SFSymbol(identifier: "lamp.ceiling.inverse")

	static public let light_recessed = SFSymbol(identifier: "light.recessed")

	static public let light_recessed_fill = SFSymbol(identifier: "light.recessed.fill")

	static public let light_recessed_inverse = SFSymbol(identifier: "light.recessed.inverse")

	static public let light_recessed_3 = SFSymbol(identifier: "light.recessed.3")

	static public let light_recessed_3_fill = SFSymbol(identifier: "light.recessed.3.fill")

	static public let light_recessed_3_inverse = SFSymbol(identifier: "light.recessed.3.inverse")

	static public let light_panel = SFSymbol(identifier: "light.panel")

	static public let light_panel_fill = SFSymbol(identifier: "light.panel.fill")

	static public let light_cylindrical_ceiling = SFSymbol(identifier: "light.cylindrical.ceiling")

	static public let light_cylindrical_ceiling_fill = SFSymbol(identifier: "light.cylindrical.ceiling.fill")

	static public let light_cylindrical_ceiling_inverse = SFSymbol(identifier: "light.cylindrical.ceiling.inverse")

	static public let light_strip_2 = SFSymbol(identifier: "light.strip.2")

	static public let light_strip_2_fill = SFSymbol(identifier: "light.strip.2.fill")

	static public let light_ribbon = SFSymbol(identifier: "light.ribbon")

	static public let light_ribbon_fill = SFSymbol(identifier: "light.ribbon.fill")

	static public let chandelier = SFSymbol(identifier: "chandelier")

	static public let chandelier_fill = SFSymbol(identifier: "chandelier.fill")

	static public let lightswitch_on = SFSymbol(identifier: "lightswitch.on")

	static public let lightswitch_on_fill = SFSymbol(identifier: "lightswitch.on.fill")

	static public let lightswitch_on_square = SFSymbol(identifier: "lightswitch.on.square")

	static public let lightswitch_on_square_fill = SFSymbol(identifier: "lightswitch.on.square.fill")

	static public let lightswitch_off = SFSymbol(identifier: "lightswitch.off")

	static public let lightswitch_off_fill = SFSymbol(identifier: "lightswitch.off.fill")

	static public let lightswitch_off_square = SFSymbol(identifier: "lightswitch.off.square")

	static public let lightswitch_off_square_fill = SFSymbol(identifier: "lightswitch.off.square.fill")

	static public let button_programmable = SFSymbol(identifier: "button.programmable")

	static public let button_programmable_square = SFSymbol(identifier: "button.programmable.square")

	static public let button_programmable_square_fill = SFSymbol(identifier: "button.programmable.square.fill")

	static public let switch_programmable = SFSymbol(identifier: "switch.programmable")

	static public let switch_programmable_fill = SFSymbol(identifier: "switch.programmable.fill")

	static public let switch_programmable_square = SFSymbol(identifier: "switch.programmable.square")

	static public let switch_programmable_square_fill = SFSymbol(identifier: "switch.programmable.square.fill")

	static public let poweroutlet_type_a = SFSymbol(identifier: "poweroutlet.type.a")

	static public let poweroutlet_type_a_fill = SFSymbol(identifier: "poweroutlet.type.a.fill")

	static public let poweroutlet_type_a_square = SFSymbol(identifier: "poweroutlet.type.a.square")

	static public let poweroutlet_type_a_square_fill = SFSymbol(identifier: "poweroutlet.type.a.square.fill")

	static public let poweroutlet_type_b = SFSymbol(identifier: "poweroutlet.type.b")

	static public let poweroutlet_type_b_fill = SFSymbol(identifier: "poweroutlet.type.b.fill")

	static public let poweroutlet_type_b_square = SFSymbol(identifier: "poweroutlet.type.b.square")

	static public let poweroutlet_type_b_square_fill = SFSymbol(identifier: "poweroutlet.type.b.square.fill")

	static public let poweroutlet_type_c = SFSymbol(identifier: "poweroutlet.type.c")

	static public let poweroutlet_type_c_fill = SFSymbol(identifier: "poweroutlet.type.c.fill")

	static public let poweroutlet_type_c_square = SFSymbol(identifier: "poweroutlet.type.c.square")

	static public let poweroutlet_type_c_square_fill = SFSymbol(identifier: "poweroutlet.type.c.square.fill")

	static public let poweroutlet_type_d = SFSymbol(identifier: "poweroutlet.type.d")

	static public let poweroutlet_type_d_fill = SFSymbol(identifier: "poweroutlet.type.d.fill")

	static public let poweroutlet_type_d_square = SFSymbol(identifier: "poweroutlet.type.d.square")

	static public let poweroutlet_type_d_square_fill = SFSymbol(identifier: "poweroutlet.type.d.square.fill")

	static public let poweroutlet_type_e = SFSymbol(identifier: "poweroutlet.type.e")

	static public let poweroutlet_type_e_fill = SFSymbol(identifier: "poweroutlet.type.e.fill")

	static public let poweroutlet_type_e_square = SFSymbol(identifier: "poweroutlet.type.e.square")

	static public let poweroutlet_type_e_square_fill = SFSymbol(identifier: "poweroutlet.type.e.square.fill")

	static public let poweroutlet_type_f = SFSymbol(identifier: "poweroutlet.type.f")

	static public let poweroutlet_type_f_fill = SFSymbol(identifier: "poweroutlet.type.f.fill")

	static public let poweroutlet_type_f_square = SFSymbol(identifier: "poweroutlet.type.f.square")

	static public let poweroutlet_type_f_square_fill = SFSymbol(identifier: "poweroutlet.type.f.square.fill")

	static public let poweroutlet_type_g = SFSymbol(identifier: "poweroutlet.type.g")

	static public let poweroutlet_type_g_fill = SFSymbol(identifier: "poweroutlet.type.g.fill")

	static public let poweroutlet_type_g_square = SFSymbol(identifier: "poweroutlet.type.g.square")

	static public let poweroutlet_type_g_square_fill = SFSymbol(identifier: "poweroutlet.type.g.square.fill")

	static public let poweroutlet_type_h = SFSymbol(identifier: "poweroutlet.type.h")

	static public let poweroutlet_type_h_fill = SFSymbol(identifier: "poweroutlet.type.h.fill")

	static public let poweroutlet_type_h_square = SFSymbol(identifier: "poweroutlet.type.h.square")

	static public let poweroutlet_type_h_square_fill = SFSymbol(identifier: "poweroutlet.type.h.square.fill")

	static public let poweroutlet_type_i = SFSymbol(identifier: "poweroutlet.type.i")

	static public let poweroutlet_type_i_fill = SFSymbol(identifier: "poweroutlet.type.i.fill")

	static public let poweroutlet_type_i_square = SFSymbol(identifier: "poweroutlet.type.i.square")

	static public let poweroutlet_type_i_square_fill = SFSymbol(identifier: "poweroutlet.type.i.square.fill")

	static public let poweroutlet_type_j = SFSymbol(identifier: "poweroutlet.type.j")

	static public let poweroutlet_type_j_fill = SFSymbol(identifier: "poweroutlet.type.j.fill")

	static public let poweroutlet_type_j_square = SFSymbol(identifier: "poweroutlet.type.j.square")

	static public let poweroutlet_type_j_square_fill = SFSymbol(identifier: "poweroutlet.type.j.square.fill")

	static public let poweroutlet_type_k = SFSymbol(identifier: "poweroutlet.type.k")

	static public let poweroutlet_type_k_fill = SFSymbol(identifier: "poweroutlet.type.k.fill")

	static public let poweroutlet_type_k_square = SFSymbol(identifier: "poweroutlet.type.k.square")

	static public let poweroutlet_type_k_square_fill = SFSymbol(identifier: "poweroutlet.type.k.square.fill")

	static public let poweroutlet_type_l = SFSymbol(identifier: "poweroutlet.type.l")

	static public let poweroutlet_type_l_fill = SFSymbol(identifier: "poweroutlet.type.l.fill")

	static public let poweroutlet_type_l_square = SFSymbol(identifier: "poweroutlet.type.l.square")

	static public let poweroutlet_type_l_square_fill = SFSymbol(identifier: "poweroutlet.type.l.square.fill")

	static public let poweroutlet_type_m = SFSymbol(identifier: "poweroutlet.type.m")

	static public let poweroutlet_type_m_fill = SFSymbol(identifier: "poweroutlet.type.m.fill")

	static public let poweroutlet_type_m_square = SFSymbol(identifier: "poweroutlet.type.m.square")

	static public let poweroutlet_type_m_square_fill = SFSymbol(identifier: "poweroutlet.type.m.square.fill")

	static public let poweroutlet_type_n = SFSymbol(identifier: "poweroutlet.type.n")

	static public let poweroutlet_type_n_fill = SFSymbol(identifier: "poweroutlet.type.n.fill")

	static public let poweroutlet_type_n_square = SFSymbol(identifier: "poweroutlet.type.n.square")

	static public let poweroutlet_type_n_square_fill = SFSymbol(identifier: "poweroutlet.type.n.square.fill")

	static public let poweroutlet_type_o = SFSymbol(identifier: "poweroutlet.type.o")

	static public let poweroutlet_type_o_fill = SFSymbol(identifier: "poweroutlet.type.o.fill")

	static public let poweroutlet_type_o_square = SFSymbol(identifier: "poweroutlet.type.o.square")

	static public let poweroutlet_type_o_square_fill = SFSymbol(identifier: "poweroutlet.type.o.square.fill")

	static public let poweroutlet_strip = SFSymbol(identifier: "poweroutlet.strip")

	static public let poweroutlet_strip_fill = SFSymbol(identifier: "poweroutlet.strip.fill")

	static public let light_beacon_min = SFSymbol(identifier: "light.beacon.min")

	static public let light_beacon_min_fill = SFSymbol(identifier: "light.beacon.min.fill")

	static public let light_beacon_max = SFSymbol(identifier: "light.beacon.max")

	static public let light_beacon_max_fill = SFSymbol(identifier: "light.beacon.max.fill")

	static public let web_camera = SFSymbol(identifier: "web.camera")

	static public let web_camera_fill = SFSymbol(identifier: "web.camera.fill")

	static public let video_doorbell = SFSymbol(identifier: "video.doorbell")

	static public let video_doorbell_fill = SFSymbol(identifier: "video.doorbell.fill")

	static public let entry_lever_keypad = SFSymbol(identifier: "entry.lever.keypad")

	static public let entry_lever_keypad_fill = SFSymbol(identifier: "entry.lever.keypad.fill")

	static public let entry_lever_keypad_trianglebadge_exclamationmark = SFSymbol(identifier: "entry.lever.keypad.trianglebadge.exclamationmark")

	static public let entry_lever_keypad_trianglebadge_exclamationmark_fill = SFSymbol(identifier: "entry.lever.keypad.trianglebadge.exclamationmark.fill")

	static public let door_left_hand_open = SFSymbol(identifier: "door.left.hand.open")

	static public let door_left_hand_closed = SFSymbol(identifier: "door.left.hand.closed")

	static public let door_right_hand_open = SFSymbol(identifier: "door.right.hand.open")

	static public let door_right_hand_closed = SFSymbol(identifier: "door.right.hand.closed")

	static public let door_sliding_left_hand_open = SFSymbol(identifier: "door.sliding.left.hand.open")

	static public let door_sliding_left_hand_closed = SFSymbol(identifier: "door.sliding.left.hand.closed")

	static public let door_sliding_right_hand_open = SFSymbol(identifier: "door.sliding.right.hand.open")

	static public let door_sliding_right_hand_closed = SFSymbol(identifier: "door.sliding.right.hand.closed")

	static public let door_garage_open = SFSymbol(identifier: "door.garage.open")

	static public let door_garage_closed = SFSymbol(identifier: "door.garage.closed")

	static public let door_garage_open_trianglebadge_exclamationmark = SFSymbol(identifier: "door.garage.open.trianglebadge.exclamationmark")

	static public let door_garage_closed_trianglebadge_exclamationmark = SFSymbol(identifier: "door.garage.closed.trianglebadge.exclamationmark")

	static public let door_garage_double_bay_open = SFSymbol(identifier: "door.garage.double.bay.open")

	static public let door_garage_double_bay_closed = SFSymbol(identifier: "door.garage.double.bay.closed")

	static public let door_garage_double_bay_open_trianglebadge_exclamationmark = SFSymbol(identifier: "door.garage.double.bay.open.trianglebadge.exclamationmark")

	static public let door_garage_double_bay_closed_trianglebadge_exclamationmark = SFSymbol(identifier: "door.garage.double.bay.closed.trianglebadge.exclamationmark")

	static public let door_french_open = SFSymbol(identifier: "door.french.open")

	static public let door_french_closed = SFSymbol(identifier: "door.french.closed")

	static public let pedestrian_gate_closed = SFSymbol(identifier: "pedestrian.gate.closed")

	static public let pedestrian_gate_open = SFSymbol(identifier: "pedestrian.gate.open")

	static public let window_vertical_open = SFSymbol(identifier: "window.vertical.open")

	static public let window_vertical_closed = SFSymbol(identifier: "window.vertical.closed")

	static public let window_horizontal = SFSymbol(identifier: "window.horizontal")

	static public let window_horizontal_closed = SFSymbol(identifier: "window.horizontal.closed")

	static public let window_ceiling = SFSymbol(identifier: "window.ceiling")

	static public let window_ceiling_closed = SFSymbol(identifier: "window.ceiling.closed")

	static public let window_casement = SFSymbol(identifier: "window.casement")

	static public let window_casement_closed = SFSymbol(identifier: "window.casement.closed")

	static public let window_awning = SFSymbol(identifier: "window.awning")

	static public let window_awning_closed = SFSymbol(identifier: "window.awning.closed")

	static public let blinds_vertical_open = SFSymbol(identifier: "blinds.vertical.open")

	static public let blinds_vertical_closed = SFSymbol(identifier: "blinds.vertical.closed")

	static public let blinds_horizontal_open = SFSymbol(identifier: "blinds.horizontal.open")

	static public let blinds_horizontal_closed = SFSymbol(identifier: "blinds.horizontal.closed")

	static public let window_shade_open = SFSymbol(identifier: "window.shade.open")

	static public let window_shade_closed = SFSymbol(identifier: "window.shade.closed")

	static public let roller_shade_open = SFSymbol(identifier: "roller.shade.open")

	static public let roller_shade_closed = SFSymbol(identifier: "roller.shade.closed")

	static public let roman_shade_open = SFSymbol(identifier: "roman.shade.open")

	static public let roman_shade_closed = SFSymbol(identifier: "roman.shade.closed")

	static public let curtains_open = SFSymbol(identifier: "curtains.open")

	static public let curtains_closed = SFSymbol(identifier: "curtains.closed")

	static public let air_purifier = SFSymbol(identifier: "air.purifier")

	static public let air_purifier_fill = SFSymbol(identifier: "air.purifier.fill")

	static public let dehumidifier = SFSymbol(identifier: "dehumidifier")

	static public let dehumidifier_fill = SFSymbol(identifier: "dehumidifier.fill")

	static public let humidifier = SFSymbol(identifier: "humidifier")

	static public let humidifier_fill = SFSymbol(identifier: "humidifier.fill")

	static public let humidifier_and_droplets = SFSymbol(identifier: "humidifier.and.droplets")

	static public let humidifier_and_droplets_fill = SFSymbol(identifier: "humidifier.and.droplets.fill")

	static public let heater_vertical = SFSymbol(identifier: "heater.vertical")

	static public let heater_vertical_fill = SFSymbol(identifier: "heater.vertical.fill")

	static public let air_conditioner_vertical = SFSymbol(identifier: "air.conditioner.vertical")

	static public let air_conditioner_vertical_fill = SFSymbol(identifier: "air.conditioner.vertical.fill")

	static public let air_conditioner_horizontal = SFSymbol(identifier: "air.conditioner.horizontal")

	static public let air_conditioner_horizontal_fill = SFSymbol(identifier: "air.conditioner.horizontal.fill")

	static public let sprinkler = SFSymbol(identifier: "sprinkler")

	static public let sprinkler_fill = SFSymbol(identifier: "sprinkler.fill")

	static public let sprinkler_and_droplets = SFSymbol(identifier: "sprinkler.and.droplets")

	static public let sprinkler_and_droplets_fill = SFSymbol(identifier: "sprinkler.and.droplets.fill")

	static public let spigot = SFSymbol(identifier: "spigot")

	static public let spigot_fill = SFSymbol(identifier: "spigot.fill")

	static public let drop_keypad_rectangle = SFSymbol(identifier: "drop.keypad.rectangle")

	static public let drop_keypad_rectangle_fill = SFSymbol(identifier: "drop.keypad.rectangle.fill")

	static public let shower_sidejet = SFSymbol(identifier: "shower.sidejet")

	static public let shower_sidejet_fill = SFSymbol(identifier: "shower.sidejet.fill")

	static public let shower = SFSymbol(identifier: "shower")

	static public let shower_fill = SFSymbol(identifier: "shower.fill")

	static public let shower_handheld = SFSymbol(identifier: "shower.handheld")

	static public let shower_handheld_fill = SFSymbol(identifier: "shower.handheld.fill")

	static public let bathtub = SFSymbol(identifier: "bathtub")

	static public let bathtub_fill = SFSymbol(identifier: "bathtub.fill")

	static public let contact_sensor = SFSymbol(identifier: "contact.sensor")

	static public let contact_sensor_fill = SFSymbol(identifier: "contact.sensor.fill")

	static public let sensor = SFSymbol(identifier: "sensor")

	static public let sensor_fill = SFSymbol(identifier: "sensor.fill")

	static public let carbon_monoxide_cloud = SFSymbol(identifier: "carbon.monoxide.cloud")

	static public let carbon_monoxide_cloud_fill = SFSymbol(identifier: "carbon.monoxide.cloud.fill")

	static public let carbon_dioxide_cloud = SFSymbol(identifier: "carbon.dioxide.cloud")

	static public let carbon_dioxide_cloud_fill = SFSymbol(identifier: "carbon.dioxide.cloud.fill")

	static public let pipe_and_drop = SFSymbol(identifier: "pipe.and.drop")

	static public let pipe_and_drop_fill = SFSymbol(identifier: "pipe.and.drop.fill")

	static public let hifireceiver = SFSymbol(identifier: "hifireceiver")

	static public let hifireceiver_fill = SFSymbol(identifier: "hifireceiver.fill")

	static public let videoprojector = SFSymbol(identifier: "videoprojector")

	static public let videoprojector_fill = SFSymbol(identifier: "videoprojector.fill")

	static public let wifi_router = SFSymbol(identifier: "wifi.router")

	static public let wifi_router_fill = SFSymbol(identifier: "wifi.router.fill")

	static public let party_popper = SFSymbol(identifier: "party.popper")

	static public let party_popper_fill = SFSymbol(identifier: "party.popper.fill")

	static public let balloon = SFSymbol(identifier: "balloon")

	static public let balloon_fill = SFSymbol(identifier: "balloon.fill")

	static public let balloon_2 = SFSymbol(identifier: "balloon.2")

	static public let balloon_2_fill = SFSymbol(identifier: "balloon.2.fill")

	static public let frying_pan = SFSymbol(identifier: "frying.pan")

	static public let frying_pan_fill = SFSymbol(identifier: "frying.pan.fill")

	static public let popcorn = SFSymbol(identifier: "popcorn")

	static public let popcorn_fill = SFSymbol(identifier: "popcorn.fill")

	static public let popcorn_circle = SFSymbol(identifier: "popcorn.circle")

	static public let popcorn_circle_fill = SFSymbol(identifier: "popcorn.circle.fill")

	static public let sofa = SFSymbol(identifier: "sofa")

	static public let sofa_fill = SFSymbol(identifier: "sofa.fill")

	static public let chair_lounge = SFSymbol(identifier: "chair.lounge")

	static public let chair_lounge_fill = SFSymbol(identifier: "chair.lounge.fill")

	static public let chair = SFSymbol(identifier: "chair")

	static public let chair_fill = SFSymbol(identifier: "chair.fill")

	static public let table_furniture = SFSymbol(identifier: "table.furniture")

	static public let table_furniture_fill = SFSymbol(identifier: "table.furniture.fill")

	static public let cabinet = SFSymbol(identifier: "cabinet")

	static public let cabinet_fill = SFSymbol(identifier: "cabinet.fill")

	static public let fireplace = SFSymbol(identifier: "fireplace")

	static public let fireplace_fill = SFSymbol(identifier: "fireplace.fill")

	static public let washer = SFSymbol(identifier: "washer")

	static public let washer_fill = SFSymbol(identifier: "washer.fill")

	static public let dryer = SFSymbol(identifier: "dryer")

	static public let dryer_fill = SFSymbol(identifier: "dryer.fill")

	static public let dishwasher = SFSymbol(identifier: "dishwasher")

	static public let dishwasher_fill = SFSymbol(identifier: "dishwasher.fill")

	static public let oven = SFSymbol(identifier: "oven")

	static public let oven_fill = SFSymbol(identifier: "oven.fill")

	static public let stove = SFSymbol(identifier: "stove")

	static public let stove_fill = SFSymbol(identifier: "stove.fill")

	static public let cooktop = SFSymbol(identifier: "cooktop")

	static public let cooktop_fill = SFSymbol(identifier: "cooktop.fill")

	static public let microwave = SFSymbol(identifier: "microwave")

	static public let microwave_fill = SFSymbol(identifier: "microwave.fill")

	static public let refrigerator = SFSymbol(identifier: "refrigerator")

	static public let refrigerator_fill = SFSymbol(identifier: "refrigerator.fill")

	static public let sink = SFSymbol(identifier: "sink")

	static public let sink_fill = SFSymbol(identifier: "sink.fill")

	static public let toilet = SFSymbol(identifier: "toilet")

	static public let toilet_fill = SFSymbol(identifier: "toilet.fill")

	static public let stairs = SFSymbol(identifier: "stairs")

	static public let tent = SFSymbol(identifier: "tent")

	static public let tent_fill = SFSymbol(identifier: "tent.fill")

	static public let lock_trianglebadge_exclamationmark = SFSymbol(identifier: "lock.trianglebadge.exclamationmark")

	static public let lock_trianglebadge_exclamationmark_fill = SFSymbol(identifier: "lock.trianglebadge.exclamationmark.fill")

	static public let exclamationmark_lock = SFSymbol(identifier: "exclamationmark.lock")

	static public let exclamationmark_lock_fill = SFSymbol(identifier: "exclamationmark.lock.fill")

	static public let lock_open_trianglebadge_exclamationmark = SFSymbol(identifier: "lock.open.trianglebadge.exclamationmark")

	static public let lock_open_trianglebadge_exclamationmark_fill = SFSymbol(identifier: "lock.open.trianglebadge.exclamationmark.fill")

	static public let opticaldisc_fill = SFSymbol(identifier: "opticaldisc.fill")

	static public let play_display = SFSymbol(identifier: "play.display")

	static public let play_desktopcomputer = SFSymbol(identifier: "play.desktopcomputer")

	static public let play_laptopcomputer = SFSymbol(identifier: "play.laptopcomputer")

	static public let macstudio = SFSymbol(identifier: "macstudio")

	static public let macstudio_fill = SFSymbol(identifier: "macstudio.fill")

	static public let arrow_up_and_down_and_sparkles = SFSymbol(identifier: "arrow.up.and.down.and.sparkles")

	static public let homepod_and_appletv_rtl = SFSymbol(identifier: "homepod.and.appletv.rtl")

	static public let homepod_and_appletv_fill_rtl = SFSymbol(identifier: "homepod.and.appletv.fill.rtl")

	static public let hifispeaker_and_appletv_rtl = SFSymbol(identifier: "hifispeaker.and.appletv.rtl")

	static public let hifispeaker_and_appletv_fill_rtl = SFSymbol(identifier: "hifispeaker.and.appletv.fill.rtl")

	static public let av_remote = SFSymbol(identifier: "av.remote")

	static public let av_remote_fill = SFSymbol(identifier: "av.remote.fill")

	static public let tv_and_mediabox_fill = SFSymbol(identifier: "tv.and.mediabox.fill")

	static public let shazam_logo = SFSymbol(identifier: "shazam.logo")

	static public let shazam_logo_fill = SFSymbol(identifier: "shazam.logo.fill")

	static public let sailboat = SFSymbol(identifier: "sailboat")

	static public let sailboat_fill = SFSymbol(identifier: "sailboat.fill")

	static public let headlight_high_beam = SFSymbol(identifier: "headlight.high.beam")

	static public let headlight_high_beam_fill = SFSymbol(identifier: "headlight.high.beam.fill")

	static public let headlight_low_beam = SFSymbol(identifier: "headlight.low.beam")

	static public let headlight_low_beam_fill = SFSymbol(identifier: "headlight.low.beam.fill")

	static public let parkinglight = SFSymbol(identifier: "parkinglight")

	static public let parkinglight_fill = SFSymbol(identifier: "parkinglight.fill")

	static public let windshield_front_and_wiper = SFSymbol(identifier: "windshield.front.and.wiper")

	static public let windshield_front_and_wiper_and_drop = SFSymbol(identifier: "windshield.front.and.wiper.and.drop")

	static public let windshield_rear_and_wiper = SFSymbol(identifier: "windshield.rear.and.wiper")

	static public let mirror_side_left = SFSymbol(identifier: "mirror.side.left")

	static public let mirror_side_right = SFSymbol(identifier: "mirror.side.right")

	static public let brakesignal = SFSymbol(identifier: "brakesignal")

	static public let exclamationmark_brakesignal = SFSymbol(identifier: "exclamationmark.brakesignal")

	static public let parkingsign_brakesignal = SFSymbol(identifier: "parkingsign.brakesignal")

	static public let parkingsign_brakesignal_slash = SFSymbol(identifier: "parkingsign.brakesignal.slash")

	static public let abs_brakesignal = SFSymbol(identifier: "abs.brakesignal")

	static public let hold_brakesignal = SFSymbol(identifier: "hold.brakesignal")

	static public let thermometer_brakesignal = SFSymbol(identifier: "thermometer.brakesignal")

	static public let bolt_brakesignal = SFSymbol(identifier: "bolt.brakesignal")

	static public let fluid_brakesignal = SFSymbol(identifier: "fluid.brakesignal")

	static public let brakesignal_dashed = SFSymbol(identifier: "brakesignal.dashed")

	static public let road_lanes = SFSymbol(identifier: "road.lanes")

	static public let road_lanes_curved_left = SFSymbol(identifier: "road.lanes.curved.left")

	static public let road_lanes_curved_right = SFSymbol(identifier: "road.lanes.curved.right")

	static public let allergens_fill = SFSymbol(identifier: "allergens.fill")

	static public let microbe = SFSymbol(identifier: "microbe")

	static public let microbe_fill = SFSymbol(identifier: "microbe.fill")

	static public let microbe_circle = SFSymbol(identifier: "microbe.circle")

	static public let microbe_circle_fill = SFSymbol(identifier: "microbe.circle.fill")

	static public let bubbles_and_sparkles = SFSymbol(identifier: "bubbles.and.sparkles")

	static public let bubbles_and_sparkles_fill = SFSymbol(identifier: "bubbles.and.sparkles.fill")

	static public let medical_thermometer = SFSymbol(identifier: "medical.thermometer")

	static public let medical_thermometer_fill = SFSymbol(identifier: "medical.thermometer.fill")

	static public let syringe = SFSymbol(identifier: "syringe")

	static public let syringe_fill = SFSymbol(identifier: "syringe.fill")

	static public let pill = SFSymbol(identifier: "pill")

	static public let pill_fill = SFSymbol(identifier: "pill.fill")

	static public let pill_circle = SFSymbol(identifier: "pill.circle")

	static public let pill_circle_fill = SFSymbol(identifier: "pill.circle.fill")

	static public let lizard = SFSymbol(identifier: "lizard")

	static public let lizard_fill = SFSymbol(identifier: "lizard.fill")

	static public let bird = SFSymbol(identifier: "bird")

	static public let bird_fill = SFSymbol(identifier: "bird.fill")

	static public let fish = SFSymbol(identifier: "fish")

	static public let fish_fill = SFSymbol(identifier: "fish.fill")

	static public let teddybear = SFSymbol(identifier: "teddybear")

	static public let teddybear_fill = SFSymbol(identifier: "teddybear.fill")

	static public let laurel_leading = SFSymbol(identifier: "laurel.leading")

	static public let laurel_trailing = SFSymbol(identifier: "laurel.trailing")

	static public let shoeprints_fill = SFSymbol(identifier: "shoeprints.fill")

	static public let film_stack = SFSymbol(identifier: "film.stack")

	static public let film_stack_fill = SFSymbol(identifier: "film.stack.fill")

	static public let face_smiling_inverse = SFSymbol(identifier: "face.smiling.inverse")

	static public let hearingdevice_ear_fill = SFSymbol(identifier: "hearingdevice.ear.fill")

	static public let hearingdevice_and_signal_meter = SFSymbol(identifier: "hearingdevice.and.signal.meter")

	static public let hearingdevice_and_signal_meter_fill = SFSymbol(identifier: "hearingdevice.and.signal.meter.fill")

	static public let hand_raised_fingers_spread = SFSymbol(identifier: "hand.raised.fingers.spread")

	static public let hand_raised_fingers_spread_fill = SFSymbol(identifier: "hand.raised.fingers.spread.fill")

	static public let creditcard_viewfinder = SFSymbol(identifier: "creditcard.viewfinder")

	static public let vial_viewfinder = SFSymbol(identifier: "vial.viewfinder")

	static public let circle_filled_pattern_diagonalline_rectangle = SFSymbol(identifier: "circle.filled.pattern.diagonalline.rectangle")

	static public let circle_rectangle_filled_pattern_diagonalline = SFSymbol(identifier: "circle.rectangle.filled.pattern.diagonalline")

	static public let circle_dashed_rectangle = SFSymbol(identifier: "circle.dashed.rectangle")

	static public let circle_rectangle_dashed = SFSymbol(identifier: "circle.rectangle.dashed")

	static public let photo_stack = SFSymbol(identifier: "photo.stack")

	static public let photo_stack_fill = SFSymbol(identifier: "photo.stack.fill")

	static public let squares_leading_rectangle = SFSymbol(identifier: "squares.leading.rectangle")

	static public let distribute_vertical_top = SFSymbol(identifier: "distribute.vertical.top")

	static public let distribute_vertical_top_fill = SFSymbol(identifier: "distribute.vertical.top.fill")

	static public let distribute_vertical_center = SFSymbol(identifier: "distribute.vertical.center")

	static public let distribute_vertical_center_fill = SFSymbol(identifier: "distribute.vertical.center.fill")

	static public let distribute_vertical_bottom = SFSymbol(identifier: "distribute.vertical.bottom")

	static public let distribute_vertical_bottom_fill = SFSymbol(identifier: "distribute.vertical.bottom.fill")

	static public let distribute_horizontal_left = SFSymbol(identifier: "distribute.horizontal.left")

	static public let distribute_horizontal_left_fill = SFSymbol(identifier: "distribute.horizontal.left.fill")

	static public let distribute_horizontal_center = SFSymbol(identifier: "distribute.horizontal.center")

	static public let distribute_horizontal_center_fill = SFSymbol(identifier: "distribute.horizontal.center.fill")

	static public let distribute_horizontal_right = SFSymbol(identifier: "distribute.horizontal.right")

	static public let distribute_horizontal_right_fill = SFSymbol(identifier: "distribute.horizontal.right.fill")

	static public let slider_horizontal_2_square_on_square = SFSymbol(identifier: "slider.horizontal.2.square.on.square")

	static public let slider_horizontal_2_square_badge_arrow_down = SFSymbol(identifier: "slider.horizontal.2.square.badge.arrow.down")

	static public let slider_horizontal_below_square_and_square_filled = SFSymbol(identifier: "slider.horizontal.below.square.and.square.filled")

	static public let shippingbox_and_arrow_backward = SFSymbol(identifier: "shippingbox.and.arrow.backward")

	static public let shippingbox_and_arrow_backward_fill = SFSymbol(identifier: "shippingbox.and.arrow.backward.fill")

	static public let clock_badge = SFSymbol(identifier: "clock.badge")

	static public let clock_badge_fill = SFSymbol(identifier: "clock.badge.fill")

	static public let clock_badge_xmark = SFSymbol(identifier: "clock.badge.xmark")

	static public let clock_badge_xmark_fill = SFSymbol(identifier: "clock.badge.xmark.fill")

	static public let clock_badge_questionmark = SFSymbol(identifier: "clock.badge.questionmark")

	static public let clock_badge_questionmark_fill = SFSymbol(identifier: "clock.badge.questionmark.fill")

	static public let clock_badge_questionmark_ar = SFSymbol(identifier: "clock.badge.questionmark.ar")

	static public let clock_badge_questionmark_fill_ar = SFSymbol(identifier: "clock.badge.questionmark.fill.ar")

	static public let alarm_waves_left_and_right = SFSymbol(identifier: "alarm.waves.left.and.right")

	static public let alarm_waves_left_and_right_fill = SFSymbol(identifier: "alarm.waves.left.and.right.fill")

	static public let timer_circle = SFSymbol(identifier: "timer.circle")

	static public let timer_circle_fill = SFSymbol(identifier: "timer.circle.fill")

	static public let playstation_logo = SFSymbol(identifier: "playstation.logo")

	static public let xbox_logo = SFSymbol(identifier: "xbox.logo")

	static public let swatchpalette = SFSymbol(identifier: "swatchpalette")

	static public let swatchpalette_fill = SFSymbol(identifier: "swatchpalette.fill")

	static public let wineglass = SFSymbol(identifier: "wineglass")

	static public let wineglass_fill = SFSymbol(identifier: "wineglass.fill")

	static public let birthday_cake = SFSymbol(identifier: "birthday.cake")

	static public let birthday_cake_fill = SFSymbol(identifier: "birthday.cake.fill")

	static public let carrot = SFSymbol(identifier: "carrot")

	static public let carrot_fill = SFSymbol(identifier: "carrot.fill")

	static public let square_2_layers_3d = SFSymbol(identifier: "square.2.layers.3d")

	static public let square_2_layers_3d_top_filled = SFSymbol(identifier: "square.2.layers.3d.top.filled")

	static public let square_2_layers_3d_bottom_filled = SFSymbol(identifier: "square.2.layers.3d.bottom.filled")

	static public let square_3_layers_3d_down_forward_slash_rtl = SFSymbol(identifier: "square.3.layers.3d.down.forward.slash.rtl")

	static public let square_3_layers_3d_down_backward_slash_rtl = SFSymbol(identifier: "square.3.layers.3d.down.backward.slash.rtl")

	static public let square_3_layers_3d = SFSymbol(identifier: "square.3.layers.3d")

	static public let square_3_layers_3d_slash = SFSymbol(identifier: "square.3.layers.3d.slash")

	static public let square_3_layers_3d_top_filled = SFSymbol(identifier: "square.3.layers.3d.top.filled")

	static public let square_3_layers_3d_middle_filled = SFSymbol(identifier: "square.3.layers.3d.middle.filled")

	static public let square_3_layers_3d_bottom_filled = SFSymbol(identifier: "square.3.layers.3d.bottom.filled")

	static public let cellularbars = SFSymbol(identifier: "cellularbars")

	static public let chart_line_downtrend_xyaxis = SFSymbol(identifier: "chart.line.downtrend.xyaxis")

	static public let chart_line_downtrend_xyaxis_circle = SFSymbol(identifier: "chart.line.downtrend.xyaxis.circle")

	static public let chart_line_downtrend_xyaxis_circle_fill = SFSymbol(identifier: "chart.line.downtrend.xyaxis.circle.fill")

	static public let chart_line_flattrend_xyaxis = SFSymbol(identifier: "chart.line.flattrend.xyaxis")

	static public let chart_line_flattrend_xyaxis_circle = SFSymbol(identifier: "chart.line.flattrend.xyaxis.circle")

	static public let chart_line_flattrend_xyaxis_circle_fill = SFSymbol(identifier: "chart.line.flattrend.xyaxis.circle.fill")

	static public let waveform_slash = SFSymbol(identifier: "waveform.slash")

	static public let angle = SFSymbol(identifier: "angle")

	static public let compass_drawing = SFSymbol(identifier: "compass.drawing")

	static public let globe_desk = SFSymbol(identifier: "globe.desk")

	static public let globe_desk_fill = SFSymbol(identifier: "globe.desk.fill")

	static public let fossil_shell = SFSymbol(identifier: "fossil.shell")

	static public let fossil_shell_fill = SFSymbol(identifier: "fossil.shell.fill")

	static public let recordingtape_circle = SFSymbol(identifier: "recordingtape.circle")

	static public let recordingtape_circle_fill = SFSymbol(identifier: "recordingtape.circle.fill")

	static public let checklist_unchecked = SFSymbol(identifier: "checklist.unchecked")

	static public let checklist_checked = SFSymbol(identifier: "checklist.checked")

	static public let checklist_checked_rtl = SFSymbol(identifier: "checklist.checked.rtl")

	static public let quotelevel = SFSymbol(identifier: "quotelevel")

	static public let text_line_first_and_arrowtriangle_forward = SFSymbol(identifier: "text.line.first.and.arrowtriangle.forward")

	static public let text_line_last_and_arrowtriangle_forward = SFSymbol(identifier: "text.line.last.and.arrowtriangle.forward")

	static public let text_word_spacing = SFSymbol(identifier: "text.word.spacing")

	static public let arrow_up_and_down_text_horizontal = SFSymbol(identifier: "arrow.up.and.down.text.horizontal")

	static public let arrow_left_and_right_text_vertical = SFSymbol(identifier: "arrow.left.and.right.text.vertical")

	static public let numbersign = SFSymbol(identifier: "numbersign")

	static public let character_sutton = SFSymbol(identifier: "character.sutton")

	static public let character_duployan = SFSymbol(identifier: "character.duployan")

	static public let character_phonetic = SFSymbol(identifier: "character.phonetic")

	static public let info_square = SFSymbol(identifier: "info.square")

	static public let info_square_fill = SFSymbol(identifier: "info.square.fill")

	static public let exclamationmark_questionmark = SFSymbol(identifier: "exclamationmark.questionmark")

	static public let exclamationmark_questionmark_ar = SFSymbol(identifier: "exclamationmark.questionmark.ar")

	static public let checkmark_circle_badge_questionmark = SFSymbol(identifier: "checkmark.circle.badge.questionmark")

	static public let checkmark_circle_badge_questionmark_fill = SFSymbol(identifier: "checkmark.circle.badge.questionmark.fill")

	static public let checkmark_circle_badge_questionmark_ar = SFSymbol(identifier: "checkmark.circle.badge.questionmark.ar")

	static public let checkmark_circle_badge_questionmark_fill_ar = SFSymbol(identifier: "checkmark.circle.badge.questionmark.fill.ar")

	static public let checkmark_circle_badge_xmark = SFSymbol(identifier: "checkmark.circle.badge.xmark")

	static public let checkmark_circle_badge_xmark_fill = SFSymbol(identifier: "checkmark.circle.badge.xmark.fill")

	static public let arrow_up_circle_badge_clock = SFSymbol(identifier: "arrow.up.circle.badge.clock")

	static public let arrow_left_and_line_vertical_and_arrow_right = SFSymbol(identifier: "arrow.left.and.line.vertical.and.arrow.right")

	static public let arrow_right_and_line_vertical_and_arrow_left = SFSymbol(identifier: "arrow.right.and.line.vertical.and.arrow.left")

	static public let arrow_down_and_line_horizontal_and_arrow_up = SFSymbol(identifier: "arrow.down.and.line.horizontal.and.arrow.up")

	static public let arrow_up_and_line_horizontal_and_arrow_down = SFSymbol(identifier: "arrow.up.and.line.horizontal.and.arrow.down")

	static public let australsign = SFSymbol(identifier: "australsign")

	static public let bahtsign = SFSymbol(identifier: "bahtsign")

	static public let bitcoinsign = SFSymbol(identifier: "bitcoinsign")

	static public let brazilianrealsign = SFSymbol(identifier: "brazilianrealsign")

	static public let cedisign = SFSymbol(identifier: "cedisign")

	static public let centsign = SFSymbol(identifier: "centsign")

	static public let coloncurrencysign = SFSymbol(identifier: "coloncurrencysign")

	static public let cruzeirosign = SFSymbol(identifier: "cruzeirosign")

	static public let dongsign = SFSymbol(identifier: "dongsign")

	static public let dollarsign = SFSymbol(identifier: "dollarsign")

	static public let eurosign = SFSymbol(identifier: "eurosign")

	static public let florinsign = SFSymbol(identifier: "florinsign")

	static public let francsign = SFSymbol(identifier: "francsign")

	static public let guaranisign = SFSymbol(identifier: "guaranisign")

	static public let hryvniasign = SFSymbol(identifier: "hryvniasign")

	static public let indianrupeesign = SFSymbol(identifier: "indianrupeesign")

	static public let kipsign = SFSymbol(identifier: "kipsign")

	static public let larisign = SFSymbol(identifier: "larisign")

	static public let lirasign = SFSymbol(identifier: "lirasign")

	static public let manatsign = SFSymbol(identifier: "manatsign")

	static public let millsign = SFSymbol(identifier: "millsign")

	static public let nairasign = SFSymbol(identifier: "nairasign")

	static public let pesetasign = SFSymbol(identifier: "pesetasign")

	static public let pesosign = SFSymbol(identifier: "pesosign")

	static public let rublesign = SFSymbol(identifier: "rublesign")

	static public let rupeesign = SFSymbol(identifier: "rupeesign")

	static public let shekelsign = SFSymbol(identifier: "shekelsign")

	static public let sterlingsign = SFSymbol(identifier: "sterlingsign")

	static public let tengesign = SFSymbol(identifier: "tengesign")

	static public let tugriksign = SFSymbol(identifier: "tugriksign")

	static public let turkishlirasign = SFSymbol(identifier: "turkishlirasign")

	static public let wonsign = SFSymbol(identifier: "wonsign")

	static public let yensign = SFSymbol(identifier: "yensign")

	static public let apple_logo = SFSymbol(identifier: "apple.logo")
}